### ISSUE TITLE
Item rename

### ISSUE THREAD

**Issue by fortunatas1** [Zrips/CMI#8769] opened 2024-05-23 07:31 UTC
### Description of Issue

When mob spawners is in blacklist for renaming and i'm trying rename it i'm lost exp.
https://streamable.com/qpsvqf

### Version Information

```shell
9.7.2.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment] 2024-05-23 07:37
please move this request to discussion i asume its not a bug its more a missing feature

https://github.com/Zrips/CMI/discussions/new?category=enhancement

**Comment by Zrips** [comment] 2024-05-24 09:10
Should be resolved with next update

**Closed by Zrips** 2024-05-24 09:10 UTC
Labels: bug report

**Comment by fortunatas1** [comment] 2024-06-02 17:49
It's not.
![image](https://github.com/Zrips/CMI/assets/74112805/c1d6bc88-197a-4b40-b247-1da2c12e36e6)
