### ISSUE TITLE
[Bug] - Random Teleport

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1777] opened 2019-05-17 20:21 UTC
**Description of issue or feature request:**
Random Teleport often teleports player to the same spot over and over again. Players on my server has come to the conclution that they can setup traps on those spots to kill them :)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
RandomTeleportation:
  Worlds:
    world:
      Enabled: true
      MaxRange: 9500
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 8.6.2.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-626 (MC: 1.13.2)

**Comment by abhisantos** [comment] 2019-05-18 19:29
This error is happening on my server too.
The plugin never finds a place to teleport the players

**Comment by Baktus79** [comment] 2019-06-08 19:14
#1870

**Comment by LogGits** [comment] 2019-06-20 08:10
Can confirm this is an actual issue, people are reporting to me that the RTP keeps teleporting them to the same locations often. Marking as confirmed.

**Comment by x1p** [comment] 2019-06-20 11:34
In addition since my issue was closed:

Players are very often teleported to the edge of the selected area, somewhere on the `maxX` or `maxY` coordinates too. I would say about 75% of the time or more.

This means that the player are always somewhere on the edge of the map.

**Comment by LogGits** [comment] 2019-09-15 15:19
@x1p are you still having this issue?

**Comment by LogGits** [comment] 2019-09-21 13:09
I believe this was fixed, if you are still experiencing this issue, please open a new ticket.

**Closed by LogGits** 2019-09-21 13:09 UTC
Labels: bug report, confirmed
