### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to CMI v8.7.5.2

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#3884] opened 2020-08-04 10:08 UTC
[11:07:52 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.7.5.2
java.lang.NoClassDefFoundError: com/gamingmesh/jobs/CmiItems/ItemManager$CMIChatColor
        at com.Zrips.CMI.Modules.ChatTag.TagListener.AsyncPlayerChatEvent(TagListener.java:61) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor811.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-131]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1825) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1740) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-131]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

Latest Paper 1.16.1

**Comment by CloudeLecaw** [comment] 2020-08-04 10:24
Duplicate of #3881 
Will be fixed in next Version.
Pls close the ticket :)

**Comment by Zrips** [comment] 2020-08-04 11:07
Yea, will get fixed with today's update

**Closed by Zrips** 2020-08-04 11:07 UTC
Labels: bug report
