### ISSUE TITLE
Unable to generate nether portal for less than y=0

### ISSUE THREAD

**Issue by NamiUni** [Zrips/CMI#5775] opened 2021-06-30 01:26 UTC
**Description of issue:**
If you try to generate a nether portal with less than y0, the following message will be displayed.
![image](https://user-images.githubusercontent.com/53502121/123887884-410e3b80-d98d-11eb-8da4-63150273e8ca.png)

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.0.3 SqLite
[10:21:46 INFO]: CMILib: 1.0.2.4
[10:21:46 INFO]: Server: Paper(66) 1.17-R0.1-SNAPSHOT
[10:21:46 INFO]: CMI economy: Enabled CMI Chat: Disabled
[10:21:46 INFO]: Modules -> 55 enabled 1 disabled: votifier

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-66

**Comment by CloudeLecaw** [comment] 2021-06-30 07:16
The -y and higher than 256 is not added you need to wait for the winternupdate.
I know there are some packs that allready allow you to create the bigger world. But you its not recomment to use it allready

**Comment by NamiUni** [comment] 2021-06-30 09:41
I know that expanding the world with datapacks is not recommended, but since it is a bug in CMI, it needs to be fixed.

**Comment by Zrips** [comment] 2021-06-30 09:44
@NamiUni 
First of all, its not a bug in CMI in particular, as you are modifying server in a way its not meant to be modified at this point. Second, I need actual method you used to increase height to reproduce this issue and create a fix for it.

**Comment by NamiUni** [comment] 2021-06-30 09:50
We apologize for the lack of information needed to reproduce the bug. The data pack can be downloaded from here. I don't see this message in vanilla or paper, and I can create a nether portal just fine, but you say it's not a bug?
https://www.minecraft.net/es-es/article/minecraft-snapshot-21w15a

**Comment by mrfloris** [comment] 2021-06-30 10:59
Just a small reminder that the datapacks are an experiment, and not supported by default yet. This is for 1.18. And worlds in 1.17 that are generated with the datapacks will 99% likely not upgrade and have no upgrade path to 1.18 and people should assume they break (unrelated to cmi btw). I hope that's not a live server.

**Comment by Zrips** [comment] 2021-06-30 11:12
With be fixed with next version.

**Closed by Zrips** 2021-06-30 11:12 UTC
Labels: bug report
