### ISSUE TITLE
Instruction /autorecharge exp does not work.

### ISSUE THREAD

**Issue by VIQingNiao** [Zrips/CMI#9242] opened 2024-10-21 05:27 UTC
### Description of Issue

Whether it's Instruction /autorecharge exp or /autorecharge money, it ends up being Instruction /autorecharge money. Instruction /autorecharge exp doesn't work and doesn't report an error... Is this normal? Or is it not set up properly somewhere?

### Version Information

```shell
cmi: 9.7.6.10
CMILib 1.5.1.6
CMIEInjector1.0.2.4

purpur 1.21
zulu java 21
```

### Relevant Config Sections

```yaml
FlightCharge:
  # By default boss bar message will be shown with remaining charges. If disabled then bossbar will only appear when flight charge was modified but not when its depleating while flying
  ShowBossBar: true
  # When set to true, each time player gets flight charge or relogs, his fly mode will be toggled on
  # If set to false, then players will have to manually turn on flight with /cmi flyc
  EnabledByDefault: true
  # When set to true, in event of player changing his game mode from survival/adventure to creative/spectator his flight charge  mode will get disabled
  # Same applies when changing game mode from creative/spectator to survival/adventure
  AutoSwitch: false
  # How much it costs for one recharge point in exp points. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  ExpRechargeCost: 2.0
  # How much it costs for one recharge point. Value can be in decimals, like 0.2 but it cant be equal or lower than 0
  # Set to 0 to disable this type of recharge
  MoneyRechargeCost: 1.0
  # Defines maximum amount of charge player can have
  # One charge is one traveled block while flying
  # if player doesn't move, then one charge for each second while hovering
  MaxChargeLevel: 1000
  # Defines multiplier when player doesn't move but is hovering. For each second player hovers.
  # Set to 0 to disable
  DeductOnIdling: 1.0
  # If this is set above 0, then player will loose defined amount of charges each second they are flying instead of traveled blocks
  # Set to 0 to disable, which will deduct charges for traveled blocks
  DeductOnlyForTime: 0.0
  AutoRecharge:
    # Value in percentage when we should automatically recharge players flight charges if player enabled autorecharge with /autorecharge command
    From: 10.0
    # Value in percentage of charges we need to recharge
    # 25 will result into 25% of max allowed charges being recharged each time auto recharge is triggered
    Amount: 25.0
  # Defines multiplier when player falls down of charge to be taken
  # This only effects when player falls from above 3 blocks of hight
  # In example if player falls from 10 blocks height, then 7 * 2 = 14 charges will be taken
  # This is to prevent avoiding no penalty from jumping from cliffs
  # Set to 0 if you want to disable it
  DeductOnFallMulti: 2
  # Defines if you want to damage player when he falls down from higher than 3 blocks height
  # This will not kill player even if he would drop from 200 block height, but will leave him with 1 hp
  # This will only effect players who jumped down and not those who disabled fly mode in mid air
  DamageOnFall: true
  # DamageOnFall should be enabled for this to work
  # This will define if you want to damage player when he deactivates fly mode in mid air
  DamageOnToggle: false
  # DamageOnFall should be enabled for this to work
  # This will define if you want to kill player if fall damage if higher than his health amount
  KillOnFall: false
  # When color name is defined then at moment player starts flying with flight charges, he will start glowing
  # Set this to 'none' if you want to disable it
  GlowColor: GREEN
Point:
  # Default particle for point command. Options: fireworks_spark, crit, magic_crit, potion_swirl, potion_swirl_transparent, spell, instant_spell, witch_magic, note, portal, flying_glyph, flame, lava_pop, footstep, splash, particle_smoke, explosion_huge, explosion_large, explosion, void_fog, small_smoke, cloud, coloured_dust, dust, snowball_break, waterdrip, lavadrip, snow_shovel, slime, heart, villager_thundercloud, happy_villager, large_smoke, water_bubble, water_wake, suspended, barrier, mob_appearance, end_rod, damage_indicator, sweep_attack, totem, spit, squid_ink, bubble_pop, current_down, bubble_column_up, nautilus, dolphin, water_splash, campfire_signal_smoke, campfire_cosy_smoke, sneeze, composter, flash, falling_lava, landing_lava, falling_water, dripping_honey, falling_honey, landing_honey, falling_nectar, soul_fire_flame, ash, crimson_spore, warped_spore, soul, dripping_obsidian_tear, falling_obsidian_tear, landing_obsidian_tear, reverse_portal, white_ash, light, falling_spore_blossom, spore_blossom_air, small_flame, snowflake, dripping_dripstone_lava, falling_dripstone_lava, dripping_dripstone_water, falling_dripstone_water, glow_squid_ink, glow, wax_on, wax_off, electric_spark, scrape, block_marker, sonic_boom, sculk_soul, sculk_charge_pop, cherry_leaves, small_gust, trial_spawner_detection_ominous, vault_connection, infested, item_cobweb, ominous_spawning, raid_omen, trial_omen, poof, explosion_emitter, firework, bubble, fishing, underwater, enchanted_hit, effect, instant_effect, entity_effect, witch, dripping_water, dripping_lava, mycelium, enchant, item_snowball, item_slime, item, block, rain, elder_guardian, falling_dust, totem_of_undying, dust_color_transition, vibration, sculk_charge, shriek, egg_crack, dust_plume, white_smoke, gust, gust_emitter_large, gust_emitter_small, trial_spawner_detection, dust_pillar, 
  DefaultParticle: DUST
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment] 2024-10-21 13:20
Small bug, will be fixed with next version

**Closed by Zrips** 2024-10-21 13:20 UTC
Labels: bug report

**Comment by VIQingNiao** [comment] 2024-10-21 14:22
When will you add - cmi.command.customrecipe.list access and then the player can command /cmi customrecipe list to view all the lists?
I want the player to be able to view all the custom recipes, but not be able to modify and edit it

**Comment by Zrips** [comment] 2024-10-24 14:04
customrecipe command is made to manage custom recipes and not to show it. Will make few modifications for /recipe command so that when you use -c variable without provided material it would output custom recipes

**Comment by VIQingNiao** [comment] 2024-11-13 01:30
> 小bug，下个版本修复 -----------谷歌翻译----------- 小bug，下个版本修复

Doesn't seem to have fixed the bug completely

Whether it's the command /autorecharge exp or the command /autorecharge money, it's the same message, the operation is completed, and the exp is consumed automatically, but in actual use, it consumes money first, and only consumes exp when it's not enough, so I hope it can be fixed again.

**Comment by VIQingNiao** [comment] 2024-11-13 01:31
> Small bug, will be fixed with next version

Doesn't seem to have fixed the bug completely

Whether it's the command /autorecharge exp or the command /autorecharge money, it's the same message, the operation is completed, and the exp is consumed automatically, but in actual use, it consumes money first, and only consumes exp when it's not enough, so I hope it can be fixed again.

**Comment by Zrips** [comment] 2024-11-13 09:26
Will fix issue with same message being shown, that said, money is prioritized over exp if you have both enabled at same time, we are checking money first and if player has enough of that then we charge with money, if player doesn't have enough then we will charge with exp. Duno about best solution here, maybe separate config option to charge exp before money or charge both semi equally?

**Comment by VIQingNiao** [comment] 2024-11-13 10:25
The first thing to do is to consume the specified consumable correctly, if it's xp then only xp can be consumed, if it's money then only money can be consumed, and only if a certain type of consumable isn't satisfied will another consumable be consumed

**Comment by VIQingNiao** [comment] 2024-11-13 10:25
> Will fix issue with same message being shown, that said, money is prioritized over exp if you have both enabled at same time, we are checking money first and if player has enough of that then we charge with money, if player doesn't have enough then we will charge with exp. Duno about best solution here, maybe separate config option to charge exp before money or charge both semi equally?

The first thing to do is to consume the specified consumable correctly, if it's xp then only xp can be consumed, if it's money then only money can be consumed, and only if a certain type of consumable isn't satisfied will another consumable be consumed

**Comment by VIQingNiao** [comment] 2024-11-13 10:27
Also is it normal that every time a player logs back in, they need to execute the command again to turn on the auto-flight energy?

**Comment by Zrips** [comment] 2024-11-13 11:09
By code currently it would charge money and/or exp if those are enabled as valid charge modes which player can enable or disable, so if you only have exp enabled then only exp will be used to charge, if player doesn't have enough exp then auto recharge will not do anything, same thing with money. There is only that thing where money is being always checked (if its enabled) before exp will be, so in case player has enough money then exp will not be touched.
Flight mode should remain enabled after relog, unless there is another plugin disabling it, then player might need to use /flyc to toggle it back on

**Comment by VIQingNiao** [comment] 2024-11-13 11:15
Inside my server, players are able to recharge with XP and money.

Hopefully you can fix /autorecharge exp and /autorecharge money to be consumed correctly in the next release!

**Comment by VIQingNiao** [comment] 2024-11-13 11:16
CMI is a great plugin for the money, and your team is great!

**Comment by Zrips** [comment] 2024-11-13 11:47
I'm still confused on what is actually incorrect in exp and money consumption here. Exp and money are separate recharge modes, so if only one is enabled then that one will only be used to recharge if there is enough of it to be used for that action. If both modes are enabled then money will be prioritized, if you don't have enough money then exp will be used, if you don't have enough exp then auto recharge will not do anything. So what exactly isn't working for you and how it should work?

**Comment by VIQingNiao** [comment] 2024-11-13 11:57
First, the error in the message, whether it's charging with /autorecharge exp or /autorecharge money it's prompting that it's consuming with xp

Then there's the
When the command /autorecharge exp succeeds, the player is first consumed by money, even if the command /autorecharge money succeeds.
Even if the command /autorecharge money succeeds, the first thing the player gets consumed is money.
There's no difference between these two commands, they both prioritize expending money before xp.

**Comment by VIQingNiao** [comment] 2024-11-13 12:18
[https://vip.123pan.cn/1817011816/12737028](url)Here's a demo animated image, not sure you can see it

First step, I set my economy to only 500
Step 2, no matter if I use the /autorecharge exp or /autorecharge money command, the final message prompted is that I will be depleted of xp value
Step 3, I used the /autorecharge exp command, and set my consumables to xp, but during the flight, I was still consumed 500money first, at this time my money was consumed, and I had no more money left, when I flew again, the flight energy auto-recharge also prompted that I had no money left, and carried out the When I flew again, the flight energy auto recharge also prompted me that I had no money, so I did the xp recharge, and then the auto recharge was all xp recharge.

**Comment by VIQingNiao** [comment] 2024-11-13 12:21
[Here's a demo animated image, not sure you can see it](https://vip.123pan.cn/1817011816/12737028)

First step, I set my economy to only 500
Step 2, no matter if I use the /autorecharge exp or /autorecharge money command, the final message prompted is that I will be depleted of xp value
Step 3, I used the /autorecharge exp command, and set my consumables to xp, but during the flight, I was still consumed 500money first, at this time my money was consumed, and I had no more money left, when I flew again, the flight energy auto-recharge also prompted that I had no money left, and carried out the When I flew again, the flight energy auto recharge also prompted me that I had no money, so I did the xp recharge, and then the auto recharge was all xp recharge.

**Comment by VIQingNiao** [comment] 2024-11-13 12:25
> I'm still confused on what is actually incorrect in exp and money consumption here. Exp and money are separate recharge modes, so if only one is enabled then that one will only be used to recharge if there is enough of it to be used for that action. If both modes are enabled then money will be prioritized, if you don't have enough money then exp will be used, if you don't have enough exp then auto recharge will not do anything. So what exactly isn't working for you and how it should work?

First, the error in the message, whether it's charging with /autorecharge exp or /autorecharge money it's prompting that it's consuming with exp

Then there's this.
When the command /autorecharge exp succeeds, the player is first consumed by money, even if the command /autorecharge money succeeds.
Even if the command /autorecharge money succeeds, the first thing the player gets consumed is money.
There is no difference between these two commands, they both prioritize the consumption of money before exp.

**Comment by VIQingNiao** [comment] 2024-11-30 07:19
I have found a bug, command /weather sun doesn't work, it always rains!

**Comment by Zrips** [comment] 2024-11-30 10:32
If you get feedback about changed weather and it still doesn't change for you, it could be the case that you have personal (pweather) enabled which overrides servers weather state. As of quick check, command does work as intended and does change weather state

**Comment by VIQingNiao** [comment] 2024-12-01 04:22
> /weather sun

I have a world inside my server that rains all the time, I haven't found a specific reason for it so far, and it's happening to all players. I didn't disable the weather change, but when I enter command  /weather sun and command  /weather rain, the message prompted is the same, both show how much time the weather is set to rain.

Of course the weather is still rainy, the weather being rainy should be another bug I'm not sure of, but the prompted message being the same should be a bug that

Translated with DeepL.com (free version)

**Comment by VIQingNiao** [comment] 2024-12-01 04:25
The weather keeps raining bug, I'll find the bug myself by investigating the cause of it
