### ISSUE TITLE
Plugin won't enable on start

### ISSUE THREAD

**Issue by MaxWainer** [Zrips/CMI#5664] opened 2021-06-05 23:07 UTC
**Description of issue:**
Plugin won't enable on start

---

**ERROR:**
Old Version spam:
```
[00:13:03] [Server thread/WARN]: [CMI] Plugin CMI v8.8.4.6 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.onPluginMessageReceived(CMIBungeeCord.java:436) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2760) ~[?:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340) ~[?:1.8.0_292]
	at java.io.DataInputStream.readUTF(DataInputStream.java:589) ~[?:1.8.0_292]
	at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_292]
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.12.2.jar:git-Paper-1618]
	... 14 more
```
New version:
```
[01:03:09] [Server thread/INFO]: [CMI] Enabling CMI v8.8.4.8
[01:03:09] [Server thread/ERROR]: Error occurred while enabling CMI v8.8.4.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/Zrips/CMI/utils/VersionChecker$Version
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1327) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.utils.VersionChecker$Version
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
	... 12 more
[01:03:09] [Server thread/INFO]: [CMI] Disabling CMI v8.8.4.8
```

**Cmi Version (using`/cmi version`): > cmi ver
[01:05:16 WARN]: Unexpected exception while parsing console command "cmi ver"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v8.8.4.8 - plugin is disabled.** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

**Comment by MaxWainer** [comment] 2021-06-06 09:52
Anyone here? This problem is basically crashes my server and we loss online...

**Comment by CloudeLecaw** [comment] 2021-06-08 07:01
have you tried reloading CMI?

[01:03:09] [Server thread/ERROR]: Error occurred while enabling CMI v8.8.4.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/Zrips/CMI/utils/VersionChecker$Version

might the jar is currpted that you used?

Just asking because most of use use 8.8.4.8 and we have no issue with CMIs version checker.

**Comment by MaxWainer** [comment] 2021-06-08 07:28
Already tried everything, nothing help...

**Comment by Zrips** [comment] 2021-06-08 14:24
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.utils.VersionChecker$Version
Would indicate corrupted jar file, this in most cases gets resolved by simply redownloading file. Due to spigot doing some file editing before sending to recipient it might some times corrupt it and introduce issues like that. Its not a issue with plugin itself. 
For first error, will issue fix with next update.

**Closed by Zrips** 2021-06-08 14:24 UTC
Labels: bug report
