### ISSUE TITLE
missing locale for command.commandspy.info.command

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4099] opened 2020-08-28 08:59 UTC
I have this missing locale for command.commandspy.info.command with latest CMI version with enables command spy.

**Comment by Zrips** [comment] 2020-08-28 09:07
Will be fixed with todays update

**Comment by blakedj012** [comment] 2020-08-28 15:39
The error is still happen

**Comment by FestusDM** [comment] 2020-08-28 17:45
Getting the same error on 8.7.6.9 as well.

**Comment by mare-on** [comment] 2020-08-28 18:07
I'm running on 8.7.6.9 as well and everything working fine.

**Comment by Zrips** [comment] 2020-08-28 18:16
@blakedj012 
@FestusDM 
Well that's strange. Everything seams to be in order. I'm guessing you are running DE locale? Did tested with it, well retested, with EN DE ES locales, everything works as intended. Could you provide section of your locale file or maybe even entire file for testing? 
And does this issue only happen for a one command or all of them?

**Comment by Zrips** [comment] 2020-08-28 18:28
Due to previous version issue, some of the locale lines got corrupted, fix for that would be ether remove  particular section of locale file and let it regenerate or delete locale file and allow it to be redownloaded which will resolve this issue. Sorry for inconvenience.

**Closed by Zrips** 2020-08-28 18:28 UTC
Labels: bug report

**Comment by Crazzyguyy** [comment] 2020-08-28 21:54
I deleted it, restarted my server, and still have the problem

**Comment by blakedj012** [comment] 2020-08-29 08:08
Delete the complete Translations Folder and cmi reload. On me it worked.
