### ISSUE TITLE
/tpa tab auto complete stops working on a server restart

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#119] opened 2018-03-12 21:50 UTC
https://github.com/Zrips/CMI/issues/66

Not to be annoying and repost the same issue. I just figured it got lost in the pages once closed. 

On a server restart /tpa does not work with tab auto complete for non OP players. I think it is loading before whatever is conflicting it (I was assuming essentials because we use /nick from essentials but was not able to recreate that as a problem). 

I have noticed that once I /cmi reload after restart it will work just fine for everyone. 

I copied the server fully over to a test server and was not able to recreate it. The only thing the test server does not have is nuVotifier.

**Comment by Zrips** [comment] 2018-03-13 12:54
Strange, after restart, before it or after /cmi reload, tpa tab complete just works as intended. Some interference is definitely there from another plugin. Is this /tpa is cmi command or alias for another plugin?

**Comment by Kbryst** [comment] 2018-03-13 18:30
It’s cmi tpa with the alias in the cmi to just be /tpa. It is both tpa and tpahere.

**Comment by Kbryst** [comment] 2018-03-24 00:10
Another note, we do still have essentials on the server as well

**Comment by Zrips** [comment] 2018-04-08 14:17
Ok, this should be fixed with next build.

**Closed by Zrips** 2018-04-08 14:17 UTC
Labels: bug report
