### ISSUE TITLE
/cmi toggleshiftedit is Not Working - Help Would Be Appreciated

### ISSUE THREAD

**Issue by Kalasky** [Zrips/CMI#908] opened 2018-10-04 08:39 UTC
**Description of issue or feature request:**
Toggle shift edit command does nothing when I try to shift click a sign.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**Cmi Version (using`/cmi version`):** 
8.0.17.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
297

**Comment by LogGits** [comment] 2018-10-04 15:38
Not able to reproduce this on build 8.0.18.0. When toggleshiftedit is enabled are you shift + rightclicking the sign (just to be sure)?

**Comment by Kalasky** [comment] 2018-10-05 07:38
I upgraded CMI to the latest version recently, and yes I am shist + right-clicking the sign.

**Comment by Zrips** [comment] 2018-10-05 09:48
Will be fixed with next build.

**Closed by Zrips** 2018-10-05 09:48 UTC
Labels: bug report, unconfirmed
