### ISSUE TITLE
Console Error With Every Chat Event

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3881] opened 2020-08-04 00:59 UTC
**Description of issue:**
Console error thrown every time someone says something in chat. Yay!

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://gist.github.com/mercurialmusic/2833036a6f804d58d37b1408e9d43e22

---

**Cmi Version (using`/cmi version`):** 8.7.5.2 BungeeCord SqLite

**Server Type (Spigot/Paperspigot/etc):** Paper/Waterfall

**Server Version (using `/ver`):** git-Paper-130 (MC: 1.16.1)/Waterfall-366

**Relevant plugins (Delete if this isn't needed):** VentureChat 2.19.2

**Comment by CloudeLecaw** [comment] 2020-08-04 07:28
Have you tried cmis chat itself? Maybe the problem is with VentureChat? If it is you may could post this issue to the dev of VentureChat

**Comment by Zrips** [comment] 2020-08-04 09:29
Will be fixed with next version.

**Closed by Zrips** 2020-08-04 09:29 UTC
Labels: bug report
