### ISSUE TITLE
[Bug?] /cmi ic on Citizens NPC stops working (chunk unload?)

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1324] opened 2019-01-20 07:17 UTC
Using /cmi ci I have pointed it to a citizens npc that's there and not moving. Every once in a while it disconnects, or stops working. I have to point at it again to make it work. 

I am starting to suspect it's because the data changes when the chunk gets unloaded or something. But I can't get npc to be usable over and over again. I don't know if this is because of a bug in cmi perhaps, or if it's because citizens does stuff to the npc like change the uuid maybe?

Each time i use /cmi ic on an npc and i /citizens save and /save-all, then /stop and start the server back up (1.13.2 and latest cmi/citizens) the entity no longer is linked, i have to go find it again and /cmi ic and click + to point to the right npc

This happened month or so ago too, and during christmas event and now again, i dunno what to do, i get no error etc, but on load it can't find the citizens ncp it seems. not sure how to debug this.

**Comment by mrfloris** [comment] 2019-01-21 19:59
Ok, signs seem to be fine for me so far. 
Just npc so far, using multiverse-core 2.6.0 for 1.13.2 (jenkins build)

**Comment by Zrips** [comment] 2019-01-25 11:52
Will make some changes to check by entities if they are NPC and by their ID's from Citizens plugin itself. As it seems that Citizens changes UUID's whatever its spawns NPC in...

**Comment by xion87** [comment] 2019-01-25 11:54
for me also signs broken...

**Comment by xion87** [comment] 2019-01-25 12:01
i think is more a issue with ic save instead npc

**Comment by xion87** [comment] 2019-01-25 12:15
Just note on my skyblock server there are no npc, i enable the interact command, and created a repair sign, for allow user to create it, randomly, the "repair sign" will disapear from interact command, and you need to do CMI reload for make it work again...

**Comment by mrfloris** [comment] 2019-01-28 09:46
> Could you elaborate on those IC in particular. What type are they? Public? Is it regular sign block only? Does it have more then one block? Do you get any error messages in console?

I do /npc create Jacky --type PLAYER, and then use /cmi ic and click on the thingy to add new block/entity, select entity, and it says look at entity. I then add a command like cmi msg [playerName] &6 hi there, how are you [playerName], and right click the npc, it works.. Test it with a player, works for them too. We then teleport away and play in the same world say 50+ chunks away from it. After some time we come back and right click; and it doesn't work anymore. 

We now have it changed to multiple things, a sign, a chest, and the npc, the chest and the sign keeps working, the npc stops. 

There are no errors in the console. not any during startup of the server either.

**Comment by xion87** [comment] 2019-01-28 10:11
no errrors, same with signs, randomly these ic stop to exist in the storage and need to use /cmi reload for fix them

**Comment by xion87** [comment] 2019-01-28 14:36
this happen in both factions 1.13.2 (worldguard 7 protection) and skyblock world (i use only askyblock plugin as protection plugin)

**Comment by Zrips** [comment] 2019-01-28 14:46
Just clarification, are used /cmi ic command to remove entities/blocks between those instances when you have missing block locations?

**Comment by xion87** [comment] 2019-01-29 23:31
nope

**Comment by 0xC1A551C** [comment] 2019-03-29 06:51
I have this same issues with villagers. I set an IC on all 50 entities (villagers) then about a few days later after some reboots only about half the villagers IC worked. Then I tried to setup IC on a villager that had it removed, logged out, logged back in and the IC was gone. Super irritating issue when this has been a problem for so long.

**Comment by 0xC1A551C** [comment] 2019-03-29 06:54
Pretty much the locations in interactivecommands.yml are MISSING.

**Comment by SeDark** [comment] 2019-05-01 20:35
I have made a sign with public interactive command so that my users can put for example [ic:disposal] but it stops working when the plugin is reloaded or the server restarts.

**Comment by xion87** [comment] 2019-08-12 20:51
i noticed the npc and stuff far from spawn it don't work at 50% when server start. instead all npc and stuff near spawn it work fine

**Comment by LogGits** [comment] 2020-03-10 12:50
Closing, apparently this issue was resolved. If anyone is still experiencing this please let us know how to reproduce.

**Comment by xion87** [comment] 2020-05-25 08:53
The issue is still here saddly

**Comment by mrfloris** [comment] 2020-05-25 11:06
This hasn't been an issue for me when I use the SPAWN area of a world that we load in, i also dont use /npc lookclose.

I test every week if they still work and they're fine. 

I really think it's how the chunks arne't loaded when the server starts, and it 'disconnects'.

**Comment by xion87** [comment] 2020-05-25 11:38
yeah the issue happen if are far from spawn, we have 5 npc to spawn and 1 far from it, the 5° npc was not reacting to click

**Comment by LogGits** [comment] 2020-11-24 11:23
Can you test this on the latest version, iirc, recently another attempt was made at a fix so it could potentially be fixed. Lmk how it goes :)

**Comment by LogGits** [comment] 2020-12-18 15:17
Going to assume this was fixed, if it isn't please open a new ticket.

**Closed by LogGits** 2020-12-18 15:17 UTC
Labels: bug report
