### ISSUE TITLE
No function in 1.13.1 why Versionlocked? All other Plugins work well except CMI, TradeMe and so on....

### ISSUE THREAD

**Issue by Effendil** [Zrips/CMI#780] opened 2018-08-29 01:27 UTC
```
[02:22:12] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_13_R2
[02:22:12] [Server thread/ERROR]: Error occurred while enabling CMI v8.0.7.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:413) ~[spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130) ~[spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:126) ~[spigot.jar:git-Spigot-2440e18-997d378]
	at com.Zrips.CMI.Modules.Afk.AfkManager.tasker(AfkManager.java:134) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager.<init>(AfkManager.java:25) ~[?:?]
	at com.Zrips.CMI.CMI.getAfkManager(CMI.java:770) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1150) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-2440e18-997d378]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [spigot.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [spigot.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-2440e18-997d378]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

Latest Version of CMI

**Comment by CloudeLecaw** [comment] 2018-08-29 06:28
https://github.com/Zrips/CMI/issues/771

**Comment by x1p** [comment] 2018-08-31 09:29
If this CMI version is really version locked, it would be strange.
Everybody could see this version coming for months

**Comment by CloudeLecaw** [comment] 2018-08-31 09:33
ZRips Said the 1.13.1 fix will come today. pls close this isses :)

**Comment by x1p** [comment] 2018-08-31 09:37
IMHO it should be closed when its solved. Until then, it is not solved

**Comment by LogGits** [comment] 2018-09-28 14:12
CMI was never version locked. This is an issue caused by update 1.13_R2 as the cmi that you are using was compiled on 1.13_R1. This should be fixed now and if it isn't please tag me and I will reopen :)

**Closed by LogGits** 2018-09-28 14:12 UTC
