### ISSUE TITLE
Invsee's tab-complete is incorrect

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#4781] opened 2020-12-21 22:07 UTC
**Description of issue:**
When using the /invsee command it shows sub-commands rather then player names.

```
[23:01:29 INFO]: CMI: 8.7.12.1 BungeeCord  MySQL-> 8.7.12.2
[23:01:29 INFO]: Server: Tuinity 1.16.4-R0.1-SNAPSHOT
```

**Comment by Zrips** [comment] 2020-12-22 11:24
This could be caused by another plugin overriding /invsee command tab completes as currently it seams to be working correctly on a clean server. Try testing this without any other plugin. If issue originates from another plugin, then we might need to make some adjustments to counter this issue. Closing ticket for now.

**Closed by Zrips** 2020-12-22 11:24 UTC
Labels: bug report

**Comment by Sikatsu** [comment] 2020-12-22 11:27
Hmm odd. I have no other plugins using the invsee command. Gotta have to see which plugin interfers in that case, as other commands work fine with tab-complete.
