### ISSUE TITLE
Exclusion of players from /whowas

### ISSUE THREAD

**Issue by EthanTheYam** [Zrips/CMI#3820] opened 2020-07-25 00:35 UTC
/whowas is always activating for every player who joins, with no exceptions. However this is also showing for any admin staff who have changed their name in the past to those with perms to /whowas.
---
### Detailed explanation of what it should do, when and in what situation: ###
Moderators and lower staff ranks have access to /whowas for moderation sakes and keeping track of players, however this also means any admin staff who have formerly changed their names, even if they're in vanish, are shown to join to these ranks despite having the permission 'cmi.messages.disablelogin'. Therefore it would be ideal to have /whowas not announce prior names if the player has the permission.
### Basic explanation as to why this feature is needed and/or useful to have: ###
It would allow the admin staff ranks to resume their duties without being disturbed by/exposed to being online to other players, meaning certain duties harder to fulfill.

**Comment by CloudeLecaw** [comment] 2020-07-27 09:48
there is allready a whowas


> cmi whowas [playerName]
>permission: cmi.command.whowas & cmi.command.whowas.others
> Shows players previous names

**Comment by Momshroom** [comment] 2020-07-27 13:17
The issue is that moderators with this permission see admins with Cmi.messages.disablelogin login, when they log in — even when they log in in vanish, because the whowas permission causes them to be announced when they login.   (If they have ever had a different name)
It would be nice if it  didn’t show this message for players who have silent join or at least not for players who log in in vanish (unless the players have perms to see vanished players.  It makes it impossible for staff who have previous name changes to check on mods.

**Comment by CloudeLecaw** [comment] 2020-07-27 14:02
Yes your right about this, maybe this solution dient work in all terms. Havent thought about that someone may not want this staffmembers be able to see this 😂

**Comment by Momshroom** [comment] 2020-07-27 15:36
It would be fine if they saw when the admin first changes their name.  The issue is that if an admin has EVER had a different name, they are announced to all staffmembers every time they log in, even in vanish and to staff that cannot see vanished players.

**Comment by CloudeLecaw** [comment] 2020-07-27 15:54
Hm may Zrips can add something here to avoid this like a bypass that the informer dies. Not get fired when an admin joins in vanish mode. Or may someone sees a better solution?

**Comment by CloudeLecaw** [comment] 2020-07-30 11:54
- CheckForNameChange:
-   OnLogin: false
-   AmountToShow: 3
-   OnInfoShow: true
-   # Do you want to perform commands
-   PerformCommandsOnNewName: false
-   # Command list to be performed in case player logs in with new name
-   NameChangeCommands:
-   - 'asConsole! cmi broadcast !&2[oldname] logged in with new name: [newname]'

What would be needed is a NameChangeCommands bypass
a permission like .**_cmi.performcommandsonnewame.bypass_**

Is this possible to add?

**Comment by Momshroom** [comment] 2020-08-28 20:57
Hi, just letting you know this would still be a very nice feature. Thanks! :)

**Comment by Momshroom** [comment] 2020-12-04 17:16
Just bumping this to let you know we're still interested in this.  Ty!

**Comment by CloudeLecaw** [comment] 2020-12-05 08:33
i think it got lost. 
Its not like in other formuns where renewing with an answer bumbs the theme up.^^
If its lost once (went to muchdown . because of the time) then its lost
what may help is crete a new one, close thisone and link to this one.
Then it really would be "bumping up" so others (also the admins) see it

**Closed** 2020-12-18 15:03 UTC
Labels: feature request
