### ISSUE TITLE
Shift to edit sign not working

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2639] opened 2020-01-12 18:14 UTC
**Description of issue:**

If I use /cmi toggleshiftedit and I shift click the sign nothing seems to happen. I believe this feature doesn't work, or atleast not on 1.15?

**Comment by Sikatsu** [comment] 2020-01-12 18:15
Actually there is an error in the console: https://pastebin.com/44H63a1e

@Zrips

**Comment by Zrips** [comment] 2020-01-13 09:35
Reproduced, will be fixed with next update. Its issue with 1.15 version due to changed API

**Closed by Zrips** 2020-01-13 09:35 UTC
Labels: bug report

**Comment by Sikatsu** [comment] 2020-01-13 09:38
Also, is there any reason this is a toggle-able command and not just a permission?

**Comment by Zrips** [comment] 2020-01-13 09:51
Because you might not want it running always when you building something or trying to place a block in front of a sign while looking at sign. You still have permission which enables it in general for that player, after which you can toggle it on or off

**Comment by Sikatsu** [comment] 2020-01-13 09:53
Makes sense, thanks for your reply!
