### ISSUE TITLE
DiscordSRV and CMI issues

### ISSUE THREAD

**Issue by RisenCloud** [Zrips/CMI#1748] opened 2019-05-13 15:51 UTC
**Description of issue or feature request:**
Hello, I have CMI and discordSRV alongside DeluxeChat just for globalized Discord and MC chat. I have talked to the DiscordSRV people and they said I could try to get you to join the discord for DiscordSRV and you could talk to them in the ticket with me so it is easier for you, me, and them. They won't help me unless I get help from you first because they are indenial about their plugin messing up. They even said they don't believe it was crashing my server due to console channel id being undefined. If you would please help me, it has messed up so many times and I just need help. 
---

**Cmi Version (using`/cmi version`):** 
8.6.1.6
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):** 
DiscordSRV, DeluxeChat

**Comment by Zrips** [comment] 2019-05-13 15:57
Can you elaborate on the issue itself? Any errors? Which part doesn't work and how could i reproduce it?

**Comment by RisenCloud** [comment] 2019-05-13 16:03
I honestly don't know, there are no errors or anything just DiscordSRV is messing up and they wanted to put you in the discord ticket with me to talk to them. I'm at a loss here. We have so much stuff that I don't know what would reproduce it.

**Comment by Zrips** [comment] 2019-05-13 16:04
So can you atleast explain what is the issue itself? What is working and what is not with your setup?

**Comment by mrfloris** [comment] 2019-05-13 16:05
If you want to use DeluxeChat for your Chat handling, you have to turn off CMI chat in config.yml and turn off CMI Discord support. Then DeluxeChat has to handle it.

That's how I assume things work. You can't have 2 plugins handle the same chat. I can imagine that will cause things to collide. 

Does DeluxeChat have DiscorvSRV support?

**Comment by RisenCloud** [comment] 2019-05-13 16:06
well CMI works but DiscordSRV doest. We have used it in this setup for years almost 4 and no issues but now we are having issues. Yes, it supports it. It is what makes it globalized through the entire network.

**Comment by RisenCloud** [comment] 2019-05-13 16:11
That's why we haven't really ever opened up any tickets because we have had no issues with it much ever. Except with the new CMI updates, it messes up aliases where we can't warp or tp so we downgraded back to the latest that worked :P

**Comment by RisenCloud** [comment] 2019-05-13 16:27
I was told it's bungeecords problem with DeluxeChat. It works on all the other servers except this one though which doesn't make sense.

**Comment by 0xC1A551C** [comment] 2019-05-16 23:40
I am having some issues related to cmi and deluxechat. Adding a nick with /cmi nick causes deluxechat to reset its chat format with no errors. maybe try enabling debugging so that you have something more.

**Comment by Vankka** [comment] 2019-11-03 12:23
Duplicate of #391

**Closed** 2020-07-01 15:21 UTC
