### ISSUE TITLE
[List of Bugs] Can Mine Spawners Without Req. Perm, Flightcharge Bugs

### ISSUE THREAD

**Issue by pinkpig3777** [Zrips/CMI#1381] opened 2019-02-03 19:58 UTC
**Description of issue or feature request:**
List of Bugs:
1. Players that should not be able to silk blaze spawners can anyways. 
Permissions given: https://gyazo.com/0ea7662a3261581ab4670b3df1b7346a

2. With Flightcharge expcharge, if a player has the max amount of charges (1000 by default) and tries getting more charges (such as with /recharge expcharge 1000 then it will take exp from their current exp but not give them any additional charges because they are already at max. It should just tell them they have the max number of charges and cannot get anymore.

3. Players can do /flightcharge expcharge 12400 (when they don't have that much & only have 24 lvls or so) and it will take away all of their xp and set it to the 3000 max charge.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://pastebin.com/KnFWNDZD
```

---

**Cmi Version (using`/cmi version`):** https://gyazo.com/7286d42e0c234079d015199598e035ab

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-b0f4c22-d5e9688 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Please Note: Discord is the best way to contact me. PiggiesGoSqueal#5552

**Comment by pinkpig3777** [comment] 2019-02-08 23:22
Another bug related to this: players can do /flightcharge expcharge 12400 and it will take away all of their xp and set it to the 3000 max charge.

**Comment by Zrips** [comment] 2019-02-10 10:47
1. Will be fixed by adding new option to check by specific permission node when needed. This will solve current issue.

**Comment by Zrips** [comment] 2019-02-10 10:53
2. Cant really reproduce this issue currently. Will add some extra fail safes for it tho. Just in case.

**Comment by Zrips** [comment] 2019-02-10 11:00
3. Same thing as 2. Can't reproduce this one. All seems to be working correctly for me. But again, will add extra check for this one too, just in case. And if issue persists with next update. Give me a shout in here or on discord.

**Closed** 2019-02-10 11:01 UTC
