### ISSUE TITLE
Plugin CMI v8.6.7.5 generated an exception while executing task 2039148

### ISSUE THREAD

**Issue by kaniesha** [Zrips/CMI#2094] opened 2019-07-25 00:15 UTC
**Description of issue:**

No noticeable problem in game, found error while scanning logs.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:25:21] [Server thread/INFO]: user issued gui command: /cmi kit
[23:25:26] [Craft Scheduler Thread - 2871/WARN]: [CMI] Plugin CMI v8.6.7.5 generated an exception while executing task 2039148
java.lang.ArithmeticException: / by zero
	at com.Zrips.CMI.Modules.FindBiome.FindBiomeManager$1$1.run(FindBiomeManager.java:105) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-137]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-137]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

**Cmi Version (using`/cmi version`):** 
8.6.7.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper spigot

**Server Version (using `/ver`):** 
git-paper-146

**Comment by Zrips** [comment] 2019-07-31 15:24
Thanks, will be fixed with next build

**Closed by Zrips** 2019-07-31 15:24 UTC
Labels: bug report

**Comment by pc25568** [comment] 2020-06-14 03:28
``Caused by: java.lang.NullPointerException
[23:14:20] [Craft Scheduler Thread - 445/WARN] [/]: Exception in thread "Craft Scheduler Thread - 445" 
[23:14:20] [Craft Scheduler Thread - 445/WARN] [/]: org.apache.commons.lang.UnhandledException: Plugin CMI v8.6.26.9 generated an exception while executing task 2802
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException

[23:14:20] [Craft Scheduler Thread - 446/WARN] [/]: Exception in thread "Craft Scheduler Thread - 446" 
[23:14:20] [Craft Scheduler Thread - 446/WARN] [/]: org.apache.commons.lang.UnhandledException: Plugin CMI v8.6.26.9 generated an exception while executing task 2803
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException

[23:14:20] [Craft Scheduler Thread - 437/WARN] [/]: Exception in thread "Craft Scheduler Thread - 437" 
[23:14:20] [Craft Scheduler Thread - 437/WARN] [/]: org.apache.commons.lang.UnhandledException: Plugin CMI v8.6.26.9 generated an exception while executing task 2795
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException

[23:14:20] [Craft Scheduler Thread - 442/WARN] [/]: Exception in thread "Craft Scheduler Thread - 442" 
[23:14:20] [Craft Scheduler Thread - 442/WARN] [/]: org.apache.commons.lang.UnhandledException: Plugin CMI v8.6.26.9 generated an exception while executing task 2798
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
