### ISSUE TITLE
Chat colors not working on 1.16

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#3610] opened 2020-06-29 21:24 UTC
**Description of issue:**

Beginning with version 8.7.0.0, all of the messages written in the chat go white.
```
'1': '{prefix}{displayName} &8&l» &b{message}'
```
![image](https://user-images.githubusercontent.com/47111280/86057449-dbc8f700-ba67-11ea-9606-910d9e83764c.png)
![image](https://user-images.githubusercontent.com/47111280/86057463-e1bed800-ba67-11ea-9671-a31aa09aa120.png)

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/47111280/86057494-f1d6b780-ba67-11ea-94ba-7504458cf269.png)

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/47111280/86057512-f8652f00-ba67-11ea-9fd1-f7c70df5b523.png)

**Comment by hamcoremusic** [comment] 2020-06-29 21:24
I can confirm this is happening and it might be the reason this is happening: https://github.com/Zrips/CMI/issues/3597

**Comment by Zrips** [comment] 2020-06-30 09:32
Will be fixed with next build

**Closed by Zrips** 2020-06-30 09:32 UTC
Labels: bug report
