### ISSUE TITLE
Server crashed from spammed netty errors with CMI, If I remove CMI I no longer get these errors.

### ISSUE THREAD

**Issue by Impactic48** [Zrips/CMI#6144] opened 2021-09-09 00:20 UTC
**Description of issue:** For the most part whenever someone teleports to /spawn, /home, /tpa, or timeouts with keepalive timeout it causes the following warning below:

io.netty.channel.StacklessClosedChannelException 
at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)

This warning gets spammed on my server between 5-50k times on my server which causes it to force stop itself I assume.
I will provide logs with all my plugins on my server and a log with the relevant plugins that are listed below. I have had this issue since August 1st so I ignored them but it has recently started crashing my server within the past week.

The logs have EventDebugger, Verbose on, and Debug Logging enabled so there's a bunch of spam in the logs from them. But I only installed/enabled them after I started getting these errors so they're not at fault.  I can also post more logs from whenever someone teleports to /spawn, /home, /tpa but I didn't have verbose, debug logging, or EventDebugger installed/enabled during those logs.

Logs with all plugins installed:
https://mclo.gs/jAzOcVR
https://mclo.gs/GOl9wZw
https://mclo.gs/jh2xF5n
https://mclo.gs/jeA9BVt
https://mclo.gs/Bx6YmtO
https://mclo.gs/3whaVL2
https://mclo.gs/FMk7uar

Log below with the following plugins: CMI, CMILib, Luckperms, and Residence
https://mclo.gs/XqvJpLL

Let me know if you need logs with IPs unblocked. All other pastebin sites won't allow me to post my logs with 70-100k lines.

Floris said that "if cmi communicates with another plugin and that goes over netty and there's an issue with that, then this could cause that." He also linked this github ticket: https://github.com/Zrips/CMI/issues/5113 but it has different errors than I do.

**Cmi Config:** https://paste.gg/p/anonymous/aea0b339866847e2b5f78fa79d77774b

**Cmi Version (using`/cmi version`):** v9.0.2.10 (Some logs have CMILib 1.0.3.6 but I updated to 1.0.3.7 and it still happens).

**Server Type (Spigot/Paperspigot/etc):** Paper 1.17.1 Build #250 and I also have the Caves and Cliffs Data pack installed on my server.

**Server Version (using `/ver`):** 1.17.1

**Relevant plugins:** CMI, CMILib, Residence, LuckPerms (Limited to these 4 plugins through deleting plugins until I got down to these 4 and still had errors).

**Comment by Impactic48** [comment] 2021-09-09 01:06
Paper Devs said that every time they've seen this exception it's been down to plugins injecting themselves into the networking logic in a manner that prevents the network connection for a user from actually closing.

**Comment by Zrips** [comment] 2021-09-09 09:34
This might be hard to debug. But some things to note. You have errors from votifier plugin on startup, so you might check that and CMI does have compatibility with Votifier, so if that one fails it might be connected. Buycraft creates another error, but that one should in general not be related to your main issue. In general checking your startup log, you might have issue with Votifier plugin as it does perform connections from outside world and might be responsible for network issues. While CMI could be just triggering something in that plugin which creates this issue. 
If issue is consistent, like you can crash server by performing specific actions, then you might want to simply disable every single plugin except CMI and then check if issue still there, if it is then we will know that issue originates from CMI and not another plugin. Its hard to determine actual cause from your logs and as this is not a bug report we see from others its is caused by something specific in your setup, might be CMI setup or might be combination of other plugins interacting with CMI in weird ways. You will need to perform more testing at your end but simplest would be to figure out how to consistently crash server and then test one plugin at the time.

**Comment by CloudeLecaw** [comment] 2021-09-09 09:45
He is using  1.17.1 . so he should not use Votifier he should switch to [NuVotifier 3.0.0](https://ci.velocitypowered.com/job/NuVotifier/40/)

**Comment by Impactic48** [comment] 2021-09-09 19:28
I don't believe it's Votifier or Buycraft causing those issues but I will look into getting Votifier fixed with the info that CloudeLecaw provided and seeing if there's any way to fix Buycraft in the future. 

I believe this issue doesn't lie with Votifier or Buycraft because the issue still persists when I have just CMI, CMILib, LuckPerms, Residence, and EventDebugger installed. Here's a log with just those 5 plugins installed: https://mclo.gs/XqvJpLL

(I have deleted Residence since this log and added WorldGuard in its place and the issue has happened twice within the last 8 hours so far which force shuts my server down so I have to manually start it each time).

**Comment by CloudeLecaw** [comment] 2021-09-10 05:16
Did u saw the setting in cmi configs related to buycraft?

**Comment by Zrips** [comment] 2021-09-10 09:06
@Impactic48 
Try resetting players skins with /cmi resetdbfields skin
And check if that resolves your issue, if it does then we will know cause of it and i might have better understanding what went wrong

**Comment by Impactic48** [comment] 2021-09-10 12:42
I reset player skins but when I did it, it said “Updated 0 players” “[CMI] Saved all player data”. I reset all my CMI files including player skins a few days ago in case it was an old config file causing the issue but that wasn’t the case either.

**Comment by Impactic48** [comment] 2021-09-10 14:30
Is there any other CMI feature that could be network related?

**Comment by Impactic48** [comment] 2021-09-10 14:44
The issue right now is being triggered by someone with awful internet joining and lagging out due to keep alive time out, when that happens those warnings keep spamming my console. Also is there a way to move homes from CMI to Essentials? I want to test and see if it is CMI that’s the problem and if it is I’ll switch to Essentials until I can figure out the problem with CMI then switch back.

**Comment by Impactic48** [comment] 2021-09-18 05:24
I have had this same exact issue on my creative server (a completely separate server from the initial one) once I installed CMILib and Residence therefore I now believe that the issue lies with CMILib instead of CMI or Residence. Is there any recommendations or changes that you suggest? This issue happened when a player lagged out from high ping. There are 6778 lines of these io.netty errors that all happened within one second after the timeout at 23:53:14 (I just cut out the 6 thousand and some odd lines of errors).

```[23:52:44] [User Authenticator #7/INFO]: UUID of player TheOGwilly is 7e7d3f2c-2d99-4592-a0a8-85499300d292
[23:52:44] [Server thread/DEBUG]: Disabled auto read
[23:52:44] [Netty Epoll Server IO #3/DEBUG]: Enabled auto read
[23:52:44] [Server thread/INFO]: TheOGwilly[/104.181.97.120:54564] logged in with entity id 3080 at ([world]-201.5, 64.0, 175.5)
[23:52:44] [Server thread/INFO]: TheOGwilly joined the game
[23:52:46] [Craft Scheduler Thread - 582 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[23:52:47] [Craft Scheduler Thread - 582 - BuycraftX/INFO]: [BuycraftX] Fetched due players (1 found).
[23:52:47] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[23:52:47] [Netty Epoll Server IO #0/DEBUG]: Enabled auto read
[23:52:57] [Netty Epoll Server IO #1/DEBUG]: Enabled auto read
[23:52:57] [Netty Epoll Server IO #1/DEBUG]: Enabled auto read
[23:52:58] [Netty Epoll Server IO #2/DEBUG]: Enabled auto read
[23:52:58] [Netty Epoll Server IO #2/DEBUG]: Enabled auto read
[23:52:59] [Async Chat Thread - #6/INFO]: [Owner] Impactic ► hey
[23:53:09] [Netty Epoll Server IO #3/DEBUG]: Enabled auto read
[23:53:09] [Netty Epoll Server IO #3/DEBUG]: Enabled auto read
[23:53:14] [Netty Epoll Server IO #3/DEBUG]: Timeout
io.netty.handler.timeout.ReadTimeoutException: null
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Netty Epoll Server IO #3/WARN]: io.netty.channel.StacklessClosedChannelException
[23:53:14] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[23:53:14] [Server thread/INFO]: TheOGwilly lost connection: Disconnected

**Comment by mrfloris** [comment] 2021-09-19 08:25
Paper and Tuinity merged, this could help.
And CMI and CMILib have been moved from 9.0.2.x to 9.0.4.1, so perhaps update these things. 
And double check the other plugins if they could use an update. I don't know their versions, can't check for you.

Those are some crazy errors, if wonder if you keep cmi while this happens, but then remove other plugins that could work with cmi - to see if suddenly these issues stop happening. 

Just removing cmi and the problem going away doesn't automatically mean it's cmi, it just means that a plugin that could potentially cause it can't do it's magic triggering this to happen since they can't use cmi. (just trying to explain it can go both ways).

**Comment by mrfloris** [comment] 2021-09-19 08:28
I did notice this in one of your logs
`Async Chunks: Disabled - Chunks will be managed synchronously, and will cause tremendous lag.`
The word tremendous here could imply why things time out perhaps, especially since modern plugins try to utilize the async features of paper and now have to not-async and require a wait .. causing perhaps these issues?

**Comment by Impactic48** [comment] 2021-09-22 02:58
So I removed CMI, CMILib, and Essentials and it's still happening so it's either paper or my host at this point.

**Comment by Zrips** [comment] 2021-09-28 13:31
@Impactic48 
BuycraftX can be a suspicious one which could be the cause. So investigate that one. As this is not CMI bug will close this ticket.

**Closed by Zrips** 2021-09-28 13:31 UTC
Labels: bug report
