### ISSUE TITLE
Using /cmi effect interacts incorrectly with beacon when adding time to an effect

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#2635] opened 2020-01-12 00:41 UTC
Description of issue:

Using /cmi effect <PLAYER> <EFFECT> +TIME <AMPLIFIER> on a player that already has the same effect from a beacon, adds to beacon timer for the higher level effect, even if command effect is of a lower level.

---

**How to replicate**

1) Have beacon give Haste II, and stand nearby
2) use /cmi effect <PLAYER> fast_digging +300 1
3) Beacon effect is now Haste II with over 5 minutes

This doesn't work if you don't use additive time.

---

**Cmi Version (using`/cmi version`):** 
CMI version 8.6.17.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-33 (MC: 1.15.1)

**Comment by Zrips** [comment] 2020-01-12 12:47
Cant really reproduce this one. Effect stays normal. Did you tested this one with only CMI installed? As this could be caused by another plugin having issues with compatibility. 
CMI recreates effect entirely when you adding time and effect itself is independent from beacon, atleast it should be with normal minecraft version. And when you use effect command only player is being effected. So something is not right with your setup. Test it out with only CMI installed and maybe even with default config file, just to make sure that you dont have some funky custom alias which edits beacon itself.

**Comment by Zrips** [comment] 2020-01-12 12:51
Och, ok, reproduced that one, should be fixed with next update.

**Closed by Zrips** 2020-01-12 12:51 UTC
Labels: bug report, unconfirmed
