### ISSUE TITLE
Armor disappearing if taken off in creative mode

### ISSUE THREAD

**Issue by marvjosh1** [Zrips/CMI#6038] opened 2021-08-16 21:11 UTC
**Description of issue:**

Whenever you try to take off armor in creative mode, instead of it going to the inventory it will delete itself.
Video of this happening: https://youtu.be/29zZYEuPiEA
This also happens with vanilla diamond armor, so it has nothing to do with the custom enchants.

---

**Cmi Version (using`/cmi version`):** 
CMI: 9.0.2.5 BungeeCord MySQL -> 9.0.2.7
CMILib: 1.0.3.4 -> 1.0.3.5

**Server Type (Spigot/Paperspigot/etc):** 
Purpur 1.17.1 Build 1331

**Server Version (using `/ver`):** 
1.17.1

**Comment by Zrips** [comment] 2021-08-25 14:31
It could be due to another plugin interfering. CMI doesn't control such actions in particular and no one else seam to report about this one, so its most likely issue with another plugin and not CMI in particular. Test this without any other plugin and CMI only to make sure that this issue originates from CMI. Closing ticket for now, if its from CMI then let me know, but currently i cant reproduce this and in general it should not be caused by CMI.

**Closed by Zrips** 2021-08-25 14:31 UTC
Labels: bug report
