### ISSUE TITLE
Silentchest option not working in /vanishedit

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#2784] opened 2020-02-10 23:55 UTC
When I turn on the option silent chest in the /vanishedit and do vanish i'm still able to open chest without doing it silently.

**Cmi Version (using`/cmi version`): 8.6.19.1** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): Paper version git-Paper.243 (MC: 1.14.4)**

**Comment by mrfloris** [comment] 2020-02-11 07:22
```
#  
# Handles silent chest opening actions
# Applies for servers from 1.7.x and up
silentChest: true
```
file: `Modules.yml`

Make sure you have the module enabled.

```
cmi.silentchest.editing – Allows to edit chests while in silent open mode

silentchest -> Toggles silent chest
cmi.command.silentchest -> default: op
```

And make sure you have the correct permission. 

Cannot reproduce, I have the permission myself, and I have set myself to vanish. When I go to a chest that's not mine, and right click, it opens silently. 

<img width="484" alt="Screenshot 2020-02-11 at 08 22 04" src="https://user-images.githubusercontent.com/28841349/74217408-97e77800-4ca7-11ea-90be-9f871558b077.png">

**Comment by pvvvo** [comment] 2020-02-11 07:49
I think that I reproduced because I used the /silenchest command
I checked everything that you said, still not working for me.

**Comment by pvvvo** [comment] 2020-02-11 07:57
I just reproduced it, I do /vanish then /silentchest and then I become visible and when I try /vanish again I can not longer open chests silently

**Comment by Zrips** [comment] 2020-02-11 14:40
Will get fixed with next version.

**Closed by Zrips** 2020-02-11 14:40 UTC
Labels: bug report
