### ISSUE TITLE
DiscordSRV broken with ClickHoverMessages enabled

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#391] opened 2018-05-17 11:44 UTC
Description of issue or feature request:

Hello, 
chat from Minecraft to Discord doesn't work when ClickHoverMessages is enabled in the config.yml

Cmi : 7.7.7.0
Server : spigot the latest 1.12.2

**Comment by Zrips** [comment] 2018-05-23 12:21
DiscordSRVSupport enabled?

**Comment by ludvdber** [comment] 2018-05-23 13:02
Yes it's enabled

**Comment by TheWranger** [comment] 2018-07-14 04:43
This one really needs to be fixed.

**Comment by TheWranger** [comment] 2018-07-20 14:56
@Zrips Any news on this?

**Comment by CloudeLecaw** [comment] 2018-10-11 10:39
i also hope it gets fixed.
if ist enabled then we dont see any meassages anymore in discord

**Comment by ludvdber** [comment] 2018-10-11 12:41
It becomes an old issue

**Comment by CloudeLecaw** [comment] 2018-10-16 09:43
jep ist still broken 🥉

**Comment by Sulort** [comment] 2018-10-27 22:08
We also have this issue.
Anybody knows when it will be fixed? is someone still working on it?
Pls fix it. Thanks a lot

**Comment by Chalwk77** [comment] 2018-11-09 11:37
I can confirm this is also broken on my 1.13.2 server.

**Comment by TheWranger** [comment] 2018-12-03 07:48
Would really like to see this fixed as I think the usage of [item] relies on ClickHoverMessages and can't use that without ClickHoverMessages is enabled.

**Comment by ludvdber** [comment] 2018-12-31 12:37
Still waiting since 8 months

**Comment by CloudeLecaw** [comment] 2019-01-07 08:08
Well may this Problem cant be fixed so easiely :3

**Comment by TheWranger** [comment] 2019-01-07 09:03
There still needs to be some status update or communication regarding this issue, if it's a hard issue to fix then @Zrips should tell us so we can at least know what's going on.

**Comment by CypherPhyre** [comment] 2019-01-07 09:31
The problem is not CMI. The problem is that DiscordSRV is not able to process that type is a message. Compatibility needs to be added to DiscordSRV, not to CMI.

**Comment by TheWranger** [comment] 2019-01-07 13:30
I don't think this is an issue on DiscordSRV's behalf, ChatControl has full JSON chat support and has no problems with DiscordSRV.

**Comment by Blueeyestar** [comment] 2019-01-19 11:35
I hope the problem will be solved soon, we have been waiting for a long time that you can click on the names in the chat again and can also use the discord.

**Comment by Blueeyestar** [comment] 2019-03-28 16:24
Will the problem be fixed sometime? would be nice if you have this function again without disabling discord

**Comment by Zrips** [comment] 2019-05-24 08:33
Some changes are coming out with next update

**Comment by CloudeLecaw** [comment] 2019-05-24 11:08
ui this will be interesting :)

**Comment by Blueeyestar** [comment] 2019-05-24 14:01
I'd love that, too. I have been waiting for it for a long time

**Comment by ludvdber** [comment] 2019-05-25 16:19
Discord --> Minecraft works but not Minecraft --> Discord
https://i.imgur.com/e9rlICi.png

My chat config:

  ModifyChatFormat: true
  ClickHoverMessages: true
  DiscordSRVPublicChat: true
  DynMapChat: true

**Comment by Blueeyestar** [comment] 2019-05-25 16:41
Which version or dicord plugin do you use? I have asked 2 other server owners who also have the problem. We take: https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by ludvdber** [comment] 2019-05-25 16:49
The latest dev build from discordsrv, they fixed me an issue yesterday

**Comment by omgitsAngus** [comment] 2019-05-26 14:08
This problem is still not fixed @Zrips. I am using the latest version and it breaks chat from MC to discord and vise versa. It still sends messages like server starts and stops. Removing CMI allows chat again and adding it back breaks it. DiscordSRV enabled aswell as click hover messages.

**Comment by omgitsAngus** [comment] 2019-05-26 14:11
Just kidding, Discord to MC works but not MC to discord.

**Comment by TwinPeaksGaming** [comment] 2019-06-05 05:41
Just leaving this here in case it helps people:

Open DiscordSRV config, change line 23:

RespectChatPlugins: true to RespectChatPlugins: false

Chat will function correctly now.

Temporary fix until author fixes.

**Comment by Blueeyestar** [comment] 2019-06-05 05:47
It actually helped. Super thanks for the note

**Comment by Scarsz** [comment] 2019-06-05 05:48
> Just leaving this here in case it helps people:
> 
> Open DiscordSRV config, change line 23:
> 
> RespectChatPlugins: true to RespectChatPlugins: false
> 
> Chat will function correctly now.
> 
> Temporary fix until author fixes.

We specifically tell people **not** to touch this setting because as the name implies, it breaks things. Any single time someone chats on your server, whether it be as an input for another plugin, staff chat, etc., it will **all** be processed thru DiscordSRV, no matter if a plugin has canceled the chat event. Change that option at your own risk.

**Comment by Blueeyestar** [comment] 2019-06-05 05:51
> 
> 
> > Just leaving this here in case it helps people:
> > Open DiscordSRV config, change line 23:
> > RespectChatPlugins: true to RespectChatPlugins: false
> > Chat will function correctly now.
> > Temporary fix until author fixes.
> 
> We specifically tell people **not** to touch this setting because as the name implies, it breaks things. Any single time someone chats on your server, whether it be as an input for another plugin, staff chat, etc., it will **all** be processed thru DiscordSRV, no matter if a plugin has canceled the chat event. Change that option at your own risk.

Nice of you to tell people that..do you have a better idea to make the function work without this setting?

**Comment by Scarsz** [comment] 2019-06-05 05:57
> Nice of you to tell people that..do you have a better idea to make the function work without this setting?

No. CMI does things that require the chat event to be canceled; legacy pre-JSON chat APIs weren't built with JSON in mind. CMI needs to integrate support for DiscordSRV itself. DiscordSRV can't do it because CMI is a paid plugin and it would need to be publicly available for the build system to work. The only workaround for that is to have a jar file similar to C's header files so that DiscordSRV can use methods in a fake class but... that's far more work than to just implement DiscordSRV into CMI.

**Comment by TwinPeaksGaming** [comment] 2019-06-05 23:26
> > Just leaving this here in case it helps people:
> > Open DiscordSRV config, change line 23:
> > RespectChatPlugins: true to RespectChatPlugins: false
> > Chat will function correctly now.
> > Temporary fix until author fixes.
> 
> We specifically tell people **not** to touch this setting because as the name implies, it breaks things. Any single time someone chats on your server, whether it be as an input for another plugin, staff chat, etc., it will **all** be processed thru DiscordSRV, no matter if a plugin has canceled the chat event. Change that option at your own risk.

Of course, personally we haven't experienced this issue, but our staff chats are in Discord anyways, but other people may experience negative effects from changing it, in fact CMI has been very cooperative since we changed the setting.  Definitely interested to see how it's fixed on yours or DiscordSRV's end.

:)

**Comment by Scarsz** [comment] 2019-06-06 00:38
> Definitely interested to see how it's fixed on yours or DiscordSRV's end.

To be clear, I'm not associated with CMI. I'm the developer of DiscordSRV. I just vaguely know why the plugin does what it does. I don't have access to CMI's source code and I don't really want to use decompiled code to suggest changes.

This issue is something CMI has with all chat plugins... DiscordSRV is just one of them. When you break the conventions of Bukkit's API for dealing with chat, you have to add support for individual plugins that rely on those now broken APIs. That's just how it is.

**Comment by TwinPeaksGaming** [comment] 2019-06-06 02:51
Oh good to know, love you plugin btw, keep up the excellent work.

Thanks for the warning about that config value too, good to know!

**Comment by banit** [comment] 2019-10-23 11:10
still broken

**Comment by Vankka** [comment] 2019-11-03 12:17
This ticket is very old now, doubt Zrips looks onto the last pages of issues very often. If he's working through them by themselves or with a small team: 778 issues (as of posting this) is a lot. 

Disabling `ClickHoverMessages` still fixes the problem, if you don't mind disabling it of course.

The only way I see this getting fixed if multiple people send messages to Zrips about it, to get his attention

**Comment by Aureliiienn** [comment] 2019-11-14 19:49
Up

**Comment by Blueeyestar** [comment] 2020-01-13 16:52
too bad that the great function can not be fixed ...

**Comment by LogGits** [comment] 2020-01-15 13:39
Hey, i want to get this fixed asap but we are having issues reproducing it. Can someone please post a step by step way to reproduce this. Lets get this fixed together 🙂

**Comment by CloudeLecaw** [comment] 2020-01-15 15:03
Well if i understand it correclty then:
1. you conect your Disocord with your server vira the DiscordSRV plugin
2. in CMi you have the option enabled: ClickHoverMessages
3. the CMI chat is used
-> in discord you dont see ppl write any measages

was that correct? :3

**Comment by Blueeyestar** [comment] 2020-01-15 16:35
if you have clickHoverMessages in CMI, you can no longer read what is written on the server in Discord Chat. Only when you turn off ClickHoverMessages in CMI can you read what is written in the game again in Discord

**Comment by banit** [comment] 2020-01-15 17:24
https://i.vgy.me/2Oo1A3.png On Server double posted messages, in discord normal chat no messages, in console log (discord and normal log) everything is fine.



Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'


CMI 8.6.17.4
1.15.1 Paper 46

**Comment by LogGits** [comment] 2020-01-16 19:13
So in build `8.6.17.4` this isn't resolved? Can someone confirm what @banit is saying so we can be sure. From what i understand, previously it wasn't sending the message to discord when `ClickHoverMessages: true` was set. However, in builds `8.6.17.4+` it now works but sends duplicate messages instead of sending a single message?

Can someone please confirm just to be sure. We should be close to resolving this long standing issue.

**Comment by Blueeyestar** [comment] 2020-01-16 20:47
It still doesn't work in 8.6.18.0 either

**Comment by Relaxing9** [comment] 2020-01-16 20:59
> So in build 8.6.17.4 this isn't resolved? Can someone confirm what @banit is saying so we can be sure. From what i understand, previously it wasn't sending the message to discord when ClickHoverMessages: true was set. However, in builds 8.6.17.4+ it now works but sends duplicate messages instead of sending a single message?
> Can someone please confirm just to be sure. We should be close to resolving this long standing issue.

I tried setting ClickHoverMessages: true, however for me it still doesn't send any messages at all, so for now I ended up disabling it. Using 8.6.17.4.

**Comment by Vankka** [comment] 2020-01-16 21:12
@LogGits The problem is that CMI cancels chat messages whenever `ClickHoverMessages` is enabled, thus causing DiscordSRV to not pick them up; ideal solution would be to clear recipients instead. (Also make sure `RespectChatPlugins` is `true` in the DiscordSRV config.)

~ DiscordSRV developer

**Comment by Zrips** [comment] 2020-03-10 11:39
One more update is coming out for this one. Changed some base mechanics in how we are handling discord messages coming in and going out. Hopefully, this will resolve it.

**Closed by Zrips** 2020-03-10 11:39 UTC
Labels: bug report

**Comment by Blueeyestar** [comment] 2020-03-10 17:05
It finally works. I'm really happy about it. Great work
