### ISSUE TITLE
Internal CMI command message /c

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5550] opened 2021-05-08 09:38 UTC
**Description of issue:**
Whenever a player executes `/c` an internal message appears:
![Screenshot-2021-05-08 112638](https://user-images.githubusercontent.com/28690790/117534337-3ec4dc00-aff1-11eb-96b4-89ba457b15d0.png)
This interferes with other plugins which do need the `/c` command.
The other plugin responds well but the CMI message cannot be prevented

---

---

**Cmi Version (using`/cmi version`):** 
8.8.3.10
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5

**Comment by CloudeLecaw** [comment] 2021-05-08 16:56
Just one letter for a command? Hmm you may can use customalaias.yml to force to use /c to the real comands. You can be shure that /c ist just an alais. If not use plugin:c in the custom alias.
After that cmi should lead to your plugin with out responding.

**Comment by x1p** [comment] 2021-05-08 17:04
I discovered this on the server where there is an alias for /c to something.
Then I tried on other servers too. It happens there too.

So: This bug happens on all servers, even when there is no actual command with /c.

I'm surprised cmi uses such simple command to execute an internal thing. Normally plugins use something more complicated/hard to guess command for internal things.

**Comment by CloudeLecaw** [comment] 2021-05-08 17:17
Coudl you try /cci /cc/sc and /sc?
May there is a problem with the Interpretation of ctextnvariables
Like `<C>someplayercoamd</C>`

**Comment by x1p** [comment] 2021-05-08 17:29
None of these `/cci, /cc, /sc, /si` do anything on my test server

**Comment by CloudeLecaw** [comment] 2021-05-08 17:34
ok..so it just effects the /c.. thats strange but i can simply reproduce it :§
Also there is no feedback from the console
![Snag_2342e5b](https://user-images.githubusercontent.com/12080017/117548274-596c7480-b034-11eb-9c96-60c002d9aafd.png)

**Comment by x1p** [comment] 2021-05-08 17:44
Exactly. I tried to find out what module/config could be involved. Tried a few things but haven't figured it out yet.
The latest change log didn't provide me any clues either.

**Comment by CloudeLecaw** [comment] 2021-05-08 17:59
like i said `<C>command</C>` is used normaly for ctext interpreation it should not be there as command for /c
CMI sees that. thats the reason for the meassage but been a command it definalty a bug.

**Comment by Zrips** [comment] 2021-05-10 11:30
Will be resolved with next build

**Closed by Zrips** 2021-05-10 11:30 UTC
Labels: bug report
