### ISSUE TITLE
Taking out an item out of the offhand of an offline player with /cmi inv duplicates the item.

### ISSUE THREAD

**Issue by Markusi13** [Zrips/CMI#3897] opened 2020-08-06 19:37 UTC
**Description of issue:**
When you open up the inventory of an offline player using the command /oi and you take an item out of their offhand into your own inventory, it duplicates that item. You'll have a duplicate of that item in your own inventory but when you open up the players inventory again, the item is back in his offhand.

**Edit: We redirected /cmi inv to /oi, meaning that that bug also still happens when you use /cmi inv (obiously)

---

**Cmi Version (using`/cmi version`):** 8.7.5.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.12.2

**Comment by CloudeLecaw** [comment] 2020-08-07 07:36
Why not using /cmi inv (playername)?

**Comment by variananora** [comment] 2020-08-07 08:10
./oi is from OpenInv, not CMI.

**Comment by CloudeLecaw** [comment] 2020-08-07 09:30
Year thats what i thought too he postet an ither comand from other plugin and declaers the wring behave of this command as cmi issue..

**Comment by Markusi13** [comment] 2020-08-07 09:59
I forgot to add that we redirected /cmi inv to /oi, so /oi is /cmi inv. Just for your sake i also tried it with the /cmi inv command but the same bug still appears. But thanks for the sassy smartass comment, really added on to the conversation :)

**Comment by FrozenBeard** [comment] 2020-08-07 10:36
It is `/cmi inv <playername>` we are using that, I have just setup a alias for /oi as this is the most common, most used shortcut, no idea why its not in the defaults for CMI. The bug is with CMI forget that we use `/oi` as an Alias, its not the point.

**Comment by CloudeLecaw** [comment] 2020-08-07 11:01
because /oi is not so cummon as you may thought^^

what you descript usually just can happen by wrong setup and that is a fact ;)
i tested the last version together with last paper a few moments ago, the takeoff of offhand worked fine there without any duplication (means u get a copy instead of the original)

but i renember this but from dome older versions. but i assume your using the latest versions of 1.16.1 and also cmi, and its a long time back in 1.15.2 when this issues accoured, so i dont renember anymore what was casuing it :3

**Comment by FrozenBeard** [comment] 2020-08-07 11:41
>  last version together with last paper a few moments ago

>  but i assume your using the latest versions of 1.16.1

**READ** the initial ticket. Scroll up and read the Server Version in the very first ticket.

**Comment by CloudeLecaw** [comment] 2020-08-07 12:52
Hm 12years here, seems your fresh to cmi ;) *joking* na year ment nothing. Open inv may is older but still not common today anymore. Today pepol use inv and end without open but thats out if thread. Finaly the question is what you have made wrong? I would try creating  a freah new testserver just cmi and your permission Systems and test aggain. Looks like you made changes or a 3rd plugin that is creating this issues. With your 7 years expierience i dont need to tell you that every plugin no matter what it does can create issues liie this. So you need to sort out step by step until you can reproduce this.

**Comment by FrozenBeard** [comment] 2020-08-07 13:28
> Hm 12years here, seems your fresh to cmi ;) _joking_ na year ment nothing. Open inv may is older but still not common today anymore. Today pepol use inv and end without open but thats out of thread. Finaly the question is what you have made wrong? I would try creating a freah new testserver just cmi and your permission Systems and test aggain. Looks like you made changes or a 3rd plugin that is creating this issues. With your 7 years expierience i dont need to tell you that every plugin no matter what it does can create issues like this. So you need to sort out step by step until you can reproduce this. Also make sure u dont interact oped, just use your permission ranks.
> Would be interesting what you got for results.

LOL, you are not even the dev, and getting angry on a bug report, calm down son! Why are you so butthurt about us saying that `/oi` stands for **O**pen **I**nventory , im going to make a feature request for this to be added to the alias just to spite you being retarded.

**Comment by Zrips** [comment] 2020-08-07 13:57
Confirmed, will get fixed with next version.

**Closed by Zrips** 2020-08-07 13:57 UTC
Labels: bug report

**Comment by CloudeLecaw** [comment] 2020-08-08 13:32
for your wish of /oe ad /oe you already found a aceptable solution with a customalais.
its not needed to be added for alias.yml :)
