### ISSUE TITLE
CMI breaks plugin loading MMO/Mythiclib/MMOItems etc.

### ISSUE THREAD

**Issue by SteelsSystem** [Zrips/CMI#8122] opened 2023-09-13 14:36 UTC
### Description of Issue

https://mclo.gs/v5dYOcS

when cmi tries to hook into mythiclib it goes nutz and doesn't load the needed plugins

it is specific after update CMI v9.6.2.7
i downgraded to v 9.6.2.5 and the issue was fixed.

### Version Information

```shell
[16:35:05 INFO]: [MythicLib] > ParadiseLand BETA-1.3.0 by gamerover98
[16:35:05 INFO]: [MythicLib] > PlaceholderAPI 2.11.3 by HelpChat
[16:35:05 INFO]: [MythicLib] > BotSentry 9.5.3-THANATOS by New Era Studios,Lahuca Software Development
[16:35:05 INFO]: [MythicLib] > PvPToggle 1.7 by aasmus (with modifications by the Red Fusion Team)
[16:35:05 INFO]: [MythicLib] > ModelEngineMerger 2.0.0 by Lighty
[16:35:05 INFO]: [MythicLib] > ChatInDiscord 1.0.5 by Jqstln,Delphind
[16:35:05 INFO]: [MythicLib] > NBTAPI 2.11.3 by tr7zw
[16:35:05 INFO]: [MythicLib] > LogFilter 3.0.6 by 4drian3d
[16:35:05 INFO]: [MythicLib] > Terra 6.3.1-BETA+73baaec6c by dfsek
[16:35:05 INFO]: [MythicLib] > MiniMOTD 2.0.13 by jmp
[16:35:05 INFO]: [MythicLib] > LuckPerms 5.4.40 by Luck
[16:35:05 INFO]: [MythicLib] > CMILib 1.4.1.0 by Zrips
[16:35:05 INFO]: [MythicLib] > spark 1.10.53 by Luck
[16:35:05 INFO]: [MythicLib] > LoneLibs 1.0.25 by LoneDev,others
[16:35:05 INFO]: [MythicLib] > ProtocolLib 5.0.0 by dmulloy2,comphenix
[16:35:05 INFO]: [MythicLib] > LibsDisguises 10.0.37 by libraryaddict,Byteflux,Navid K.
[16:35:05 INFO]: [MythicLib] > TAB 4.0.3 by NEZNAMY
[16:35:05 INFO]: [MythicLib] > Vault 1.7.3-b131 by cereal,Sleaker,mung3r
[16:35:05 INFO]: [MythicLib] > CommandPrompter 2.1.1 by CyR1en
[16:35:05 INFO]: [MythicLib] > NexEngine 2.2.10 build-15/06/2023 by NightExpress
[16:35:05 INFO]: [MythicLib] > DecentHolograms 2.8.3 by d0by
[16:35:05 INFO]: [MythicLib] > FastAsyncWorldEdit 2.7.2-SNAPSHOT-557;2f309ff by Empire92,MattBDev,IronApollo,dordsor21,NotMyFault
[16:35:05 INFO]: [MythicLib] > ExcellentCrates 4.3.3 by NightExpress
[16:35:05 INFO]: [MythicLib] > AlonsoTags 2.0.7-BETA by AlonsoAliaga
[16:35:05 INFO]: [MythicLib] > ajLeaderboards 2.7.0 by ajgeiss0702
[16:35:05 INFO]: [MythicLib] > PluralKitMC 0.4.16 by Allymonies
[16:35:05 INFO]: [MythicLib] > BKCommonLib 1.20.1-v2 by bergerkiller,lenis0012,timstans,bubba1234119,KamikazePlatypus,mg_1999,Friwi
[16:35:05 INFO]: [MythicLib] > ExcellentEnchants 3.4.3 by NightExpress
[16:35:05 INFO]: [MythicLib] > PlayerPoints 3.2.6 by Esophose,Black_ixx
[16:35:05 INFO]: [MythicLib] > WorldGuard 7.0.9-beta1+2249-223b80c by 
[16:35:05 INFO]: [MythicLib] > MythicMobs 5.3.5-64893d49 by Lumine
[16:35:05 INFO]: [MythicLib] > My_Worlds 1.20.1-v2 by KamikazePlatypus,mg_1999,Friwi,bergerkiller,lenis0012,timstans,bubba1234119
[16:35:05 INFO]: [MythicLib] > CoreProtect 22.0 by Intelli
[16:35:05 INFO]: [MythicLib] > Jobs 5.2.1.0 by Zrips
[16:35:05 INFO]: [MythicLib] > MythicCrucible 1.6.0 by Ashijin
[16:35:05 INFO]: [MythicLib] > PlayerAuctions 1.24.0 by Olzie
[16:35:05 INFO]: [MythicLib] > Codex 1.13.1 by Ajneb97
[16:35:05 INFO]: [MythicLib] > mcMMO 2.1.223 by nossr50,GJ,NuclearW,bm01,Glitchfinder,TfT_02,t00thpick1,Riking,electronicboy,kashike
[16:35:05 INFO]: [MythicLib] > AureliumSkills Beta 1.3.21 by Archyx
[16:35:05 INFO]: [MythicLib] > JobPicker 0.1 by 
[16:35:05 INFO]: [MythicLib] > MythicLib 1.6.1 by Indyuce
[16:35:05 INFO]: [MythicLib] > BetterProfiles 1.5-BETA by AlonsoAliaga
[16:35:05 INFO]: [MythicLib] > CMI 9.6.2.5 by Zrips
[16:35:05 INFO]: [MythicLib] > CMIEInjector 1.0.2.3 by Zrips
[16:35:05 INFO]: [MythicLib] > MMOItems 6.9.4 by Indyuce
[16:35:05 INFO]: [MythicLib] > Citizens 2.0.32-SNAPSHOT (build 3156) by fullwall
[16:35:05 INFO]: [MythicLib] > CharacterDialogue 0.8 by iAtog
[16:35:05 INFO]: [MythicLib] > ItemJoin 6.0.1-RELEASE-b892 by RockinChaos
[16:35:05 INFO]: [MythicLib] > ModelEngine R3.1.8 by Ticxo
[16:35:05 INFO]: [MythicLib] > RPGInventory 1.8.1-SNAPSHOT by Indyuce
[16:35:05 INFO]: [MythicLib] > MIReplacer 3.0 by Aria Sangarin
[16:35:05 INFO]: [MythicLib] > Procedural 1.5.0 by Denizen
[16:35:05 INFO]: [MythicLib] > MythicDungeons 1.1.1F by MarcatoSound
[16:35:05 INFO]: [MythicLib] > LM_Items 1.2.11 by stumper66
[16:35:05 INFO]: [MythicLib] > ItemsAdder 3.5.0c-r4b by LoneDev
[16:35:05 INFO]: [MythicLib] > ItemsAdder-WorldEdit 1.1.3 by 
[16:35:05 INFO]: [MythicLib] > MythicMobsGUI 1.6.5 by Ender_Griefeur99
[16:35:05 INFO]: [MythicLib] > EvenMoreFish 1.6.11.3 by Oheers
[16:35:05 INFO]: [MythicLib] > DeluxeMenus 1.13.7-Release by extended_clip,Glare
[16:35:05 INFO]: [MythicLib] > SCore 4.23.9.8 by Ssomar
[16:35:05 INFO]: [MythicLib] > LevelledMobs 3.12.0 b777 by lokka30,PenalBuffalo,UltimaOath
[16:35:05 INFO]: [MythicLib] > ExecutableItems 6.23.9.8 by Ssomar
[16:35:05 INFO]: [MythicLib] > ExecutableBlocks 4.23.9.8 by Ssomar
[16:35:05 INFO]: [MythicLib] > ShopGUIPlus 1.90.1 by brc
[16:35:05 INFO]: [MythicLib] > Interface4 4.6 by OLLIEZ4
[16:35:05 INFO]: [MythicLib] > Space 2.11.4 by OLLIEZ4
[16:35:05 INFO]: [MythicLib] > SelectionVisualizer 3.2.2.0 by Zrips
[16:35:05 INFO]: [MythicLib] > TradeMe 6.2.0.4 by Zrips
[16:35:05 INFO]: [MythicLib] > GriefPrevention 16.18 by 
[16:35:05 INFO]: [MythicLib] > GPFlags 5.12.8 by Big_Scary,ShaneBee,DmitryRendov,DrBot
[16:35:05 INFO]: [MythicLib] > GPExtension 1.8.5 by 
[16:35:05 INFO]: [MythicLib] > DungeonParties 1.0-SNAPSHOT by MarcatoSound
[16:35:05 INFO]: Plugin versions pasted to your server console
```

### Errors

```shell
[03:06:41] [Server thread/INFO]: [MythicLib] Enabling MythicLib v1.6.1
[03:06:41] [Server thread/WARN]: [MythicLib] You may be using an outdated config.yml!
[03:06:41] [Server thread/WARN]: [MythicLib] (Your config version: '4' | Expected config version: '5')
[03:06:41] [Server thread/INFO]: [MythicLib] Hooked onto DecentHolograms
[03:06:41] [Server thread/INFO]: [MythicLib] Hooked onto CMI
[03:06:41] [Server thread/ERROR]: Error occurred while enabling MythicLib v1.6.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class io.lumine.mythic.bukkit.events.MythicMechanicLoadEvent while not enabled
	at io.papermc.paper.plugin.manager.PaperEventManager.registerEvent(PaperEventManager.java:95) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvent(PaperPluginManagerImpl.java:141) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:708) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.register(EventListener.java:77) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.events.functional.single.SingleHandlerListImpl.register(SingleHandlerListImpl.java:62) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.events.functional.single.SingleHandlerListImpl.register(SingleHandlerListImpl.java:38) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.events.functional.single.SingleSubscriptionBuilder.handler(SingleSubscriptionBuilder.java:155) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.lib.comp.mythicmobs.MythicLibSupportImpl.load(MythicLibSupportImpl.java:43) ~[MythicLib-1.6.1.jar:?]
	at io.lumine.mythic.lib.comp.mythicmobs.MythicLibSupportImpl.load(MythicLibSupportImpl.java:35) ~[MythicLib-1.6.1.jar:?]
	at io.lumine.mythic.bukkit.utils.plugin.PluginModule.setup(PluginModule.java:34) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.terminable.TerminableConsumer.bindModule(TerminableConsumer.java:31) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.plugin.LuminePlugin.bindModule(LuminePlugin.java:125) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.terminable.TerminableModule.bindModuleWith(TerminableModule.java:24) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.plugin.PluginModule.doBinding(PluginModule.java:27) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.plugin.PluginModule.<init>(PluginModule.java:23) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.bukkit.utils.plugin.ReloadableModule.<init>(ReloadableModule.java:8) ~[MythicMobs-5.3.5 (1).jar:?]
	at io.lumine.mythic.lib.comp.mythicmobs.MythicLibSupportImpl.<init>(MythicLibSupportImpl.java:37) ~[MythicLib-1.6.1.jar:?]
	at io.lumine.mythic.lib.comp.mythicmobs.MythicMobsHook.<init>(MythicMobsHook.java:19) ~[MythicLib-1.6.1.jar:?]
	at io.lumine.mythic.lib.MythicLib.onEnable(MythicLib.java:164) ~[MythicLib-1.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:06:41] [Server thread/INFO]: [MythicLib] Disabling MythicLib v1.6.1
[03:06:41] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling MythicLib v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.lib.glow.GlowModule.disable()" because "this.glowModule" is null
	at io.lumine.mythic.lib.MythicLib.onDisable(MythicLib.java:284) ~[MythicLib-1.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2053]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:06:41] [Server thread/INFO]: [CMI] Enabling CMI v9.6.2.7
```

### Relevant Config Sections

```yaml
we're using tweaked version of hyronic survival with CMI enabled
```

### Relevant Plugins

Mythiclib

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by SteelsSystem** [comment] 2023-09-13 14:38
hyronic-survival-setup: https://builtbybit.com/resources/hyronic-survival-setup.25352/

**Comment by mrfloris** [comment] 2023-09-13 17:38
Thank you for following up with this, super annoying - a temp fix is to start the server with the flag to still allow things to load the legacy way and not the paper way. But let's find out what's the cause this time.

**Comment by SteelsSystem** [comment] 2023-09-13 18:06
![image](https://github.com/Zrips/CMI/assets/92061582/60b9b18b-8954-4713-9c61-c35cceed2dc7)

**Comment by Zrips** [comment] 2023-09-15 09:06
@SteelsSystem 
Tested out MythicLib with latest CMI, no errors on startup. And your error log doesn't mention CMI at all and CMI doesn't have any hooks with Mythic plugins, so this entire issue is from MythicLib side and I can't even reproduce to make a fix from my end. You might want to get into contact with MythicLib developer to have a look into this issue and double check what, where and why it failed to load. 
Closing ticket as it looks to be issue with MythicLib.

**Closed by Zrips** 2023-09-15 09:06 UTC
Labels: bug report
