### ISSUE TITLE
Players can't see own sent private Message

### ISSUE THREAD

**Issue by PanetiX** [Zrips/CMI#7056] opened 2022-07-12 06:53 UTC
### Description of Issue

If players send a private message to some other player on a other subserver, he will get the message but the player who sent the message will not see the own sent message.

### Version Information

```shell
CMI Plugin Version: 9.2.1.1
CMI Lib: 1.2.1.1
CMIB: 1.0.1.0
```

### Errors

```shell
No error in console or log.
```

### Relevant Config Sections

```yaml
BungeeMessages: true
  BungeePublicMessages: true
  BungeeStaffMessages: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment] 2022-07-21 10:32
Should be resolved with next update. If issue persists, let me know as its not guaranteed to be fixed due to this issue not being consistent or easily reproducible, but found some potential cause which got addressed.

**Closed by Zrips** 2022-07-21 10:32 UTC
Labels: bug report
