### ISSUE TITLE
Unhandled exception when creating chatroom

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3454] opened 2020-06-04 15:45 UTC
**Description of issue:**
Happens when creating a room, leaving, creating again
- /chat create vis
- /chat leave
- /chat create vis
- error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:36:35 INFO]: Player123 issued server command: /chat create vis
[17:36:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.26.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Purpur-585]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.15.2.jar:git-Purpur-585]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1887) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1695) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1114) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1248) ~[patched_1.15.2.jar:git-Purpur-585]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:979) ~[patched_1.15.2.jar:git-Purpur-585]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.commands.list.chat.perform(chat.java:120) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:319) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Purpur-585]
... 17 more
```

---

**Cmi Version (using`/cmi version`):** 
[17:40:36 INFO]: CMI: 8.6.26.9 MySQL
[17:40:36 INFO]: Server: Purpur 1.15.2-R0.1-SNAPSHOT
[17:40:36 INFO]: CMI economy: Yes Vault: 1.7.3-b CMI Chat: Yes
[17:40:36 INFO]: Modules -> 28 enabled 23 disabled: cuffed, mirror, tablist, armorstand, versionCheck, moneyCheque, portals, holograms, noTarget, elytraBoost, dynamicSigns, eventCommands, playerChatTag, coloredArmor, flightCharge, schedule, disabledEnchants, ranks, selection, attachedCommands, spawnerCharge, warmup, namePlates
**Server Type (Spigot/Paperspigot/etc):** 
Paper (fork)
**Server Version (using `/ver`):** 
1.15.2

**Comment by CloudeLecaw** [comment] 2020-06-05 04:06
Wow...
I cant reproduce this. I created, lefr, join same channel 4times now.

Maybe Zrips sees what going wrong on your server... 

Cmi: 8.6.29.9 
Paperspigot:1.15.2 build 333

**Comment by Zrips** [comment] 2020-06-18 14:39
Should be fixed with latest builds

**Closed by Zrips** 2020-06-18 14:39 UTC
Labels: bug report
