### ISSUE TITLE
Please reopen ticket 1493.  Color codes still fill and ruin books

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#2336] opened 2019-09-08 05:24 UTC
**Description of issue:**
Issue from ticket #1493  is NOT fixed as of 8.6.12.1.  Every time you hit done on a book, every return character gets an additional &0.  Books become unusable.

https://prnt.sc/p2y28p

---

**Cmi Version (using`/cmi version`):** 
8.6.12.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2 (Paper 641)

**Comment by LogGits** [comment] 2019-09-15 15:17
Duplicate of #1493

**Closed by LogGits** 2019-09-15 15:17 UTC
Labels: bug report
