### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8899] opened 2024-07-05 07:27 UTC
### Description of Issue

I discovered a bug when starting the server

### Version Information

```shell
CMI Plugin Version: 9.7.4.3
CMILib: 1.5.0.5
Server: Paper(2256) 1.21-RO.1-SNAPSHOT
```

### Errors

```shell
[07:23:32] [Server thread/INFO]: Enabling BungeeCord Support
[07:23:32] [Server thread/INFO]: Loaded (1) kits into memory. Took 1ms
[07:23:32] [Server thread/INFO]: Loaded (7) ranks into memory. Took 10ms
[07:23:32] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "<parameter1>" is null
[07:23:32] [Server thread/WARN]: 	at CMI-9.7.4.3.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1190)
[07:23:32] [Server thread/WARN]: 	at CMI-9.7.4.3.jar//com.Zrips.CMI.utils.Util.fixItemStackFile(Util.java:1216)
[07:23:32] [Server thread/WARN]: 	at CMI-9.7.4.3.jar//com.Zrips.CMI.Modules.SavedItems.SavedItemManager.load(SavedItemManager.java:133)
[07:23:32] [Server thread/WARN]: 	at CMI-9.7.4.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1541)
[07:23:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[07:23:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[07:23:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[07:23:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[07:23:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[07:23:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[07:23:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755)
[07:23:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517)
[07:23:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361)
[07:23:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
[07:23:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[07:23:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[07:23:32] [Server thread/INFO]: Loaded (8) playtime rewards into memory. Took 2ms
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by NoltoxGit** [comment] 2024-07-05 07:42
Duplicate of my previous issue #8897

**Comment by Zrips** [comment] 2024-07-05 17:47
New version is out to address this small issue

**Closed by Zrips** 2024-07-05 17:47 UTC
Labels: bug report
