### ISSUE TITLE
CMI Vanish Error

### ISSUE THREAD

**Issue by Relaxing9** [Zrips/CMI#4202] opened 2020-09-13 19:15 UTC
**Description of issue:**
CMI Vanish Error when a vanished player joins

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[https://pastebin.com/B6XhGqp9](https://pastebin.com/B6XhGqp9)

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.7.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  git-Spigot-2740d5a-d5a7296 (MC: 1.16.3)

**Comment by Zrips** [comment] 2020-09-16 14:03
Error isint really caused by CMI but by DynMap, will check what i can do from my end, but in general this needs to be fixed by DynMap dev

**Closed by Zrips** 2020-09-16 14:03 UTC
Labels: bug report

**Comment by Relaxing9** [comment] 2020-09-16 14:19
Yeah I removed Dynmap from my server until its updated to 1.16.3 and I don't see that error anymore, but thanks for trying to mitigate the issue.
