### ISSUE TITLE
Dupe Bug with Ender Chest

### ISSUE THREAD

**Issue by HahaSoStupid** [Zrips/CMI#5569] opened 2021-05-11 13:30 UTC
**Description of issue:**
This apparently only affects some players and not all of them had this game breaking bug on their account. 
Whenever the affected account took out something from their ender chest, specifically from the 3rd row, the item will appear again, causing the dupe to happen.

The bug was found to be on 8.8.3.10, and we had to revert back to 8.8.1.0 temporarily as that version doesn't have this bug. 
We've added some new plugins during this time (MMO Items, MMOCore, MythicLoot), so I'm not sure if it's those plugins that causes the bug or that it's something wrong with the CMI.

---

---

**Cmi Version (using`/cmi version`):**  8.8.3.10

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 228

**Relevant plugins (Delete if this isn't needed):** MMOItems, MythicLib, MythicLoot

**Comment by CloudeLecaw** [comment] 2021-05-11 13:56
we are not ussuing MMO Plugics or MythicLoot and we are using Version 8.8.4.0 but as server we are using PaperMC with version 1.16.5    maybe you should try to reproduce this first without the mystic and MMO plugins.

On our server it seems not happen. we asked 25 players to clear, took out some single or a full row. 
out of their enderchest and this never happened,,

i do not spect this comes from Tuinity itself..even if this server is not supported by cmi...
i think more its one of the other plugins.

**Comment by 0liverGMC** [comment] 2021-05-12 03:04
Can confirm using a similar setup and this has been happening, there has been several reports of similar things happening across many other discords and github issues. Not sure if it is CMI related or not, I update CMI the most regularly so my guess was that it was CMI.

**Comment by HahaSoStupid** [comment] 2021-05-12 03:09
> Can confirm using a similar setup and this has been happening, there has been several reports of similar things happening across many other discords and github issues. Not sure if it is CMI related or not, I update CMI the most regularly so my guess was that it was CMI. I'll also note that it is wildly inconsistent and I have found no real way to replicate it.

Yup, I can't replicate it too as it only happens to some accounts. Older cmi versions doesn't seem to have this issue. Would be using the older versions for now.

**Comment by CloudeLecaw** [comment] 2021-05-12 04:48
What happens when you tried this without other plugins?
i found no way to replicate this with just CMI + CMILibs + CMIINJECTOR + VAULT + PEX - Server Paper 1.16.5

**Comment by mrfloris** [comment] 2021-05-12 16:55
MMOItems can perhaps have oversized nbt data causing plugins to have incomplete results, maybe this means the original item and handled item both are no longer 100% match and causing it to dupe. This is just a poor assumption, but i've seen mmoitems cause issues with server managing plugins and chest ui plugins before. I have tried loads of stuff and haven't been able to reproduce this at all. I have been going through my player history to dupe check (manually) and haven't noticed anything. 

I wish i knew how to reproduce this so we can have it confirmed and a fix out soon.

**Comment by Zrips** [comment] 2021-05-13 09:36
@HahaSoStupid 
Are we talking here about /cmi ender command or physical interaction with ender chest block? CMI doesn't really do anything special with ender chest, uses basic generic method to open it, and especially relating to specific row of it, as there isint any checks relating to rows or items in general. Any extra information relating to this would be nice to have.  Maybe another plugin responsible for inventory sorting or any other management of it. Maybe inventory got modified by some staff member which glitched it out. We need actual way to reproduce this issue or atleast narrow it down.

**Comment by HahaSoStupid** [comment] 2021-05-13 14:02
Hey there @Zrips,

Both command and normal interaction would duplicate the items. I'll try to reproduce the issue it on my server with the new version again with video if I can. This happens to /inv too actually from what I observe. Do give me some time and see if I can video it down for you sir. I can confirm that this would not happen with an older CMI version (I'm using 8.8.1.0 now). 

Do you need my list of plugins too?

**Comment by Zrips** [comment] 2021-05-13 14:12
If issue can be reproduced with latest CMI builds without any plugins then we will only need consistent way to do so. I can fix any bug which can be reproduced, if this is some random one which happens at some random points then trying to debug it will only be huge time consuming task with most likely no actual results. Any extra information would help, but in general, test this with CMI only, no other plugins present, just to make sure its an issue with CMI and not interference from another plugin.

**Comment by HahaSoStupid** [comment] 2021-05-13 14:15
Let me see what I can do, thanks and appreciate your assistance!

**Comment by levtey** [comment] 2021-05-15 00:22
Had this issue a couple of times, extremely rare unfortunately and hard to reproduce.

**Comment by mrfloris** [comment] 2021-05-15 00:24
> Had this issue a couple of times, extremely rare unfortunately and hard to reproduce.

Some info helps, can you do /cmi version and list of plugins? Does it happen without plugins too?

**Comment by xxirs** [comment] 2021-05-18 23:58
Getting the same issue, when a player interacts with a enderchest places an item inside, and then the server is rebooted the items are either DUPED or deleted. 

CMI Version: 8.8.4.3

**Comment by TheHooperSC** [comment] 2021-05-25 07:17
I have the same problem .. Error in CMI with duplication, please fix immediately and if something like this happens, make the option to downgrade the version, thanks to the fact that I have updated the latest, it now spams me with translation errors.

CMI Version 8.8.4.3

**Comment by Zrips** [comment] 2021-05-25 11:04
Should be resolved with next update

**Closed by Zrips** 2021-05-25 11:04 UTC
Labels: bug report
