### ISSUE TITLE
cmi silent chest mechanics unexpectedly erases items in chests

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#3435] opened 2020-06-02 06:28 UTC
Spigot 1.12.2
CMI8.6.26.7.jar

Player should have permission to open chest in silent mode.
Player should have creative.
Chests are erased even player has no permision to edit chest in silent mode (`cmi.silentchest.editing`)!
Players who have permission only to open chest in silent mode, also could erase that chest!!

As result: players with creative and permission only to open chest in silent mode (without editing) hack other players chests removing items from them!
@Zrips, this is a serious bug!

Do I need to publicate here detail instructions how to do it or to PM with private message?

PS, @CloudeLecaw I think it will be a better day for all hackers if I publish it here.

**Comment by CloudeLecaw** [comment] 2020-06-02 08:10
na not so much player work with silent chests mode, so it should not be a so farwell thing. but a detailed instruction with pictures would be nice to understand the problem.
at the moment im having a bit problems with trying to understand what kind of issue you reported..sorry :3

**Comment by Qveshn** [comment] 2020-06-02 09:28
Player does not delete chest. He removes all items in it while he use chest silent mode and has no permission `cmi.silentchest.editing`. This does not work anywhere else because only CMI manages "silent mode". Without silent mode this is not reproduced anywhere else.

I send private message @Zrips to discord with video how it works.
I am afraid to publish it here because hackers can use it.

There no any permission plugin. Only spigot 1.12.2 and CMI. There are no other plugins to keep the test clean.

There no any permission plugin to make test simpler. Only CMI and no others.
To prevent editing chest in silent mode I have deoped myself and then show how to erase items in chest.
No matter, you have edit permission or not... Items disappear unexpectedly when I do non-standard action. I discovered this action by accident, It may not be reproduced the first time, but if you practice it, it will be obtained almost always.

**Comment by CloudeLecaw** [comment] 2020-06-02 09:32
> I am afraid to publish it here because hackers can use it.

really? ;)
this is what the hithub is for -  to publish issues and bugs. no real hacker would come here and search for bugs.
And kiddies wanne find bugs on youtube and not on github... but ok i hope zrips now can handle with this and maybe you get a fix ;)

**Comment by Qveshn** [comment] 2020-06-02 09:46
> Setting: GM1 + Silentchestmode true + not allowed to edit
This is because you do one little thing wrong 😃 

My video on youtube has access only by url. At this moment only I and @Zrips has get this url (I hope).

Also, I will not find anywhere mention that you are in the staff. I am afraid. 😟 
May be you ask @Zrips to show you this video

**Comment by CloudeLecaw** [comment] 2020-06-02 10:20
maybe a did a little thing wrong
i really hope u make a better report next time. or else you dont need to create a isuuse or bug report pm dev directly next time - lol
you really have not understood what this github is for.

**Comment by Qveshn** [comment] 2020-06-02 10:23
If you can proof you are inthe stuff, I can show you detailed video in discord.

**Comment by CloudeLecaw** [comment] 2020-06-02 10:28
outch u did not understand a whole thin about the CMI github..
well  this thread is closed for me now. if i see you handling like this aggain the the enxt thread will be reped. now have fun with the dev pmming him, im sure he is happy about this *lol*

**Comment by Qveshn** [comment] 2020-06-02 10:30
As you like. @Zrip has already got this issue

**Comment by CloudeLecaw** [comment] 2020-06-02 10:36
i dont know what this man is talking? i tried it with the video from him i found on google - cant reproduce this. Well maybe not an issues on ym server, what ever i saw my name in the first line so i thought i may have to do with this ^^

but maybe not.
Thanks for sharing the video with tor ;)

**Comment by Qveshn** [comment] 2020-06-02 11:13
I have just reproduced this bug also on:
Spigot 1.15.2
CraftBukkit 1.15.2
Paper 1.15.2

xD

**Comment by Zrips** [comment] 2020-06-02 11:55
@Qveshn 
Tested out this one with regular player and your mentioned settup. Player was not allowed to take out items from chests as expected. Have you tested this one with CMI only to make sure that there is no interference from another plugin?

**Comment by Zrips** [comment] 2020-06-02 11:58
Och nwm, reproduced just after sending this message. Will investigate what exactly causes this and will issue fix/work around this one with next update.

**Comment by CloudeLecaw** [comment] 2020-06-02 12:06
if your lookinh into this could you try to also fix Qveshn  reported isse with the silentchest state on login/logout?
https://github.com/Zrips/CMI/issues/3424

**Comment by Qveshn** [comment] 2020-06-02 12:23
Look, the main word in this bug - "creative mode"
May be when you copy inventory from real chest to the "fake" inventoty, you still copy empty inventory, because may be it is loading from real chest in creative mode with something like async mode in bukkit. And it does not have time to load on the opening event of the chest. I know it sounds like nonsense, but it can be..

Tonight I will also try to find solution with my own plugin for tests. If I find solution, I will post it

Thanks

**Comment by Zrips** [comment] 2020-06-02 12:34
Should be fixed with next build.

**Closed by Zrips** 2020-06-02 12:34 UTC
Labels: bug report

**Comment by mrfloris** [comment] 2020-06-02 22:21
I just want to say thank you Qveshn for reporting this, and zrips for fixing it. I personally appreciate it that you made an effort to limit the public report part to give time to resolve this.

**Comment by Qveshn** [comment] 2020-06-03 09:06
Unfortunately, another bug appeared after fixing this 😟 

1. Player with silent chest mode and edit permission can not remove item from "fake" inventory (he only grabs it but does not extract). But he can put item there.

2. When player1 without silent mode opens the chest (open chest cover) and then player2 with silent mode opens it, then the chest cover is closed. I think player2 makes player1 to close his normal chest and open fake chest that player2 has created. I think player1 should keep his normal chest opened while player2 opens fake chest.

3.  When player1 without silent mode migrates items in the chest, player2 with silent mode see updates. But when player2 begins do something with items, the items is restored as were before. 
Something is wrong with synchonization between normal and fake chest 

4.  When player1 with silent mode migrates items in the chest, player2 with silent mode does not see any changes. Something is wrong with synchonization of fake chest between players with silent mode.

To reproduce it run two or more clients and test how players share the same chest, when some of them have silent mode and others does not

Do I need to create new issue or you reopen this?

**Comment by Zrips** [comment] 2020-06-03 09:17
@Qveshn No need for new ticket, will look into it.
