### ISSUE TITLE
Sit drops down player by 1 block

### ISSUE THREAD

**Issue by RVSkeLe** [Zrips/CMI#8643] opened 2024-04-16 16:08 UTC
### Description of Issue

Exact same problem of [#774](https://github.com/Zrips/CMI/issues/774). When you do /sit and press shift to stand up you get bugged in the block below, enabling player to go in unwanted zones. When doing /sit and again /sit the bug doesn't work.

### Version Information

```shell
Versione di CMI: 9.7.0.6 Unknown  SqLite
CMILib: 1.4.6.1 -> 1.4.6.2
Server: Purpur(2000) 1.20.1-R0.1-SNAPSHOT-
CMI economy: Disabilitato CMI Chat: Disabilitato 
Modules -> 44 enabled 15 disabled: mirror, launchPad, tablist, moneyCheque, skin, jail, dynamicSigns, flightCharge, ranks, firstJoinMessages, playerCombat, votifier, shulkerBackpack, headDrop, namePlates
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment] 2024-04-21 11:42
More teleport changes have been made since that release you're using, can you try to upgrade and see if the latest cmi and cmilib combo resolves this for you? i cannot reproduce this on 1.20.4 at the moment with the latest (but every server is different of course)

**Comment by Zrips** [comment] 2024-04-30 14:07
@RVSkeLe 
There will be some changes relating to teleportations with next update. No direct changes to sit command, but exiting sitting position does teleport you which could be resolved with those teleport changes. If issue persists with next update, please make a new ticket with some extra information, like, does it work with every block, do players sit on solid 1 block height blocks or any other additional information to help out to narrow down this issue. Closing this ticket for now.

**Closed by Zrips** 2024-04-30 14:07 UTC
Labels: bug report
