### ISSUE TITLE
WarmUps commands

### ISSUE THREAD

**Issue by mario414x** [Zrips/CMI#8209] opened 2023-10-27 20:16 UTC
### Description of Issue

Hello! Let's take this scenario:

Player A -> has 2 homes: A, B
Player A use /home A -> he goes to home A without issues
Player A use /home C -> he will get "Invalid home" error

Now, we will configure WarmUps from configuration with 3 seconds delay.

Player A -> still has the 2 homes (A,B)
Player A use /home C -> he will get the warmup message and particle effect, but he won't be teleported anywhere, because his destination is not valid.

Here is what could be changed: if the command won't do something (like /home [wrongdest]), the warmup won't apply. In this case, the "Invalid home" message will be return. Also, this should apply to more commands teleportation commands, like /warp [name].

### Version Information

```shell
latest version
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment] 2023-11-01 12:40
Well there are more cases where using a wrong command could be triggered after warmup..
well it should not just be added for home.. for all (check before warmup if command would be vailed)

at least its not a bug or issue. its a request.
so pls recreate it here
https://github.com/Zrips/CMI/discussions/new?category=enhancement


and close this issue ticket.

**Comment by Zrips** [comment] 2023-11-14 14:56
@mario414x 
Issue is that we can't know if command will be performed or not before it actually goes over its dedicated process, so without having overly complicated checks for every single command from CMI and excluding 3rd party due to impossibility to check those, it would be quite tedious and huge work with limited results.
Sadly there is no good solution here besides players just remembering their home names or just using tabcomplete for actions like that to limit how many times they got it incorrectly.

**Closed by Zrips** 2023-11-14 14:56 UTC
Labels: bug report
