### ISSUE TITLE
hologram new display

### ISSUE THREAD

**Issue by WayneFX** [Zrips/CMI#8272] opened 2023-11-19 22:11 UTC
### Description of Issue

What can cause the error java.lang.IllegalStateException: EntityTeleportEvent may only be triggered synchronously. related to holograms? Error appears when new display mode is enabled and vertical/fixed position
Purpur 1.20.2 build 2092
CMI 9.6.8.1
CMILIB 1.4.3.2
Not use VIA!

### Version Information

```shell
9.6.8.1
```

### Errors

```shell
[00:27:53 WARN]: java.lang.IllegalStateException: EntityTeleportEvent may only be triggered synchronously.                                                  [00:27:53 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)                                           [00:27:53 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)                                [00:27:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)                                                    [00:27:53 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)                                                                                  [00:27:53 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:630)                                                [00:27:53 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:594)                                                [00:27:53 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:588)                                                [00:27:53 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:35)                                     [00:27:53 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2057)                                [00:27:53 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1678)                                    [00:27:53 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$6(CMIHologram.java:2093)                                     [00:27:53 WARN]:        at CMILib1.4.3.2.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)       [00:27:53 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)                                                      [00:27:53 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)                                             [00:27:53 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)                             [00:27:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                        [00:27:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                        [00:27:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment] 2023-11-20 00:37
Confirming, getting the same on Paper 1.20.2 b297. Went back to b292 and holos returned/spam was gone.

Error: https://gist.github.com/mercurialmusic/d9c9b730c3311d15f1bf14f6fb603b11

[19:37:04 INFO]: CMI plugin version: 9.6.8.1 BungeeCord CMIB  SqLite
[19:37:04 INFO]: CMILib: 1.4.3.2 
[19:37:04 INFO]: Server: Paper(297) 1.20.2-R0.1-SNAPSHOT-
[19:37:04 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
[19:37:04 INFO]: Modules -> 57 enabled 2 disabled: ranks, skin

**Comment by mercurialmusic** [comment] 2023-11-20 00:39
This is a duplicate of #8270

**Comment by WayneFX** [comment] 2023-11-20 08:08
Perhaps there were some changes in the api of the kernel, so it pours errors, I'll try to roll back too

**Comment by Zrips** [comment] 2023-11-21 11:22
Will be fixed with CMILib and CMI updates. Which should happen today if everything goes by the plan

**Closed by Zrips** 2023-11-21 11:22 UTC
Labels: bug report

**Comment by WayneFX** [comment] 2023-11-21 22:34
No error, but the hologram is now invisible, it's just not visible when you switch on new display
