### ISSUE TITLE
Rank specific item is defined not work

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#191] opened 2018-04-01 16:54 UTC
If an block is specified in StatsRequirements, no count blocks, examples:
"BlocksMined:planks:30"
"BlocksMined:dirt:30"
"BlocksMined:bookshelf:10"

Not specified if it works, examples:
"BlocksMined:20000"

**Comment by Zrips** [comment] 2018-04-06 12:12
Try performing full restart if new requirements are not been taken properly as its seems to work for me correctly.

**Comment by C4BR3R4** [comment] 2018-04-06 13:42
It's the first thing I've tried and nothing.

**Comment by Zrips** [comment] 2018-04-06 14:27
That's strange, Which mc version are you running?

**Comment by C4BR3R4** [comment] 2018-04-07 06:31
Spigot 1.12.2-R0.1-SNAPSHOT #1544

**Comment by LogGits** [comment] 2018-04-09 13:39
Cannot reproduce. Can you please provide your ranks.yml or atleast a rank we can test that is already setup. All these work for me except for planks but that is a mojang issue with not logging all types of a block just its base id.

**Comment by LogGits** [comment] 2018-04-24 15:09
I am closing this issue as, it is an issue with Mojang's statistics logging system.

**Closed by LogGits** 2018-04-24 15:09 UTC
Labels: awaiting answer, bug report
