### ISSUE TITLE
After the teleport, /fly is deactivated

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [Zrips/CMI#7401] opened 2022-11-26 17:29 UTC
### Description of Issue

Hello, yesterday I updated the CMI plugin to the latest version and whoever activates /fly, after teleporting to another world /fly is deactivated. He has to type the command again to fly again.

I have AntiWorldFly, but i have same version more than 2 months and only for SpawnNew - Event world
Thanks

### Version Information

```shell
[18:22:25 INFO]: CMI: 9.2.5.5 BungeeCord MySQL
[18:22:25 INFO]: CMILib: 1.2.3.7
[18:22:25 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[18:22:25 INFO]: CMI economy: POVOLENO Vault: 1.7.3-b131(CMIEInjector) CMI Chat: ZAKAZÁNO
[18:22:25 INFO]: Modules -> 46 enabled 11 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, tablist, skin, noTarget, elytraBoost, spawnerCharge, paintingEditor, playerChatTag
```

### Relevant Config Sections

```yaml
WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: false

AntiWorldFly config:
antiFlyWorlds:
- SpawnNew
```

### Relevant Plugins

AntiWorldFly-2.5.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Rexmen1** [comment] 2022-11-27 03:23
Yea its bcz of latest update, It should disable fly only when they don't have fly permission or no flight charges left but its disabling everytime... I think for now going back to old method will be good until fixed...

**Comment by mercurialmusic** [comment] 2022-11-27 07:52
Throwing my hat in this ring as well. The new behavior is god awful. It's even removing fly when in spectator mode and going between worlds. Now every time I change a world I'm having to redo fly, even as OP. At the very least the bypass permission should be respected here.

**Comment by CloudeLecaw** [comment] 2022-11-27 18:04
it might has to do with the "fix" tat was made in latest version.

We also see this issue now on our server
Fly gets chanelt now each time someone even the owner changes a world.

**Comment by OceaniaCraft** [comment] 2022-11-28 06:04
Same issue here. Players are losing fly when changing worlds no matter what we do. No permissions/settings have any effect. Even worldguard regions with "Fly:allow" do not work.

Please revert these changes ASAP.

**Comment by Zrips** [comment] 2022-11-28 11:05
Oversight from my side, will issue fix for this one today

**Closed by Zrips** 2022-11-28 11:05 UTC
Labels: bug report

**Comment by Rexmen1** [comment] 2022-12-01 02:51
Still disables when changing worlds... Even when fly is allowed in those worlds...

**Comment by mercurialmusic** [comment] 2022-12-01 11:03
> Still disables when changing worlds... Even when fly is allowed in those worlds...

For what it's worth, it was fixed for me in the last update, so it might be down to your settings/config/permissions at this point.

**Comment by CloudeLecaw** [comment] 2022-12-01 11:44
for us it also was fixed with the latest version.

**Comment by OceaniaCraft** [comment] 2022-12-01 11:47
The main issue was fixed for us, but fly is acting far different since these updates. We are dealing with many issues caused by this change. Obviously these are our issues as the methods used have all changed, but its frustrating to deal with.

Not sure these changes were needed in the first place as everyone has come to accept how cmi handled fly.

But yes, the latest update did fix the major issue this post was about.

**Comment by Rexmen1** [comment] 2022-12-03 02:05
Its working fine for op, but not for normal players and have no idea what permission to give at this point.. tried few

**Comment by CloudeLecaw** [comment] 2022-12-03 21:36
> Its working fine for op, but not for normal players and have no idea what permission to give at this point.. tried few

any eventCommand on worldxhange or teleported?
any other plugin that change habit like Multiverse-Core? any other plugins that dies this? any worldlimits might set?  its normal your oos would bypass these all

**Comment by Rexmen1** [comment] 2022-12-04 05:44
it was working fine before the update, so it shouldn't be an issue with other plugins...  and works for me with owner op perms... So has to be cmi permission issue..

**Comment by CloudeLecaw** [comment] 2022-12-04 16:31
> it was working fine before the update, so it shouldn't be an issue with other plugins... and works for me with owner op perms... So has to be cmi permission issue..
> 
> No world limits set either...

You doing something perm related after teleporting or worldchange?
if so you might should add a delay a little before the checks

**Comment by Rexmen1** [comment] 2022-12-06 15:14
yea using delay and working fine before the update... nothing changed except the update.

**Comment by Rexmen1** [comment] 2022-12-14 03:24
disabled the world event commands and still causing world change fly disable issue for players....

**Comment by Sh3r1ffCZ** [comment] 2023-01-19 16:38
[17:37:42 WARN]: [CMI] Task #347953 for CMI v9.3.0.6 generated an exception
java.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false
at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.setFlying(CraftPlayer.java:2157) ~[purpur-1.19.3.jar:git-Purpur-1895]
at com.Zrips.CMI.AllListeners.WorldLimits.lambda$0(WorldLimits.java:90) ~[CMI-9.3.0.6.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1895]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1895]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1895]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1895]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1895]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1895]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1895]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

Version: 9.3.0.6

**Comment by EagL3-GIT** [comment] 2023-01-19 19:29
Yep, its broken in the latest version

**Comment by Strahilchu** [comment] 2024-05-31 22:31
Is there a fix for this? Jesus christ!

**Comment by Strahilchu** [comment] 2024-10-10 22:41
What about now?
