### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/CMI#3766] opened 2020-07-18 17:52 UTC
Hello, it would be nice if you put a system so that the CMI updates are done automatically (this directly download and change the .jar)

Thank you !

**Comment by variananora** [comment] 2020-07-19 14:45
Duplicate of #3550

**Comment by Zrips** [comment] 2020-07-19 14:54
At this point there will not be auto updater feature. If i will figure out decent way to achieve this without publishing some direct download link and avoid pirated versions being auto updated will add that.

**Closed by Zrips** 2020-07-19 14:54 UTC
Labels: feature request

**Comment by SlyTheFloof** [comment] 2022-01-27 20:39
pog idea
