### ISSUE TITLE
Private Message Error

### ISSUE THREAD

**Issue by FestusDM** [Zrips/CMI#2780] opened 2020-02-09 20:41 UTC
When using `/cmi msg` alias `/msg` then using tab, it no longers show players on the server.
Instead, it shows all CMI commands as if using `/cmi`
---

**Cmi Version (using`/cmi version`): 8.6.19.1** 
**Server Type (Spigot/Paperspigot/etc): Paperspigot** 
**Server Version (using `/ver`): Paper 655**

**Comment by mrfloris** [comment] 2020-02-11 07:25
I have the correct permissions, and I have alias.yml updated to be 'true' to allow use of /msg, restarted the server, and used /cmi msg and /msg, in both situations it showed the list of online players (in the screenshot, just me btw). I can't reproduce this (but I am not on paper, i am on spigot 1.15.2)

<img width="342" alt="Screenshot 2020-02-11 at 08 23 17" src="https://user-images.githubusercontent.com/28841349/74217523-fa407880-4ca7-11ea-942a-c5abed93d776.png">
<img width="264" alt="Screenshot 2020-02-11 at 08 23 57" src="https://user-images.githubusercontent.com/28841349/74217528-fb71a580-4ca7-11ea-927d-64e479c65473.png">
<img width="322" alt="Screenshot 2020-02-11 at 08 23 28" src="https://user-images.githubusercontent.com/28841349/74217529-fc0a3c00-4ca7-11ea-878f-936a8fa879ce.png">

Did you by chance create a customAlias through /cmi aliaseditor for /msg ?

**Comment by FestusDM** [comment] 2020-02-11 07:54
Got the correct permissions and `alias.yml` is set to true. Exactly like yours in your screenshot.
Using `/msg` gave the error that I wrote above but using `/cmi msg` doesn't and works normally with a list of online players.

I don't have any custom alias for `/msg`.

**Comment by FestusDM** [comment] 2020-02-11 21:08
Rolled it back to 8.6.19.0, no issue there.
Issues showed up in 8.6.19.1.

**Comment by FestusDM** [comment] 2020-02-20 19:45
Issue shows up in 8.6.19.4 and 8.6.19.5 as well.

**Comment by FestusDM** [comment] 2020-02-25 19:59
Issue still persist in 8.6.19.6.

**Comment by FestusDM** [comment] 2020-03-04 17:29
Issue persist in 8.6.20.1.
![Screen Shot 2020-03-04 at 09 27 47](https://user-images.githubusercontent.com/29752246/75905903-91f23c00-5dfa-11ea-8709-c7c0d5cec2e6.png)

**Comment by FestusDM** [comment] 2020-03-10 17:22
Issue persist in 8.6.20.2, 8.6.20.3, and 8.6.20.4
This seems to happen with /w and /whisper as well
@mrfloris Do you have this happening? What are your settings like? Feel free to contact me via Discord if it's easier. Thanks.

![Screen Shot 2020-03-10 at 10 20 08](https://user-images.githubusercontent.com/29752246/76340535-f90b6700-62b8-11ea-8c3d-001afdbe0b1e.png)
![Screen Shot 2020-03-10 at 10 21 10](https://user-images.githubusercontent.com/29752246/76340538-fad52a80-62b8-11ea-8391-ed7b681827a1.png)

**Comment by Zrips** [comment] 2020-03-10 18:19
This might be related to another plugin taking over this particular alias and tab completing it or messing up its complete entirely. Do you have any plugin which would be using those alias?

**Comment by FestusDM** [comment] 2020-03-12 04:24
No, only thing that has those alias is CMI.
Turned `/msg` to true under `Alias.yml`
Under `CustomAlias.yml`, I have the following:
`w:
Cmds:
- cmi msg $1-

whisper:
Cmds:
- cmi msg $1-`

Could that be messing with it?

**Comment by FestusDM** [comment] 2020-03-27 13:20
As of 8.6.20.8, the bug is still there.
All tab-complete listed are all CMI commands/functions.

**Comment by Zrips** [comment] 2020-08-06 13:58
Should be resolved with latest build

**Closed by Zrips** 2020-08-06 13:58 UTC
Labels: bug report
