### ISSUE TITLE
CMI Enchant with other modpacks

### ISSUE THREAD

**Issue by michael040990** [Zrips/CMI#7254] opened 2022-09-25 09:43 UTC
**Description of issue or feature request:**
when trying to enchant items with /cmi enchant it doesnt show the enchants for other mod packs in the tab menu, it shows items labeled as "unknown_enchant_103", "unknown_enchant_108".
if you were to enchant a item with "/cmi enchant (username) unknown_enchant_103 1" it will enchant the item with the enchantment from one of the modpacks.
however if you try to type in the enchantment by the name such as "/cmi enchant (username) somanyenchantments:supremesharpness 1" it will give a error saying "Incorrect enchant name or id."

---

**Relevant plugins (Delete if this isn't needed):** 
somanyenchantments
spartanshields
spartanweaponry
switchbow

**Comment by Zrips** [comment] 2022-10-04 11:57
Should be fixed with next CMILib update, if issue persists, lets me know.

**Closed by Zrips** 2022-10-04 11:57 UTC

**Comment by kalirenegade** [comment] 2022-10-25 07:43
im getting this error when trying to enchant with the new update 
`Server thread/INFO03:38:09
Kalirenegade issued server command: /cmi enchant somanyenchantments:advancedsharpness 5
Server thread/ERROR03:38:09
null
Console03:38:09
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.2.4.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-dae70adc]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-dae70adc]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) ~[CraftServer.class:git-CatServer-1.12.2-dae70adc]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1667) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1468) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_342]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_342]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getByKey(Lorg/bukkit/NamespacedKey;)Lorg/bukkit/enchantments/Enchantment;
at net.Zrips.CMILib.Enchants.CMIEnchantment.getByName(CMIEnchantment.java:143) ~[?:?]
at net.Zrips.CMILib.Enchants.CMIEnchantment.get(CMIEnchantment.java:124) ~[?:?]
at com.Zrips.CMI.commands.list.enchant.perform(enchant.java:141) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-dae70adc]
... 15 more
`
and its still showing the "unknown_enchant_101" names when tabbing though the enchantments, doing" /cmi enchant unknown_enchant_101" works but "/cmi enchant somanyenchantments:disarmament" doesn't which is the same enchantment based off the enchantment of the "/cmi enchant unknown_enchant_101" enchanted item
