### ISSUE TITLE
Shulker Box Crash by [item] in chat

### ISSUE THREAD

**Issue by naikyy** [Zrips/CMI#5174] opened 2021-02-26 11:21 UTC
Hello when I want to ping Shulker box to chat and has some special items in it it can crash server, I've tried that many times and yeah, its because of this. Players can then crash server that easily.

Screen of example Shulker what crashed the server: https://i.imgur.com/jFoStns.png
---

**Cmi Version:** 8.8.1.3

**Server Type:** Purpur - newest build, was doing on Tuinity too

**Server Version:** newest build

**Comment by CloudeLecaw** [comment] 2021-02-26 18:33
Can you reproduce this with PaperMC or Spigot (not with the forks your using) ? 
Why  ask? Because forks can do alot of strengh things..
So pls confirm first (with /cmi version) that this issue comes with Spigot or PaperMC too.
Else dont asspect support.

**Comment by Zrips** [comment] 2021-03-02 14:43
@naikyy 
Can you provide actual shulker box which creates this crash? You can save it with saveditems command and then provided its contents. Or atleast provide crash logs so we will know whats going on here exactly.

**Comment by naikyy** [comment] 2021-03-26 18:38
There is the shulker box by command /saveditems
`dc:
  ShulkerCrashing:
    Item:
      v: 2586
      type: PINK_SHULKER_BOX
      meta:
        ==: ItemMeta
        meta-type: TILE_ENTITY
        display-name: '{"text":"Vzááácnosti"}'
        internal: H4sIAAAAAAAAAO1cy27bRhQdvxLHaB5N80bRCuo2QKm36K74BIwEbZAE6aIoBFoaSawoUqXIJEqQXbvMokCLdhOgBgp0U6Nf4JXSH+kHdN9dh4xtXlNyYiPpYYBQXhgWxzzDy5m599x7ZtYYW2NnVMdrDww3sIPJXat3iq1sBHw4XmOMnV1gy3ccL1hYYCuaF7rBwhpbCqzeEjuhW0Orx0Ub8dXJjj0eOdZklS1/bg35yvbjIn8Y+FZx/avHxU3P6RTXu5Yz5teLdmA5dnv/z9DtcN+xXZ60GAe+PeBB3/fCXn//W2+zG47bVkAatj3H84vrxU+MuiQ+xevFQICKL/5+9l3xyXUEsFYxK2YCXMDAmuWG2SCwt0GwTdVUCawFgo0/CewwG9gRCFbRq3o1gfVAsHVFfBLYMJuR3AbNW6NWrREj90GwSln8wJeLucvj1/t/Fp+cYss3PZ+vRmv56Y8yXbrvwEwiSzJ8chuNUrlUTmA5CLZZ0koafpbJ5Vq5lsDasFlmlsmaMt0C4aqVZqWZ4DqoGKRarpIx5YJg9apaVYmVt2FLt/jg11CzZtSMBPYeyD9K9Ua9gR/LZqkhfuCDSoQDSkPBBz/lZrVJwoHnT0G4labe1PFWrsoNuYGfumZNkRQJz5ZSoa0Bgm2oFbWSwHZgJE1TNbjTNWWtrtXhIYapaKZmwgMqU9VlXcaPZM0oG8TVl0GwuqEZZEhJIFjhc80a/mlTvF86yJXYKfae4bb7lhsMuRvESbITq2zR7rALQwHd9q1usB5dd7noSm+RLTn3HbbAXrQ5n7SxhyOLtFjbbfF+0sLxvCBpcGJeg4nlBJPD7yC62JntBOlo6G763BrQbszeRdiwI56V7eYCl1O5wJn0H/sdzCFrWkOn/Pa3wj3LET2e7rjjwXSncMOZbj9/WhAXUi9zjZ2/FW6KHqnhYGAH4r9CPl5lV3qiz9wVTx/w8Xrvxe/WgE/Y6v34xhNXWOnELfF6PJedTSzFh6NgsmvAS8SA9mjEOy3L970He1Y8+Sornv4RasWyYOJVasVffsVMuLIqSbUyfDGtlAQsiYI0EGxDwOrwELeiSVKdGNnHwFbLAraJh20KWGJkUDazqktSg4R8oKxSrSJgiZEDEKwsYA147FUzJKmJj6vrVQGLD/nqioAlRlZBsKYkyfgqRKMmYGU8rPBAsgGfQGKRkhRi5DEIVjh6BT+Sm8IDKSSu/gIDKws3rxIjd0Gwws2r+FKPLDwQLdGCyimKcPNaDT5vFTGDNAUeXSjCA+kSHFYVbl7HG1kVbl4nif4HIFjhgQx8slATHsiop1jQIbXSRfYMydAcu9cPWqPQHzmczHAvdDYFjewUNjY2Uuz2y9nuBX7I95vc5D3udqZbvjvdLmz6Lo9+Pxp4fjgcefctd7rT7hdUr//Xn0fOgVxLSO+mY41Ff30v4O2IJ6eyFFeTll1uBX3ut8QDz0mI0Ia2zw+/43HyHofe5OW5kSW2MhbcfRy9fSqBEheuWLzFE6N8Nt57MfHVmUdxefTIdsBbm150w92swNpLdFZsNkXwM7xY31QOJFpwCoamBl8MYljiTUFFvwhWJlwdpLOKYYl/QdWvI9gmnEbGsMStocrm9UyoRgSrkHrudAeIW8VbWXhxpQFnVvHTkvVxAITVs3m5Kj5Ei2FJAuguELYGj/pjWLI8okRUESxZHkFZthgWn1OMYDW83CWGrWbiDLRGJvOWsvWbQFi6OqLkgPWDWQKgD9IrmfggnfDmCRAWn8uMYbUUETpMUX3m30xJGk5RfYCioRTVKYqGZA/EYaAU1fWDZRlgMCBnoEKNceVsGKmWDTWkunWUojrFDYFrKKWGwOQKpYbA5IqSzVBWtEyWR1rrA84gtZRJPE1LjFD+Xc/GynImgS0VNgMDW8pIkb5Py2ZVppQUScDJUAamGzQ5k3hKy2A/XgSbTXJFz2Yk043UIPl4mgiDxPJpIox8WjKSS2+LWP7kq8TySyCx/OmZgu7abT6ybF/zxkGUHphjouUZZN7t2m2bu+3X0fqPbWfQCryw3T/WI9IS9LmZEvTqo4yP+vj+nTrqA7XvNHXUB2zfaWrzDWpHZAo2o0M3UPtO08dfAIkDnbuwfaept4uauqpu6ngtZnrqorZE1mSTZq9A9Cy9PqJi2mhrIoFFFYNTTgiVvJJLZgk/geb6+sOqLAufZntuzYi37emWEyko7YAPC4+sgReOuDvdodZ6Ib9EdOjedMv1nj8V/RkW7noD7vJhKjbfDf4uz9MkWg/5XgB7biaAPZ9SOnatKJBdedOi0NfTen58QOv5TXQT5yX3exPS0LQClLuxZJfHCtDjqEWX2MXU5bbVDsJYdTobgP/zDmlADfwiFG1JIvV0JZuSG+jQu3TpCxQIx/UC/I6KGBa/oyJdC7oPhDUyeVoq10OqBMkEupFNlQJYXtTIBAKWF+m+L9Q5iqm0PXAka9lot3WyHQAprcpGJXhUadUK+wEZ+1jfhhY5LyIOyQozm65+QnYpOqck6ZKxF3DO2Qv2NLtumVZQuJfqztu9cy6X7P3fsLlkD8sfcsleLtnLJXu5ZC+X7OWSvVyyl0v2csleLtnLJXu5ZG9WskeOOFneLXx9OK9E6PBez3Z7+yeXnN+rEy4edirsH9lz/tmjYfVwMN0K5hwNO6ecuXAMRSDRLo5sd9DqTPYrqh+88vzc3FIvLHUhH1NHtNTFfEwd0VKXcksd0VKXc0sd0VJX8nXqiJa6mo+pI1rqWj6mXmUpxv4Dx7Fm8b90AAA=
        blockMaterial: PINK_SHULKER_BOX
`

There is no crash, it just disconnects all players and they can join back but it really does shulker by pinging it in chat.

**Comment by naikyy** [comment] 2021-03-26 18:40
The content of shulker whats crashing it has HEX name with lore, we also use special enchants by plugin AdvancedEnchantments, so it has unvanilla enchantments. But when I ping the item while holding it in hand it doesnt crash, it is doing only with Shulker.

**Comment by naikyy** [comment] 2021-04-02 10:52
Hello, another crash what caused plugin AdvancedEnchantments, its doing just with Shulker, single item with that plugin is not "crashing" the server.
There is the ping in chat and then kick of all players: https://pastebin.com/nHHz1J7k
This is another shulker box: https://i.imgur.com/m1pMlPw.png

**Comment by Zrips** [comment] 2021-05-07 15:02
Reproduced, should be resolved with next update

**Closed by Zrips** 2021-05-07 15:02 UTC
Labels: bug report, unconfirmed
