### ISSUE TITLE
update api cmi and uperms

### ISSUE THREAD

**Issue by linuxhus** [Zrips/CMI#1060] opened 2018-11-12 22:47 UTC
Hi so what is this ?
TechXcrafter say at you must update the api ?!

[23:40:48] [Craft Scheduler Thread - 192/WARN]: [CMI] Plugin CMI v8.0.21.4 generated an exception while executing task 5098
java.lang.NoClassDefFoundError: me/TechXcrafter/UltraPermissions/UltraPermissions
at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:176) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager.updateTablistName(TabListManager.java:326) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:372) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[23:40:48] [Craft Scheduler Thread - 199/WARN]: [CMI] Plugin CMI v8.0.21.4 generated an exception while executing task 5099
java.lang.NoClassDefFoundError: me/TechXcrafter/UltraPermissions/UltraPermissions
at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:176) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager.updateTablistName(TabListManager.java:326) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:372) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by LogGits** [comment] 2018-11-13 00:50
Duplicate of #1040

**Closed by LogGits** 2018-11-13 00:50 UTC
