### ISSUE TITLE
Interactive command "cooldown:[sec]! doesn't work when too high. No errors what so ever

### ISSUE THREAD

**Issue by imparium-de** [Zrips/CMI#5213] opened 2021-03-03 19:06 UTC
**Description of issue:**
`cooldown:10! asConsole! money give [playerName] 10000` works
`cooldown:604800! asConsole! money give [playerName] 10000` doesn't work. 1 week. No errors.
`cooldown:2419200! asConsole! money give [playerName] 10000` doesn't work. 1 Month. No errors. Player can spam the sign.

Where's the limit?

---

**Cmi Version (using`/cmi version`):** 
8.8.1.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-469

**Comment by CloudeLecaw** [comment] 2021-03-04 07:37
have you also made sure its the right cooldown u used?

- if command starts with cooldown:[timeInSec]! then that line or any following ones (if defined) will have cooldown before reusing it. Example: cooldown:5! cmi heal [playerName] will heal player, but not more frequently than every 5sec.
- if command starts with ucooldown:[timeInSec]! then differently than previous cooldown this will apply depending on source. So you can have different cooldowns if it was triggered from different InteractiveCommands or different custom alias.
- if command starts with gcooldown:[timeInSec]! then cooldown will be applied server vide and if it was triggered no one else can trigger it again until cooldown ends

**Comment by derMiepz** [comment] 2021-03-04 15:06
Yes. I've checked the exact wiki part of the text you pasted. The normal `cooldown` without `u` or `g` should work, but it seems like it's not working with bigger values. Tbh, I didn't check how long I can go because I don't wanna spend days on troubleshooting a single command from a plugin that isn't coded by us, but one week or month in seconds is already too long.

**Comment by imparium-de** [comment] 2021-03-04 15:08
Yes. I've checked the exact wiki part of the text you pasted. The normal `cooldown` without `u` or `g` should work, but it seems like it's not working with bigger values. Tbh, I didn't check how long I can go because I don't wanna spend days on troubleshooting a single command from a plugin that isn't coded by us, but one week or month in seconds is already too long.

**Comment by Zrips** [comment] 2021-03-06 15:25
Confirmed. Will be fixed with next build.

**Closed by Zrips** 2021-03-06 15:25 UTC
Labels: bug report
