### ISSUE TITLE
Custom Text Console Command <CC> can't click to send the command in chat.

### ISSUE THREAD

**Issue by LoJoSho** [Zrips/CMI#6023] opened 2021-08-11 22:15 UTC
**Description of issue:**

When a player clicks on a text message with <CC>, it doesn't send a command. <C> (sending a command from the player) does work though. All commands I have tried could be sent through the console perfectly fine.

[GIF](https://i.imgur.com/NtvpVoG.gif)

`<T>&e[->]</T><H>&7Click Me!</H><CC>cmi ctext guard2 [playerName]</CC>`
(I have tried it with other commands as well, doesn't work)

**Cmi Version (using`/cmi version`):** 
9.0.2.5
**Server Type (Spigot/Paperspigot/etc):** 
PurPur
**Server Version (using `/ver`):** 
git-PurPur-1310

**Comment by Zrips** [comment] 2021-08-12 09:58
Cant reproduce this issue currently. Tho keep in mind that <CC> creates one time use command while <CCI> would create one which can be used infinite amount of times. Other than this cant reproduce issue so cant really resolve this issue at the moment.

**Comment by LoJoSho** [comment] 2021-08-12 23:18
That's really odd, are you on 1.17.1 when reproducing this issue? 

As for some fixes, I have tried:
1. Revert back to PaperSpigot 
2. Remove everything besides the click button 
3. Remove all plugins so that only CMI & CMILib is left.
4. Remove the variable in the command 

None of these work. If there is anything more I can do, let me know!

**Comment by Zrips** [comment] 2021-08-13 09:42
I did tested with 1.17.1 paper and purpur builds, both worked as it should. Can you provide exact code you used for it? Like ctext file contents so i could test it with your exact setup just to be sure that we are on same page

**Comment by LoJoSho** [comment] 2021-08-13 15:21
@Zrips Of course, here is the file I am using for the custom text. 

`&r
&r
&r
&r   &e&lThe Tester Test
&r
&r    &7Welcome Traveler to the home of Fluff...
&r    &7Here on Fluff, you can explore alot...
&r
<T>&e[->]</T><H>&7Click Me!</H><CC>cmi heal [playerName]</CC>
&r`

**Comment by mrfloris** [comment] 2021-08-15 20:08
> Cant reproduce this issue currently. Tho keep in mind that creates one time use command while would create one which can be used infinite amount of times. Other than this cant reproduce issue so cant really resolve this issue at the moment.

I can reproduce it.
Using /cmi ctellraw it works, putting it in a .txt file, and /cmi reload, and using /cmi ctext file .. it shows the text, shows the hover, i click it, doesn't do anything.

**Comment by Zrips** [comment] 2021-08-16 12:05
Will be resolved with next CMILib update

**Closed by Zrips** 2021-08-16 12:05 UTC
Labels: bug report, unconfirmed
