### ISSUE TITLE
Unable to load plugin & Could not pass event error

### ISSUE THREAD

**Issue by Lostpart** [Zrips/CMI#714] opened 2018-08-05 20:39 UTC
**Description of issue or feature request:**
When loading it appear this following mistake, and when server finish starting, it keep appear many “ Could not pass event” error

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[04:23:34 INFO]: [CMI] Enabling CMI v8.0.4.2
[04:23:36 INFO]: [CMI] GroupManager permission plugin will be used                   
[04:23:38 INFO]: [CMI] Loaded (43) regular alias into memory. Took 25ms
[04:23:38 INFO]: [CMI] Loaded (1) custom text's into memory. Took 7ms                
[04:23:38 INFO]: [CMI] Started (MySQL) data base. Took 95ms
[04:23:38 INFO]: [CMI] Vault was found - Enabling capabilities. Economy: iConomy 6   
[04:23:39 INFO]: [CMI] Can't determine sound name for tag. Trying to defaulting to BLOCK_NOTE_HARP                                                                        
[04:23:39 INFO]: [CMI] Can't find BLOCK_NOTE_HARP sound, setting to AMBIENCE_CAVE
[04:23:39 INFO]: [CMI] Loaded (5) warning categories into memory. Took 2ms
[04:23:39 INFO]: [CMI] Loaded (3) warning commands into memory. Took 0ms             
[04:23:39 INFO]: [CMI] Loaded (5) kits into memory. Took 16ms
[04:23:39 INFO]: [CMI] Loaded (0) cooldowns into memory. Took 6ms                    
[04:23:39 INFO]: [CMI] Loaded (5) kits into memory. Took 1ms
[04:23:39 INFO]: [CMI] Loaded (7) ranks into memory. Took 56ms                       
[04:23:39 INFO]: [CMI] Loaded (8) playtime rewards into memory. Took 5ms
[04:23:39 INFO]: [CMI] Loaded (2) Player data into memory. Took 154ms                
[04:23:39 INFO]: [CMI] Loaded (2) playtime records into memory. Took 15ms
[04:23:39 INFO]: [CMI] Loaded (0) playtime reward records into memory. Took 1ms      
[04:23:40 ERROR]: [CMI] Plugin CMI v8.0.4.2 has failed to register events for class com.Zrips.CMI.AllListeners.PlayerListeners because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.
[04:23:40 ERROR]: [CMI] Plugin CMI v8.0.4.2 has failed to register events for class com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandListener because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.
[04:23:40 ERROR]: [CMI] Plugin CMI v8.0.4.2 has failed to register events for class com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.                                              
[04:23:40 ERROR]: [CMI] Plugin CMI v8.0.4.2 has failed to register events for class com.Zrips.CMI.Modules.AStand.ArmorStandListener because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.
[04:23:40 INFO]: [CMI] Registered events. Took 704ms                                 
[04:23:40 INFO]: [CMI] Loaded (346) worth values into memory. Took 86ms
[04:23:40 INFO]: [CMI] Loaded (0) event action commands into memory. Took 6ms        
[04:23:40 ERROR]: Error occurred while enabling CMI v8.0.4.2 (Is it up to date?)
        java.lang.StringIndexOutOfBoundsException: String index out of range: 1                      
        at java.lang.String.substring(String.java:1963) ~[?:1.8.0_131]
        at com.Zrips.CMI.Modules.Enchants.EnchantManager.loadLocale(EnchantManager.java:78)~[?:?]                                                                                
		at com.Zrips.CMI.Config.LoadLang(Config.java:536) ~[?:?]
        at com.Zrips.CMI.Config.LoadLang(Config.java:390) ~[?:?]                             
		at com.Zrips.CMI.CMI.onEnable(CMI.java:1496) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:359)[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]                                          
		at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
————————————happening during running
06:50:03 ERROR]: Could not pass event PlayerInteractContainerEvent to CMI v8.0.4.2
org.bukkit.event.EventException
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:25) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.checkmodel.CMBlockContainer.getAccessResult(CMBlockContainer.java:34) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan.canAccessEvent(ItemCheckMan.java:168) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan.onPlayerInteract(ItemCheckMan.java:129) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan_47_onPlayerInteract_PlayerInteractEvent.invoke(Uranium) [?:?]
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:23) [EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:224) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:771) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176)
[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: net.minecraftforge.cauldron.block.CraftCustomContainer cannot be cast to org.bukkit.block.Chest
        at com.Zrips.CMI.AllListeners.silentChest.onPlayerInteract(silentChest.java:60) ~[?:?]
        at com.Zrips.CMI.AllListeners.silentChest_362_onPlayerInteract_PlayerInteractEvent.invoke(Uranium) ~[?:?]
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:23) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        ... 23 more
[06:50:06 ERROR]: Could not pass event PlayerInteractContainerEvent to CMI v8.0.4.2
org.bukkit.event.EventException
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:25) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.checkmodel.CMBlockContainer.getAccessResult(CMBlockContainer.java:34) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan.canAccessEvent(ItemCheckMan.java:168) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan.onPlayerInteract(ItemCheckMan.java:129) [MultiFunc_v1.2.01.jar:?]
        at cc.bukkitPlugin.multiFunc.model.itemcheck.ItemCheckMan_47_onPlayerInteract_PlayerInteractEvent.invoke(Uranium) [?:?]
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:23) [EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:224) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:771) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176)
[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: net.minecraftforge.cauldron.block.CraftCustomContainer cannot be cast to org.bukkit.block.Chest
        at com.Zrips.CMI.AllListeners.silentChest.onPlayerInteract(silentChest.java:60) ~[?:?]
        at com.Zrips.CMI.AllListeners.silentChest_362_onPlayerInteract_PlayerInteractEvent.invoke(Uranium) ~[?:?]
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:23) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        ... 23 more

**Cmi Version (using`/cmi version`):** 
 --------------------------------------------------
CMI plugin version: 8.0.4.2
 Server version: dev 1.7.10-R0.1-SNAPSHOT
 Vault version: 1.5.6-b49(CMIEInjector)
 --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Uranium（a core base on KCauldron and with some Thermos)
**Server Version (using `/ver`):** 
This server is running Uranium version 1710-dev-4-BUnkonwn (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by tmellen** [comment] 2018-08-06 14:47
The last two updates to CMI have done this for me too, so I'm still running 8.0.3.0.

This is what 8.0.4.3 does:
`[10:43:54 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.4.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_171]
        at com.Zrips.CMI.Modules.Alias.AliasManager.getAliasForCommand(AliasManager.java:123) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommandSpy(onPreprocessCommand.java:72) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        ... 16 more`

Even typing version gets me:

`>version
[10:47:06 ERROR]: Could not pass event ServerCommandEvent to CMI v8.0.4.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:511) [CMI8.0.4.3.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:107) [CMI8.0.4.3.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:75) [CMI8.0.4.3.jar:?]
        at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:67) [CMI8.0.4.3.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:439) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_171]
        at com.Zrips.CMI.Modules.Alias.AliasManager.getAliasForCommand(AliasManager.java:123) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        ... 20 more
[10:47:06 INFO]: --------------------------------------------------
[10:47:06 INFO]: CMI plugin version: 8.0.4.3
[10:47:06 INFO]: Server version: Spigot 1.12.2-R0.1-SNAPSHOT
[10:47:06 INFO]: Vault version: 1.6.10(+)
[10:47:06 INFO]: --------------------------------------------------`

**Comment by Zrips** [comment] 2018-09-30 12:39
This should be fixed in latest builds.

**Closed by Zrips** 2018-09-30 12:39 UTC
