### ISSUE TITLE
[Bug] Random Teleport max limit

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1870] opened 2019-06-01 20:16 UTC
**Description of issue:**

---
Random teleport (rt) awfully often places player on 1 or 2 of the max coords. It's not quite random anymore.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
none

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    world:
      Enabled: true
      MaxRange: 9500
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: false
      IgnoreLava: true
      minY: 50
      maxY: 160
```

---

**Cmi Version (using`/cmi version`):** 
8.6.4.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 1.13.2 build 627

**Comment by digitalcrowd** [comment] 2019-06-01 23:50
I have had the same issue.

**Comment by LogGits** [comment] 2019-06-20 08:09
Duplicate of #1777

**Closed by LogGits** 2019-06-20 08:09 UTC
Labels: bug report
