### ISSUE TITLE
Player Balance Limit and /pay Issue

### ISSUE THREAD

**Issue by BetaBurnt** [Zrips/CMI#4384] opened 2020-10-15 20:40 UTC
**Description of issue:**
Sending money to another player with /pay when their balance is at the cap set in the config.yml voids that money (the player sending it loses it, the player it was sent to can't have it so it just vanishes) rather than cancel/deny the payment.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: true
  # Set to true if you want to log money transfers between players
  LogEnabled: true
  log:
    Unknown: true
    Transfer: true
  # Determines max amount of cheque player can create
  # Set it to 0 to remove limit
  MaxChequeValue: 1.0E8
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: false
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: false
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
  Global:
    # Starting amount of money players will have
    StartingAmount: 1000.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 25000000
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 0.5
    # Defines if you want to allow payments with fractions
    # if this is disabled then payments will be limited to whole numbers and in case player provides number with fraction we will round number down
    Fractions: true
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: $
    # Format used for displaying money
    MoneyFormat: '###,###.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: false
    # Placing of currency symbol
    Placing: '[symbol][money]'
```

---

**Cmi Version (using`/cmi version`):**  CMI: 8.7.8.2 SqLite-> 8.7.8.4 (little out of date but nothing in the changelogs for the newer builds that suggest this would be fixed in them either - update pending for active server)

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** This server is running Paper version git-Paper-231 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** Using Vault 1.7.3 and CMIInjector 1.0.2.3

**Comment by CloudeLecaw** [comment] 2020-10-15 23:55
Why? You have a Cap that is setet up in config. Ita the max that players can have. If someone beeda more because he is at the cap. Then its your job to think about if you want to set the cap higher or not? Well but somthing on your economy seems to be inlatuate because the default cap from config is hard to reach, if reached this means all your players over cap are millarderes

**Comment by BetaBurnt** [comment] 2020-10-16 00:15
> Why? You have a Cap that is setet up in config. Ita the max that players can have. If someone beeda more because he is at the cap. Then its your job to think about if you want to set the cap higher or not? Well but somthing on your economy seems to be inlatuate because the default cap from config is hard to reach, if reached this means all your players over cap are millarderes...

Well that was a helpful response. 
What the cap is set to is not relevant - it's not uncommon to get to that with how my server works and that's not relevant to the issue.

If a player is at 24million and the cap is 25million, sending a payment with /pay of 2million should either not work because its more than they can take or the excess should be returned to the sender, not just voided.

**Comment by CloudeLecaw** [comment] 2020-10-16 05:11
If your server is Designed like that then the default cap is definitiv to low. Simoly set it higher (e11 for example and you will not run into this issues normaly.

**Comment by BetaBurnt** [comment] 2020-10-16 10:20
> Well so your server was designed to have max 24 Millionen? If so and players can pay high amounts like 2 Millionen then the default cap seems to be to low, Well that the reason why you can set it higher. You should calculate from the Beginning if its easy for your players to reach the default cap or not. For 99% of the servers here, the players never will reach it. You should change your config so a player never can reach the limit cap even if he play 20 years on your server. Well on our server the normal cap is enough and its nearly impossible for Players too ever be even a Millioennare so the default cap in config was enough. i think its enough for most servers (may not in your case) so simply set the limit higher. Or do you have a reason for limiting your players to the defined 24 Millionen? What if a player reaches them on your server, does the player had no opttion then anymore to make money? So he work for nothing because you forgot to higher the cap? Like i said, its not really a issues, you should take care that a player never reaches the limit if there is no reason to be limited..
> If your server is Designed like that then the default cap is definitiv to low. Simply set it higher (e11 for example and you will not run into this issues normaly.
> Finaly you can say: if a player reaches the cap then pay and fees to him went to the server ;D

Unless you're actually going to reply to what the actual problem is - please stop replying to the post. What the cap is set to is **not** relevant. It is at 25mil for a reason and does not need to be changed nor does changing the cap have any effect on the issue whatsoever.

As I said, more than once now, the issue is **specifically** that whatever the cap is set to you can send someone enough money to go over their cap and excess is destroyed rather than the payment either being cancelled entirely because of the cap or the excess amount that goes over their cap being sent back to the sender. Those are the two logical outcomes of having a cap sent and that situation happening - not the excess just being destroyed entirely.

**Comment by BetaBurnt** [comment] 2020-10-16 10:39
To reiterate as you're clearly ignoring what I have said the actual issue is:

If there is a limit set on player balances - regardless of what it is set to - you should not be able to /pay an amount to someone that would take their balance over the limit. Currently you can and the excess is just destroyed.
It shouldn't be that hard to make /pay check the recipients balance against the server limit and if what you're sending is greater than the difference - cancel the payment.

**Comment by Zrips** [comment] 2020-10-16 11:54
@BetaBurnt 
Confirmed, will be fixed with next update. Thanks for reporting this issue.

**Closed by Zrips** 2020-10-16 11:54 UTC
Labels: bug report

**Comment by BetaBurnt** [comment] 2020-10-16 11:56
Thank you Zrips!
