### ISSUE TITLE
Color codes don't translate in placeholder on cheques

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#4309] opened 2020-10-04 00:40 UTC
**Description of issue:**

Exactly as the title says. here's a picture:
https://prnt.sc/usoq1u

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  cheque:
    help:
      info: '&3Convert money into cheque'
      args: (playerName) [amount]
    info:
      transfered: '&3Transfered &6[amount] &3to your account. New balance: &6[balance]'
      chequeName: '&3Cheque for &6[amount]'
      chequeLore:
      - '&r&fIssued by &7[senderPrefix] [senderName]'
      - '&r&fRight click to deposit'
      holdPaper: '&3Hold paper in your hand'
      cantUse: '&3Can''t use this piece of paper. It is a cheque already!'
```

---

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-212 (1.16.3)

**Comment by CloudeLecaw** [comment] 2020-10-04 11:58
i cant agree you

![Snag_b26bf5e](https://user-images.githubusercontent.com/12080017/95014798-96f5c300-0649-11eb-8377-bf6ae49df64a.png)

looks fine..maybe an issue in your langfile?

**Comment by Insprill** [comment] 2020-10-04 12:51
You used hex, I'm using <1.16 color codes. And it returns everything correctly, it just doesn't translate the codes.

**Comment by CloudeLecaw** [comment] 2020-10-04 17:55
Insprill the hexed is just my Nickname its used with the hexed colors ;)

**Comment by Insprill** [comment] 2020-10-05 07:03
> Insprill the hexed is just my Nickname it's used with the hexed colors ;) This just means that the placeholder senderDisplayName works correct and shows my Nickname like it is

For me HEX codes or <1.16 codes in [prefix] or [senderPrefix] don't translate. Yes, colors are enabled. 


>Its not working on your check..means?.. right.....its not possible^^

Everything is working it's just the codes aren't getting translated into colors. It's not that it can't get the prefix.

**Comment by CloudeLecaw** [comment] 2020-10-05 07:48
The qustion is why your colorcodes are not translated. i see no difference in the colorcodes that i use these are also normal &colors you are using

**Comment by Zrips** [comment] 2021-02-16 13:36
This could have been caused by your permission plugin providing raw prefix instead of translated one. Should be resolved with next update if it wasn't resolved from your permission plugin side.

**Closed by Zrips** 2021-02-16 13:36 UTC
Labels: bug report
