### ISSUE TITLE
CMI's scavenge have some dangerouse bugs.

### ISSUE THREAD

**Issue by d0nghan** [Zrips/CMI#3374] opened 2020-05-24 06:02 UTC
**Description of issue or feature request:**

---
CMI's scavenge have a lot of bugs.
if i put 'stained_glass', it give us Maximum '8 - glass', and if I put 'Iron_ingot', it give us 'iron_pickaxe (durablity is -32517)

---

**Cmi Version (using`/cmi version`):8.6.24.4

**Server Type (/Paperspigot/):Paperspigot

**Server Version (using `/ver`): 1.15.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment] 2020-05-24 09:32
You might have some strange custom recipes set for iron_ingots. Stained glass can return up to 8 glass, because recipe contains up to 8 glass.

**Comment by Zrips** [comment] 2020-05-25 09:46
Ok, confirmed and will be fixed

**Closed by Zrips** 2020-05-25 09:46 UTC
Labels: unconfirmed
