### ISSUE TITLE
CMI monitoring the chat bar causes the game to freeze (every player will get stuck)

### ISSUE THREAD

**Issue by vlssu** [Zrips/CMI#6040] opened 2021-08-17 02:13 UTC
This is a very strange thing. Before 1.17, including 1.16 and previous versions, such problems will not occur.
For this problem, I didn't see the error log in the terminal, so I couldn't provide an error report.
But I am very anxious to fix this problem, which will lead to a very bad player experience, even if the computer configuration is high, it will be stuck. This situation is particularly obvious when the number of people is more than 8.

![image](https://user-images.githubusercontent.com/43847794/129653226-0333f9c2-f995-4d77-8af8-73e14d8f8afd.png)

**Comment by Zrips** [comment] 2021-08-25 14:56
This isint enough to determine what is the cause or even if its caused by CMI in general. Can you explain what exactly you mean by "chat bar monitoring"?

**Comment by vlssu** [comment] 2021-08-25 15:43
That is, the player executes the command "tpa" on the client, and the other party can click OK or reject to save the process of inputting the command, but it may not be for these reasons. I am not very clear about the specific reasons. My friend restarted on his computer. The server and all the plug-ins are all reconfigured, but there is still a lag problem, even though it is 1.16.5, so I think it may be caused by these problems in the new version of cmi, but it may also be a problem with minecraft itself.

**Comment by Zrips** [comment] 2021-09-09 14:22
Purpur isint officially supported and without more information i cant debug this or even determine if issue comes from CMI. Closing ticket for now.

**Closed by Zrips** 2021-09-09 14:22 UTC
Labels: question
