### ISSUE TITLE
[1.15 Bees] Users can change spawner type.

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#2614] opened 2020-01-04 00:58 UTC
Hi im using 8.6.16.5.

In my config i use the option so that players need permission to change spawner types. but still they are able to do it.

We tested it with bee eggs. I Saw another user reported this. NOt sure if other eggs are affected too.

@Zrips 
can you please fix it? its important to us.

**Comment by mrfloris** [comment] 2020-01-04 09:42
```
  Interact:
    # When set to true, players trying to change spawner with monster egg will require appropriate permission node
    # In example: player should have cmi.egginteract.pig to change spawner into pig, or cmi.egginteract.zombie to change into zombie spawner
    EggRequiresPermission: true
```
This is what I have in my `config.yml` from cmi.
And I have not given the players any cmi.egginteract permissions, because I do not want them to change spawner types. 

I've just checked on the latest spigot 1.15.1 build and latest available cmi on spigotmc, and they still cannot interact with cows or zombies or other spawn eggs, but the bee changes the spawner type to bee, using bee spawnegg. 

I think it's fair to assume CMI needs to update to make sure it checks against all 1.15.1 available mob types valid for a spawner. 

I can reproduce what you're saying.

```
>cmi version
[10:41:47] [Server thread/INFO]: --------------------------------------------------
[10:41:47] [Server thread/INFO]: CMI plugin version: 8.6.16.5
[10:41:47] [Server thread/INFO]: Server version: Spigot 1.15.1-R0.1-SNAPSHOT
[10:41:47] [Server thread/INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[10:41:47] [Server thread/INFO]: --------------------------------------------------
>
```

**Comment by mrfloris** [comment] 2020-01-04 09:46
Duplicate of https://github.com/Zrips/CMI/issues/2585

**Comment by ScuroK** [comment] 2020-01-09 19:23
@Zrips could you fix it pls?

**Comment by Zrips** [comment] 2020-01-12 12:31
Will be fixed with todays update

**Closed by Zrips** 2020-01-12 12:31 UTC
Labels: bug report
