### ISSUE TITLE
/glow not working

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#54] opened 2018-02-27 19:23 UTC
Hey there, cant seem to get /glow to show colors

Tried with cmi.command.glow.red and cmi.command.glow.* . Could not get any color other than the default white to show up. 

1.12.2 - no errors in console

**Comment by LogGits** [comment] 2018-02-28 11:46
Did you try `/cmi glow red` or `/cmi glow blue`?

**Comment by Kbryst** [comment] 2018-02-28 16:47
Yes I tried both

**Comment by LogGits** [comment] 2018-03-01 11:28
As Op does it let you use the command also what version of CMI and Spigot/paperspigot are you using (plz specify if its paper or just regular spigot)?

**Comment by Kbryst** [comment] 2018-03-01 22:00
Op can use the command but the glow wont change color. I’m on the current cmi from spigot and we are on paperspigot. I’m at work right now I can’t check the exact versions but it shouldn’t be too far behind

**Comment by LogGits** [comment] 2018-03-02 11:20
Okie i tested this issue (I am on the latest version of CMI and PaperSpigot and not opped).

I have these permissions `cmi.command.glow` and `cmi.command.glow`. You must use the command like `/cmi glow red` or `/glow red`. 

I also tested this with another user on my server to try and reproduce the issue, however, it is functioning as intended.

**Comment by Kbryst** [comment] 2018-03-02 16:12
I'm thinking the pvp manager is conflicting because it has a glow effect on pvp tag. Just odd I expected to see an error from it.

Thanks so much for testing for me, sorry I wasted your time a bit.

**Comment by LogGits** [comment] 2018-03-03 12:56
Oddly enough I have tested this with the premium version of pvpmanager and i still cant reproduce. Have you tested this with only cmi in your plugin folder to test if its actually the cause? Try using CMI (latest build of course) and then if the issue doesn't occur, start adding in plugins. If you think pvpmanager could be causing it, put it in the plugins folder and restart. If you can find a way to reproduce this there is a higher likelihood that it will be fixed 🙂

**Comment by Kbryst** [comment] 2018-03-05 19:25
Its featherboard (which requires MVdWPlaceholderAPI)

**Comment by LogGits** [comment] 2018-03-05 22:09
> Its featherboard (which requires MVdWPlaceholderAPI)

Ah ok, I am closing this for now. Let us know if the issue with featherboard gets resolved 🙂

**Comment by Kbryst** [comment] 2018-03-05 23:25
I can't get it resolved with them, the issue is on CMI's end because CMI does not use packets or something.

https://www.spigotmc.org/threads/featherboard-paid.41341/page-224#post-2916077

Discussion for that plugin.

**Comment by 0xC1A551C** [comment] 2018-03-10 23:05
I can verify glow works for me on the latest cmi version, but the colors do not work. The glow effect is still white for me while the chat says the color

**Comment by Kbryst** [comment] 2018-03-11 02:09
That is exactly what happens to me. Do you have featherboard by chance?

**Comment by Kbryst** [comment] 2018-03-27 18:25
Is there any update on this by chance?

**Comment by Zrips** [comment] 2018-04-08 14:52
@Kbryst Not currently, i need to remake bunch of stuff and make centralised engine to handle stuff like this throw packets and avoid usage of scoreboards to have normal support with 3rd party plugins

**Comment by CloudeLecaw** [comment] 2018-04-24 06:35
cmi.command.glow is not enought….

example for blue:
**- cmi.command
- cmi.command.glow
- cmi.command.glow.blue**

![image](https://user-images.githubusercontent.com/12080017/39170057-5f33ebc4-479a-11e8-9dd4-4833153ac32d.png)

**Comment by Kbryst** [comment] 2018-04-24 16:16
@CloudeLecaw I don't understand why you are posting now. We have already determined it is the plugin FEATHERBOARD that is causing the issue. I'm sorry I know you are trying to be helpful but none of that helped lol.

**Comment by CloudeLecaw** [comment] 2018-04-24 19:16
hmm then may disable Featherboard or close it when we have the answer now what is causing it :D

**Comment by Zrips** [comment] 2018-06-22 13:08
This is deprecated issue as of new glow handling.

**Closed by Zrips** 2018-06-22 13:08 UTC
Labels: bug report

**Comment by subhxer** [comment] 2024-11-01 01:23
im having the same problem what do i do i can share you my plugins screenshot
![image_2024-11-01_065114120](https://github.com/user-attachments/assets/4e72a5ea-61b1-496b-938d-9b3ea1d8d7a9)
