### ISSUE TITLE
cmi silentchest do not apply to user after join server

### ISSUE THREAD

**Issue by Qveshn** [Zrips/CMI#3424] opened 2020-05-31 07:04 UTC
CMI8.6.26.6.jar

I use "/cmi silentchest" to turn silent mode on. All works
But after leave and join server again chests begin opening without silent.
But cmi remembers that it is still silent mode for me now: when I type "/cmi silentchest" it shows me that silent mode now is turned off (it means that it was on before).

Also, tell me please where this silent mode flag is saved (database or somewhere in world/playerdata)?

**Comment by CloudeLecaw** [comment] 2020-05-31 16:48
wat your telling just means you disable your silten cestmode onlogin.

What your a re telling is just a prevention for staff and members to not let this on forever^^

all works fine - no bug

**Comment by Qveshn** [comment] 2020-06-01 01:34
Look!

1. join the server
2. type: /cmi silentchest
>> You toggled silent chest mode to True.
3. Open chest. all works fine. The chest is opened in silent mode (chest cover is not opened and chest inventory is showed)
4. Leave and join server again
5. Open chest. BUG! Chest is opened without silent mode (I see chest cover opened)
6. type again: /cmi silentchest
>> You toggled silent chest mode to False.
This message means that it was turned from TRUE to FALSE state. And this means that before this command silent mode was ON. 
But if silent mode was ON, why chest cover was opened?
Expected silent mode!

**Comment by CloudeLecaw** [comment] 2020-06-01 09:39
this just means this kind of prvention does not work anymore.

by the way - if you use this command the first time it also tells you it was "false" what would mean it was true before? ;)

So the Problem is not that its toggled off on logout that is wanted.
The problem is the value in database is not changed on logout to false.

The value in database does only change on /cmi silentchest but not on logout.
but as long this error is simply use /cmi silentchest twice when u forgot to turn it off before login ;)

**Comment by Zrips** [comment] 2020-06-02 12:58
Will be fixed with next version

**Closed by Zrips** 2020-06-02 12:58 UTC
Labels: bug report
