### ISSUE TITLE
DiscordSRV still broken

### ISSUE THREAD

**Issue by QueenAngus** [Zrips/CMI#1837] opened 2019-05-27 02:33 UTC
**Description of issue or feature request:**
I am using the latest version of CMI, and it breaks chat from MC to discord. It still sends messages like server starts and stops. Removing CMI allows chat again and adding it back breaks it. DiscordSRV enabled aswell as click hover messages.

Here are my chat settings in config.yml: https://pastebin.com/Bf6rJnQX

I have removed every other plugin from my server and the issue is still occuring, making me think this must be a conflict between DiscordSRV and CMI as they are the only plugins still running. This makes me believe there isn't another plugin causing a conflict and it would be CMI.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
Latest
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):** 
CMI, DiscordSRV

**Comment by TheWranger** [comment] 2019-06-02 06:25
You can close this issue, it's been broken for awhile now, https://github.com/Zrips/CMI/issues/391

**Comment by TwinPeaksGaming** [comment] 2019-06-05 05:43
Just leaving this here in case it helps people:

Open DiscordSRV config, change line 23:

RespectChatPlugins: true to RespectChatPlugins: false

Chat will function correctly now.

Temporary fix until author fixes.

**Comment by Vankka** [comment] 2019-11-03 12:25
Never disable `RespectChatPlugins`, it is intended for debugging purposes only.

Duplicate of #391 (also includes a proper solution without disabling RespectChatPlugins)

**Closed** 2020-07-01 15:24 UTC
