### ISSUE TITLE
Writing on signs doesn't work

### ISSUE THREAD

**Issue by Morloxz** [Zrips/CMI#7895] opened 2023-06-18 13:12 UTC
### Description of Issue

Hi, players can't write on the signs, only player with OP rights can write on the signs, but classic player when he writes something the text disappears and the sign is empty.

### Version Information

```shell
CMI-9.6.0.4
CMILib1.3.0.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by PovilasLT** [comment] 2023-06-18 14:56
Duplicate of #7892 , players with cmi.signs.shiftedit can write signs as normal.

**Comment by Morloxz** [comment] 2023-06-18 15:29
> 

That's not true, in luckperms this value is set for all players, but the text doesn't stay there, even when editing.

**Comment by CloudeLecaw** [comment] 2023-06-18 19:07
You need to enable it in cmi Options to be able to write on Signs then you can write on them aggain

its a bug and needs to be fixed

**Comment by Morloxz** [comment] 2023-06-18 19:09
> You need to enable it in cmi Options to be able to write on Signs then you can write on them aggain
> 
> ![image](https://user-images.githubusercontent.com/12080017/246684986-1b66c065-cfc9-42b9-936b-e98961e42639.png)
> 
> its a bug and needs to be fixed
> 
> For a current solution you can allow all players to use SHIFT+Edit the sign for all in default options and enable it if you disabled it for you..

Where can I find gui?

**Comment by CloudeLecaw** [comment] 2023-06-18 19:10
use /cmi options

**Comment by Morloxz** [comment] 2023-06-18 19:12
> 

Okay, thank you

**Comment by Morloxz** [comment] 2023-06-18 19:32
> 

It's on, players have permissions and still the text disappears.

**Comment by CloudeLecaw** [comment] 2023-06-18 21:08
then need to turn it on

**Comment by Dyvinia** [comment] 2023-06-18 21:10
is there a way to prevent cmi from having to do anything with signs? i just want it to be handled vanilla

**Comment by CloudeLecaw** [comment] 2023-06-18 21:15
https://streamable.com/c90hu2

**Comment by mrfloris** [comment] 2023-06-18 21:23
> Duplicate of #7892 , players with cmi.signs.shiftedit can write signs as normal.

it also depends if the sign and side is empty or not and has been recently edited, etc. There's so many situations where it breaks in one paper build, and it's fine in another, but the UI + done, ;.. that's just not working, regardless of permissions as there's no event in the API to use.

**Comment by Dyvinia** [comment] 2023-06-18 21:26
even while opped and with the permission, I cannot edit signs. cmi is an important plugin in servers i do, and ive used it for 3+ years now, but the sign issue is making me consider just switching to essentials or something

**Comment by CloudeLecaw** [comment] 2023-06-18 21:40
https://streamable.com/c90hu2

**Comment by CloudeLecaw** [comment] 2023-06-18 21:41
> even while opped and with the permission, I cannot edit signs. cmi is an important plugin in servers i do, and ive used it for 3+ years now, but the sign issue is making me consider just switching to essentials or something

take alook here
https://streamable.com/c90hu2

**Comment by mrfloris** [comment] 2023-06-18 21:49
> even while opped and with the permission, I cannot edit signs. cmi is an important plugin in servers i do, and ive used it for 3+ years now, but the sign issue is making me consider just switching to essentials or something

You can switch to another plugin, but it will have the same issue. This isn't a cmi issue, this is a consequence to the cmi plugin and many others that have to deal with the bukkit API not having the stuff it needs to have to keep doing things the same in 1.20 as in 1.19, due to mojang's bigger changes to the signs. 

You just have to wait like everybody else for the API to update, so CMI can make the appropriate changes. 

Paper 1.20.1 latest build and latest cmi/cmilib, signs as operators etc works, for editing - I have a 11 minute video of trying stuff out. 

BUt there are enough situations like DSIGN feature issues and random right clicks that do work for interaction with elevator signs or other `[ic:whatever]`, and a bunch of other little issues. 

these have mostly been reported to spigot by some devs, including 2 tickets by zrips. 

https://youtu.be/y4sTB5ZOYPs

**Comment by Zrips** [comment] 2023-06-22 13:11
Will be fixed with next update.

**Closed by Zrips** 2023-06-22 13:11 UTC
Labels: bug report
