### ISSUE TITLE
On Death Console Warn

### ISSUE THREAD

**Issue by LucidusMC** [Zrips/CMI#1752] opened 2019-05-14 06:40 UTC
On players death, console posts the following warning (over and over).

**ERROR:**
[23:30:37 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.DedicatedPlayerList.moveToWorld(net.minecraft.server.v1_13_R2.EntityPlayer, org.bukkit.craftbukkit.v1_13_R2.CraftServer$3, boolean)
[23:30:37 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[23:30:37 WARN]:        at com.Zrips.CMI.Reflections.respawn(Reflections.java:1150)
[23:30:37 WARN]:        at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1684)
[23:30:37 WARN]:        at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:211)
[23:30:37 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[23:30:37 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[23:30:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[23:30:37 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[23:30:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[23:30:37 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[23:30:37 WARN]:        at java.lang.Thread.run(Thread.java:748)

Versions:
CMI plugin version: 8.6.1.5
Server version: Paper(624) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.2-b107

**Comment by Zrips** [comment] 2019-05-14 09:12
Tested with same paper version and same CMI version, could not reproduce issue. Did you updated something lately what could be causing this issue? And you could remove/negate cmi.autorespawn to prevent this messages appearing. But until i can reproduce this one, i cant really fix it. Error is not harmful by itself, you only loosing auto respawn feature.

**Comment by LucidusMC** [comment] 2019-05-14 13:20
Thank you, no issue with it really, just wanted to report it just in case. Appreciate your feedback.

**Comment by Zrips** [comment] 2019-05-14 14:03
Will close this one for time being, if you will encounter this issue again, try testing it without any other plugin except CMI to make sure that we dont have something interfering.

**Closed by Zrips** 2019-05-14 14:03 UTC
