### ISSUE TITLE
AFK Bug

### ISSUE THREAD

**Issue by S4IVin** [Zrips/CMI#5674] opened 2021-06-07 09:52 UTC
**Description of issue:**
When I walk just after the / afk command, I don't exit AFK mode, please watch the video to understand better
---

**CONFIG SECTION:**
```
Afk:
  # Enable or disable auto afk system entirely
  Enabled: true
  # When enabled shows title message informing that player is in afk mode
  TitleMessage: true
  # When enabled shows random subtitle message
  SubTitleMessage: true
  # Prevents jumping in one place to avoid afk status
  PreventJumping: true
  # Prevents damage while afk
  PreventDamage: true
  # Defines how often in seconds plugin will check for afk players state
  CheckInterval: 1
  # When set to true, players playtime counter stops
  # As of nature how this system works you can see +-1second jumping up and down while checking players playtime
  StopPlayTime: true
  # Defines how long to wait after player stops moving to set him as afk
  # Player needs to have cmi.command.afk.auto permission node
  # Set to 0 if you want to disable it
  AutoAfkIn: 300
  # Defines commands to be performed when player enters afk mode automatically while addling
  # Supports specialized commands
  AutoAfkCmds:
  - cmi broadcast !&7&lMine&b&lCore &8» &b[playerDisplayName] &fè andato AFK.
  # Defines commands to be performed when player enters /cmi afk
  # Supports specialized commands
  ManualAfkCmds:
  - cmi broadcast !&7&lMine&b&lCore &8» &b[playerDisplayName] &fè andato AFK.
  # Defines commands to be performed when player leaves afk mode
  AfkLeaveCmds:
  - cmi broadcast !&7&lMine&b&lCore &8» &b[playerDisplayName] &fnon è più AFK.
  # Defines how long to wait after player stops moving to kick player
  # This is additional timer to AutoAfkIn and in case player entered afk mode manually he will get kicked after AutoAfkIn+AutoKickIn seconds
  # This can be used not only to kick but to perform repeating action every x seconds if needed
  # Keep it at -1 to disable auto kick
  # Can be bypassed with cmi.command.afk.kickbypass permission node
  # Additionally players kick time can be changed with cmi.command.afk.kickOutIn.[seconds] permission node where bigger value takes priority
  AutoKickIn: -1
  # This will define how long to wait before performing kick commands again
  RepeatingAutoKickInterval: 300
  # When set to true, kick command will be repeated each RepeatingAutoKickInterval seconds
  RepeatKickCommand: false
  # Defines commands to be performed when player can be kicked
  # If player is not kicked then commands will be repeated every RepeatingAutoKickInterval seconds
  AutoKickCmds:
  - A
  # Defines worlds where players will not be placed into afk mode after they idled for defined time
  DisabledWorlds:
  - A
  # Disables afk on interaction
  DisableOnInteract: true
  # Prevents player from going bypassing afk mode while continuously holding one button with particular items or on particular blocks
  SmartInteractCheck: true
  # Prevents from players abusing afk by constantly moving in afk machine
  AntiAfkMachines: true
  # EXPERIMENTAL! Prevents players from being pushed around while player is in afk mode
  # Keep in mind that player can still be moved around the same block he is in
  PreventPushing: false
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on item drop
  DisableOnitemDrop: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables afk on fishing
  DisableFishing: false
  # Disables item pickup while afk
  DisableItemPickup: false
  PreventMobSpawning:
    # When enabled we can prevent mob spawning near players who are afk
    Enabled: false
    # Prevents natural mob spawning
    # This can be more on heavy side of the server as it will try constantly to spawn in monsters near afk players
    Natural: false
    # Prevent mob spawning from spawners
    Spawners: false
    # Usually responsible for spawning in iron golems
    VillageDefence: false
  # Disables exp pickup while afk
  # Attention! Because of weird minecraft handling of exp orbs, best way is to set orb to 0exp and allow it to be obsorbed
  # So by enabling this exp obsorbed by afk players will have no effect
  DisableExpPickup: false
```

---

**Cmi Version (using`/cmi version`):** 8.8.4.8

**Server Type (Spigot/Paperspigot/etc):**  PaperSpigot

**Server Version (using `/ver`):** 1.8.8

https://user-images.githubusercontent.com/67902218/120996670-d2bbcc00-c786-11eb-969e-8727a40488ab.mp4

**Comment by EkonC** [comment] 2021-06-07 18:36
DisableOnMove probably isn't working.

**Comment by Zrips** [comment] 2021-06-08 15:32
This is actually SmartInteractCheck where we are trying to detect players in afk machines, which usually is player moving to one direction without moving camera around. Afk does get toggled off when you move your camera around and move around. Not a bug in particular, i might need to improve on this to  have less false positive.

**Closed by Zrips** 2021-06-08 15:32 UTC
Labels: bug report
