### ISSUE TITLE
I use kits system have some BUG!!

### ISSUE THREAD

**Issue by qwer2415wy** [Zrips/CMI#4108] opened 2020-08-29 07:12 UTC
**Description of issue:**
I type in Conditions and then it will be use on Description

Viedo:
[https://youtu.be/AkPn6eu_34Y](https://youtu.be/AkPn6eu_34Y)
---
---

**Cmi Version (using`/cmi version`):8.7.6.9** 

**Server Type (Spigot/Paperspigot/etc):Paperspigot** 

**Server Version (using `/ver`):git-Paper-148 (MC: 1.16.2)**

**Comment by CloudeLecaw** [comment] 2020-08-29 09:57
Great catch 🤣

**Comment by CloudeLecaw** [comment] 2020-08-29 09:59
Can you check your langfile in the section for kitseditor to see if its not currpted? Just asking because we had an issues with the Lang file some Version ago, maybe your langfile is also effected...

**Comment by qwer2415wy** [comment] 2020-08-29 10:16
What did you mean , you mean another more bug about kitseditor?

**Comment by qwer2415wy** [comment] 2020-08-29 10:18
![2020-08-29_18 17 44](https://user-images.githubusercontent.com/70427269/91634584-f8f85280-ea23-11ea-9888-b8414396cefb.png)
This enable is not useful it will go to setting page not got to enable/disable

**Comment by CloudeLecaw** [comment] 2020-08-29 18:38
No i mean the language file if CMI your using
currped version:

```
```
  kitcdreset:
    info:
      notCd: '&eKit is not in cooldown stage'
      reset: '&eKit (&6[kit]&e) cooldown got reset for &6[playerDisplayName]'
      resetAll: '&eKit (&6[kit]&e) cooldown got reset for &6[count] &eplayers'
      list: '&e[place]. &6[kit] &e[time]'
      listHover: '&eClick to reset'
      noCd: '&eThere are no kit''s on cooldown'
      command:
        kiteditor:
          help:
            info: '&eKit editor.'
            args: ''
            explanation:
            - '&ePermissions:'
            - '&6cmi.kit.[kitName] &e- allows to use particular kit'
            - '&6cmi.kit.bypass.money &e- bypass money requirement'
            - '&6cmi.kit.bypass.exp &e- bypass exp requirement'
            - '&6/cmi kiteditor &e- shows kit list'
  kiteditor:
    info:
      kits: '&eKits: '
      iconSet: '&eNew icon set for &6[kitname] &ekit'
      kitExists: '&eKit with this name already exist!'
      deleteConfirm: '&eClick me if you really want to remove (&6[kitname]&e) kit!'
      deleteConfirmFinal: '&cThis action is not reversible!'
      kitRemoved: '&eKit (&6[kitname]&e) removed'
      kitNotRemoved: '&cKit (&6[kitname]&c) could not be removed'
      addNewInfo: '&eType kit name into chat and press enter. Type ''&6cancel&e''
        to cancel this action.'
      renameCommandInfo: '&eType new kit &6command &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      renameConfigInfo: '&eType new kit &6config &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      groupInfo: '&eType new group name into chat and press enter. Type ''&6none&e''
        to remove group. Type ''&6cancel&e'' to cancel this action.'
      commandInfo: '&eType new command into chat and press enter. Type ''&6cancel&e''
        to cancel this action. Possible placeholders: &6{USERNAME} {DISPLAYNAME} {WORLDNAME}
        {KITNAME} {RANDOMPLAYER}'
      conditionsInfo: '&eType new required permission node into chat and press enter.
        Type ''&6cancel&e'' to cancel this action'
      descInfo: '&eType new description into chat and press enter. Type ''&6cancel&e''
        to cancel this action'
      renamed: '&eRenamed &6[kitname] &eto &6[newkitname]&e.'
      groupSet: '&eNew group (&6[groupname]&e) set for &6[kitname]'
      commandsListTitle: '&e✎&6Commands:'
      conditionsListTitle: '&e✎&6Conditions:'
      descListTitle: '&e✎&6Description:'
      ListTitleHover: '&eClick to open GUI'
      ListEditKitHover: '&cEdit &6[kitname]'
      ListAdd: ' &2+'
      ListAddHover: '&2Add new'
      guiClickery:
      - '&eLeft mouse click to increase and right click to decrease'
      - '&eHold &6Shift &eto speed process by 10 times'
      - '&eRepeating fast clicks will speed amount change'
      - '&eStop clicking for 1 sec to go back to default amount'
      OffHand: '&ePlace offHand item over here'
      Helmet: '&ePlace helmet item over here'
      Chest: '&ePlace chest item over here'
      Legs: '&ePlace leggings over here'
      Boots: '&ePlace boots over here'
      Weight: '&eWeight: &6[Weight]'
      WeightExtra:
      - '&eHigher value have bigger priority'
      - '&eKits should be in same group'
      despiteWeight: '&eShow despite weight: &6[Weight]'
      despiteWeightExtra:
      - '&ePLayer is not getting access to kit, but can preview it'
      Slot: '&eSlot: &6[slot]'
      SlotAuto: '&6Auto'
      Clone: '&eClone items from inventory'
      CloneExtra:
      - '&eUse right mouse button to include armors'
      - '&eClick again to revert changes'
      timeDelay: '&eDelay: &6[time]'
      usages: '&eCan be used for &6[times] &etimes'
      usagesUnlimited: '&6Unlimited'
      ignoreWeight: '&eShow despite weight: &6[state]'
      timeDelaySeconds: '&eIn seconds: &6[time]'
      moneyCost: '&eMoney cost: [cost]'
      expCost: '&eExp cost: [cost]'
      enabled: '&eEnabled'
      disabled: '&6Disabled'
      delete: '&6Delete kit'
      clickToSwitch: '&eClick to switch state'
      clickToEdit: '&eClick to start editing'
      editConfigName:
      - '&eClick to rename config name'
      - '&eThis only determines permission node'
      editCommandName:
      - '&eClick to rename command name'
      - '&eThis sets command you need to use to get this kit'
      displayName: '&7DisplayName: &r&f[name]'
      editDisplayName:
      - '&eClick to change display name'
      - '&eThis only used for visual purposes'
      kitGroup: '&eKit group: &6[group]'
      dropItems: '&eDrop item if full: &6[state]'
      commands: '&eCommands:'
      conditions: '&eConditions:'
      desc: '&eDescription:'
      mainMenu: '&eMainMenu'
      settings: '&eSettings'
      icon: '&eIcon used when kit is &2available'
      iconCd: '&eIcon used when kit is &cunavailable'
      command:
        kitusagereset:
          help:
            info: '&eReset kit usage counter'
            args: (kitName) (playerName)
```

not currpted version:
  kiteditor:
    help:
      info: '&eKit editor.'
      args: ''
      explanation:
      - '&ePermissions:'
      - '&6cmi.kit.[kitName] &e- allows to use particular kit'
      - '&6cmi.kit.bypass.money &e- bypass money requirement'
      - '&6cmi.kit.bypass.exp &e- bypass exp requirement'
      - '&6/cmi kiteditor &e- shows kit list'
    info:
      kits: '&eKits: '
      iconSet: '&eNew icon set for &6[kitname] &ekit'
      kitExists: '&eKit with this name already exist!'
      deleteConfirm: '&eClick me if you really want to remove (&6[kitname]&e) kit!'
      deleteConfirmFinal: '&cThis action is not reversible!'
      kitRemoved: '&eKit (&6[kitname]&e) removed'
      kitNotRemoved: '&cKit (&6[kitname]&c) could not be removed'
      addNewInfo: '&eType kit name into chat and press enter. Type ''&6cancel&e''
        to cancel this action.'
      renameCommandInfo: '&eType new kit &6command &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      renameConfigInfo: '&eType new kit &6config &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      groupInfo: '&eType new group name into chat and press enter. Type ''&6none&e''
        to remove group. Type ''&6cancel&e'' to cancel this action.'
      commandInfo: '&eType new command into chat and press enter. Type ''&6cancel&e''
        to cancel this action. Possible placeholders: &6{USERNAME} {DISPLAYNAME} {WORLDNAME}
        {KITNAME} {RANDOMPLAYER}'
      conditionsInfo: '&eType new required permission node into chat and press enter.
        Type ''&6cancel&e'' to cancel this action'
      descInfo: '&eType new description into chat and press enter. Type ''&6cancel&e''
        to cancel this action'
      renamed: '&eRenamed &6[kitname] &eto &6[newkitname]&e.'
      groupSet: '&eNew group (&6[groupname]&e) set for &6[kitname]'
      commandsListTitle: '&e✎&6Commands:'
      conditionsListTitle: '&e✎&6Conditions:'
      descListTitle: '&e✎&6Description:'
      ListTitleHover: '&eClick to open GUI'
      ListEditKitHover: '&cEdit &6[kitname]'
      ListAdd: ' &2+'
      ListAddHover: '&2Add new'
      guiClickery:
      - '&eLeft mouse click to increase and right click to decrease'
      - '&eHold &6Shift &eto speed process by 10 times'
      - '&eRepeating fast clicks will speed amount change'
      - '&eStop clicking for 1 sec to go back to default amount'
      OffHand: '&ePlace offHand item over here'
      Helmet: '&ePlace helmet item over here'
      Chest: '&ePlace chest item over here'
      Legs: '&ePlace leggings over here'
      Boots: '&ePlace boots over here'
      Weight: '&eWeight: &6[Weight]'
      WeightExtra:
      - '&eHigher value have bigger priority'
      - '&eKits should be in same group'
      despiteWeight: '&eShow despite weight: &6[Weight]'
      despiteWeightExtra:
      - '&ePLayer is not getting access to kit, but can preview it'
      Slot: '&eSlot: &6[slot]'
      SlotAuto: '&6Auto'
      Clone: '&eClone items from inventory'
      CloneExtra:
      - '&eUse right mouse button to include armors'
      - '&eClick again to revert changes'
      timeDelay: '&eDelay: &6[time]'
      usages: '&eCan be used for &6[times] &etimes'
      usagesUnlimited: '&6Unlimited'
      ignoreWeight: '&eShow despite weight: &6[state]'
      timeDelaySeconds: '&eIn seconds: &6[time]'
      moneyCost: '&eMoney cost: [cost]'
      expCost: '&eExp cost: [cost]'
      enabled: '&eEnabled'
      disabled: '&6Disabled'
      delete: '&6Delete kit'
      clickToSwitch: '&eClick to switch state'
      clickToEdit: '&eClick to start editing'
      editConfigName:
      - '&eClick to rename config name'
      - '&eThis only determines permission node'
      editCommandName:
      - '&eClick to rename command name'
      - '&eThis sets command you need to use to get this kit'
      displayName: '&7DisplayName: &r&f[name]'
      editDisplayName:
      - '&eClick to change display name'
      - '&eThis only used for visual purposes'
      kitGroup: '&eKit group: &6[group]'
      dropItems: '&eDrop item if full: &6[state]'
      commands: '&eCommands:'
      conditions: '&eConditions:'
      desc: '&eDescription:'
      mainMenu: '&eMainMenu'
      settings: '&eSettings'
      icon: '&eIcon used when kit is &2available'
      iconCd: '&eIcon used when kit is &cunavailable'
```

**Comment by qwer2415wy** [comment] 2020-08-30 00:12
Is use not currpted version I want to delete lang file?

**Comment by qwer2415wy** [comment] 2020-08-30 01:08
Your lang currped like this:
```
  kit:
    help:
      info: '&eGives predefined kit.'
      args: '[kitName] (playerName)'
      explanation:
      - '&ePermissions:'
      - '&6cmi.kit.[kitName] &e- allows to use particular kit'
      - '&6cmi.kit.bypass.money &e- bypass money requirement'
      - '&6cmi.kit.bypass.exp &e- bypass exp requirement'
      - '&6cmi.kit.bypass.onetimeuse &e- bypass one time use'
      - '&6/cmi kit [kitName] [playerName] &e- will give kit to another player'
    info:
      noMoney: '&eNot enough money. Cost: &6[cost] &eyou have &6[balance]'
      noExp: '&eNot enough exp. Cost: &6[cost] &eyou have &6[balance]'
      noCondition: '&eYou dont have special condition permission to use this kit:
        &6[condition]'
      oneTime: '&cThis is a one time use kit and you have already used it!'
      cantUseNow: '&cYou can''t use this kit for the next [time]'
      limitedTimeUseError: '&eCan''t use more than &6[times] &etimes'
      limitedTimeUse: '&7Can use for &c[times] &7times'
      limitedTimeAllUsed: '&cYou can''t get another one'
      canUseIn: "&eCan use again in: \n[time]"
      cooldown: "&eCooldown: \n[time]"
      noKit: '&eCan''t find kit by this name'
      kitDoesntExist: '&eCan''t find kit ([kitName])'
      noKitAccess: '&cYou don''t have access to this kit'
      noFoundKit: '&eCan''t find any kits'
      givenKit: '&eYou have given &6[kit] &eto &6[playerDisplayName]'
      title: '&8Kits'
      nameCanUse: '&6[kitName]'
      nameCantUse: '&7[kitName]'
      group: '&eGroup: &6[group]'
      left: '&6Left &eclick to claim'
      right: '&6Right &eclick to preview'
      take: '&6Take this kit!'
      eye: ' &e☬'
      use: '&2'
      cantuse: '&7'
      list: '&7[number]. &e[kitName] &6- [description]'
  kitcdreset:
    help:
      info: '&eReset kit timer'
      args: (kitName) (playerName/all)
    info:
      notCd: '&eKit is not in cooldown stage'
      reset: '&eKit (&6[kit]&e) cooldown got reset for &6[playerDisplayName]'
      resetAll: '&eKit (&6[kit]&e) cooldown got reset for &6[count] &eplayers'
      list: '&e[place]. &6[kit] &e[time]'
      listHover: '&eClick to reset'
      noCd: '&eThere are no kit''s on cooldown'
  kiteditor:
    help:
      info: '&eKit editor.'
      args: ''
      explanation:
      - '&ePermissions:'
      - '&6cmi.kit.[kitName] &e- allows to use particular kit'
      - '&6cmi.kit.bypass.money &e- bypass money requirement'
      - '&6cmi.kit.bypass.exp &e- bypass exp requirement'
      - '&6/cmi kiteditor &e- shows kit list'
    info:
      kits: '&eKits: '
      iconSet: '&eNew icon set for &6[kitname] &ekit'
      kitExists: '&eKit with this name already exist!'
      deleteConfirm: '&eClick me if you really want to remove (&6[kitname]&e) kit!'
      deleteConfirmFinal: '&cThis action is not reversible!'
      kitRemoved: '&eKit (&6[kitname]&e) removed'
      kitNotRemoved: '&cKit (&6[kitname]&c) could not be removed'
      addNewInfo: '&eType kit name into chat and press enter. Type ''&6cancel&e''
        to cancel this action.'
      renameCommandInfo: '&eType new kit &6command &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      renameConfigInfo: '&eType new kit &6config &ename into chat and press enter.
        Type ''&6cancel&e'' to cancel this action.'
      groupInfo: '&eType new group name into chat and press enter. Type ''&6none&e''
        to remove group. Type ''&6cancel&e'' to cancel this action.'
      commandInfo: '&eType new command into chat and press enter. Type ''&6cancel&e''
        to cancel this action. Possible placeholders: &6{USERNAME} {DISPLAYNAME} {WORLDNAME}
        {KITNAME} {RANDOMPLAYER}'
      conditionsInfo: '&eType new required permission node into chat and press enter.
        Type ''&6cancel&e'' to cancel this action'
      descInfo: '&eType new description into chat and press enter. Type ''&6cancel&e''
        to cancel this action'
      renamed: '&eRenamed &6[kitname] &eto &6[newkitname]&e.'
      groupSet: '&eNew group (&6[groupname]&e) set for &6[kitname]'
      commandsListTitle: '&e✎&6Commands:'
      conditionsListTitle: '&e✎&6Conditions:'
      descListTitle: '&e✎&6Description:'
      ListTitleHover: '&eClick to open GUI'
      ListEditKitHover: '&cEdit &6[kitname]'
      ListAdd: ' &2+'
      ListAddHover: '&2Add new'
      guiClickery:
      - '&eLeft mouse click to increase and right click to decrease'
      - '&eHold &6Shift &eto speed process by 10 times'
      - '&eRepeating fast clicks will speed amount change'
      - '&eStop clicking for 1 sec to go back to default amount'
      OffHand: '&ePlace offHand item over here'
      Helmet: '&ePlace helmet item over here'
      Chest: '&ePlace chest item over here'
      Legs: '&ePlace leggings over here'
      Boots: '&ePlace boots over here'
      Weight: '&eWeight: &6[Weight]'
      WeightExtra:
      - '&eHigher value have bigger priority'
      - '&eKits should be in same group'
      despiteWeight: '&eShow despite weight: &6[Weight]'
      despiteWeightExtra:
      - '&ePLayer is not getting access to kit, but can preview it'
      Slot: '&eSlot: &6[slot]'
      SlotAuto: '&6Auto'
      Clone: '&eClone items from inventory'
      CloneExtra:
      - '&eUse right mouse button to include armors'
      - '&eClick again to revert changes'
      timeDelay: '&eDelay: &6[time]'
      usages: '&eCan be used for &6[times] &etimes'
      usagesUnlimited: '&6Unlimited'
      ignoreWeight: '&eShow despite weight: &6[state]'
      timeDelaySeconds: '&eIn seconds: &6[time]'
      moneyCost: '&eMoney cost: [cost]'
      expCost: '&eExp cost: [cost]'
      enabled: '&eEnabled'
      disabled: '&6Disabled'
      delete: '&6Delete kit'
      clickToSwitch: '&eClick to switch state'
      clickToEdit: '&eClick to start editing'
      editConfigName:
      - '&eClick to rename config name'
      - '&eThis only determines permission node'
      editCommandName:
      - '&eClick to rename command name'
      - '&eThis sets command you need to use to get this kit'
      displayName: '&7DisplayName: &r&f[name]'
      editDisplayName:
      - '&eClick to change display name'
      - '&eThis only used for visual purposes'
      kitGroup: '&eKit group: &6[group]'
      dropItems: '&eDrop item if full: &6[state]'
      commands: '&eCommands:'
      conditions: '&eConditions:'
      desc: '&eDescription:'
      mainMenu: '&eMainMenu'
      settings: '&eSettings'
      icon: '&eIcon used when kit is &2available'
      iconCd: '&eIcon used when kit is &cunavailable'
  kitusagereset:
    help:
      info: '&eReset kit usage counter'
      args: (kitName) (playerName)
    info:
      notLimited: '&eKit has no limited amount of usage'
      reset: '&eKit (&6[kit]&e) usage amount got reset for &6[playerDisplayName]'
      list: '&e[place]. &6[kit] &e[used]/[usages]'
      listHover: '&eClick to reset'
      noCd: '&eThere are no kit''s with usage above 0'
```

**Comment by CloudeLecaw** [comment] 2020-08-30 02:27
Nö your using the right Version. Was just asking to make sure its an issue and not just because of the old issue with the Lang file. Hope this can be fixed soon :)

**Comment by qwer2415wy** [comment] 2020-08-30 02:29
Ok Thx~ When will it be resolved?

**Comment by CloudeLecaw** [comment] 2020-08-30 11:57
hm it can take a while since you made a request instead of a bug report...

**Comment by qwer2415wy** [comment] 2020-08-30 11:58
Ok I will wait you

**Comment by Zrips** [comment] 2020-09-01 13:36
Confirmed, will be fixed with next update

**Closed by Zrips** 2020-09-01 13:36 UTC
Labels: bug report

**Comment by qwer2415wy** [comment] 2020-09-01 13:37
Ok thank you very much!
