### ISSUE TITLE
Bugged tp request.

### ISSUE THREAD

**Issue by Remski01** [Zrips/CMI#1982] opened 2019-06-29 16:28 UTC
**Description of issue:**
The other player where you send a tp request to dont get the message.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
18.06 12:04:03 [Server] INFO RemcoMC issued server command: /tpa ExoWolf
18.06 12:04:03 [Server] INFO Expected whitespace to end one argument, but found trailing data
18.06 12:04:03 [Server] INFO ...t":"
18.06 12:04:03 [Server] INFO [Accepteer]","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Accepteer"}]}},"clickEvent":{"action":"run_command","value":"/cmi tpaccept RemcoMC"}},{"text":" [Weiger]  ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Weiger"}]}},"clickEvent":{"action":"run_command","value":"/cmi tpdeny RemcoMC"}}]<--[HERE]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.5.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper-632 (MC: 1.13.2)

**Comment by Zrips** [comment] 2019-07-03 09:34
Can you send me your locale file? As it seems to be related to some strange locale text format used in this command

**Comment by DutchUser** [comment] 2019-07-04 15:11
https://pastebin.com/tBKvDY9N

**Comment by DutchUser** [comment] 2019-07-18 20:49
I dont think ist related to the locale. 

This also happen on /tpahere, and no changes were made after the update.

**Comment by DutchUser** [comment] 2019-07-20 00:21
Hello.

I looked into this. And found the issue quite fast. Its said to see that you just didnt say it. You know you plugin. But no, not saying anything. Really childish. 

But anyway, the issue is that you plugin decide to go retard mode when using `\n`. it decide that it want to remove the `'`. Causing a error when using that line as result.

Talking about line 625. After i removed the\n and added the ' the plugin then didnt go retard mode and didnt remove it. 

Now you think. Yay, issue fixed. No. Because you plugin dont handle it quite well. See the picture. Please fix that CMI dont remove the ' when a \n is used, or just make the handling better when it enter a new line.

And also. 

The purge is still broken. Please dont ignore me about it https://github.com/Zrips/CMI/issues/1632

**Comment by Zrips** [comment] 2019-11-11 10:19
Found the cause, should be fixed with next update and you can use \n for a hover over messages from now on and it will create new line.

**Closed by Zrips** 2019-11-11 10:19 UTC
Labels: bug report
