### ISSUE TITLE
Books appear empty upon using /book unlock

### ISSUE THREAD

**Issue by DevTarlow** [Zrips/CMI#8719] opened 2024-05-11 04:13 UTC
### Description of Issue

Gave myself a book from a kit I made with content inside it. When using the command /book unlock the book is then showing empty inside.

### Version Information

```shell
CMI: 9.7.2.6
CMILib: 1.4.78
Server: Paper(62) 1.20.6
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment] 2024-05-13 17:13
Might be issue specific to API of 1.20.6, because I cannot reproduce this on 1.20.4.

I know meta info for books changed in .5, so might be why. Thanks for reporting.

**Comment by Zrips** [comment] 2024-05-15 10:25
Should be resolved with next version

**Closed by Zrips** 2024-05-15 10:25 UTC
Labels: bug report
