### ISSUE TITLE
PlayTimeRewards (PayEvery) trigger after every server restart, sometimes even after /cmi reload

### ISSUE THREAD

**Issue by PetKCH** [Zrips/CMI#5556] opened 2021-05-09 22:47 UTC
**Description of issue:**
As the title says, upon every server restart, PayEvery type of PlayTimeRewards are distributed upon player join.

**Cmi Version (using`/cmi version`):**  8.8.3.10 SqLite

**Server Type (Spigot/Paperspigot/etc):** Paper(575) 1.16.5-R0.1-SNAPSHOT

**Server Version (using `/ver`):** git-Paper-575 (MC: 1.16.5)

**Comment by PetKCH** [comment] 2021-05-10 15:49
> PlayTimeFromStats

>`PlayTimeFromStats: false`

**Comment by Zrips** [comment] 2021-05-11 10:33
Do you have any plugin which could adjust players playtime? As it looks like player playtime gets messed up and detected incorrectly after server restart, atleast for you situation. Playtime in players data file and players statistics file could be different, so you might want to stick with one of those and avoid changing them. Usually playtime from stats should be more accurate value. Will investigate more, but at this time i cant reproduce this issue on my test server

**Comment by PetKCH** [comment] 2021-05-11 21:15
Sent you a DM on discord with my config files, tested without any plugins besides CMI and problem still occurs

**Comment by klaidoshka** [comment] 2021-05-12 09:59
Can confirm the issue, the same thing is happening to me.

Got around it by enabling permissions for every PlaytimeReward (in config) and when reward occurs, by using LuckPerms command I set the permission to false X_X, so it never happens again.

**Comment by Zrips** [comment] 2021-05-13 10:38
Will be resolved with next update

**Closed by Zrips** 2021-05-13 10:38 UTC
Labels: bug report
