### ISSUE TITLE
auto show of false gamemode - cant place blocks

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5602] opened 2021-05-24 00:07 UTC
on our server we get set automaticly to a fake gamemode 0
We cant place blocks, the gui looks.like gamemode 0 and the the rest behave like gamemode 1.
Only way to fix it set us to gamemode 0 and die. After some time i comes back.
Setting back to cmi 8.8.4.3 seems to fix this.
We setter back aggain to 8.8.4.4 and the issue was back.

We are using Paper 1.16.5 Build 721
And cmi 8.8.4.4 (we settet back to 8.8.4.4 and hope forna solution in 8.8.4.5

**Comment by rockitseven** [comment] 2021-05-24 12:45
I have the same issue, which seems to be caused by the /skin command.

**Comment by Zrips** [comment] 2021-05-25 09:31
Should get resolved with todays update

**Closed by Zrips** 2021-05-25 09:31 UTC
Labels: bug report

**Comment by CloudeLecaw** [comment] 2021-05-25 17:39
The problem is not fixed in 8.8.4.5
When we set back to 8.8.4.3 its fixed....
