### ISSUE TITLE
Integration with DiscordSRV does not work

### ISSUE THREAD

**Issue by DarkFort** [Zrips/CMI#1744] opened 2019-05-13 08:06 UTC
Integration with DiscordSRV does not work.
[10:52:39 INFO]: [DiscordSRV] No chat plugin hooks enabled

Messages from Discord to the chat are sent, but the message from the Minecraft chat is not.
---

#####################################
#####################################
```

---

> cmi version
[11:05:12 INFO]: --------------------------------------------------
[11:05:12 INFO]: Plugin version CMI: 8.6.1.5
[11:05:12 INFO]: Server version: Paper(625) 1.13.2-R0.1-SNAPSHOT
[11:05:12 INFO]: Version Vault: 1.7.2-b${env.TRAVIS_BUILD_NUMBER}(CMIEInjector)
[11:05:12 INFO]: --------------------------------------------------

[11:05:54 INFO]: This server is running Paper version git-Paper-625 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[11:05:54 INFO]: Previous version: git-Paper-624 (MC: 1.13.2)
[11:05:54 INFO]: Checking version, please wait...

**Comment by hamcoremusic** [comment] 2019-05-15 04:14
You need to disable "ClickHoverMessages" in your config and enable all of the DiscordSRV support!

**Comment by Vankka** [comment] 2019-11-03 12:22
Duplicate of #391

**Closed** 2020-07-01 15:20 UTC
