### ISSUE TITLE
Set/remove home cannot be run from Console

### ISSUE THREAD

**Issue by erisawesome** [Zrips/CMI#3264] opened 2020-05-07 17:23 UTC
**Description of issue:**
See title.

---
**ERROR:**
[Server] INFO You can only use this in game!

---

**CMI Version:** 8.6.24.0

**Server Type:** Paper(208) 1.15.2-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment] 2020-05-08 19:45
This is no bug, how you wanne setup home, sethome from console?
The console has no place where she is, also no world and no material. also the console cant have a place to tp. The console is not there. 

What you can do from console: You can /sethome and /home for other players from console

> sudo [playerName] (command/c:[text])
> Force another player to perform command
> 
> cmi.command.sudo.bypass – protects player from being ‘trolled’
so you can use: sudo ersawesome sethome Myhouse  or sudp ersawesome home Myhouse

This does make more sence then setting home or sethome from console

**Comment by erisawesome** [comment] 2020-05-09 16:19
According to the docs the sethome command has the ability to set another player's home at a location (or their current location):

**_sethome (homeName) (playerName) (-p) (-l:worldName;x;y;z) (block/Material) (slotNumber)_** 

I see no logistical reason why this couldn't be run from the console?

Similar with removehome:

**_removehome (homeName) (playerName)_**

This command shouldn't need to know a player's location to be run.

**Comment by CloudeLecaw** [comment] 2020-05-09 17:28
its still no bug because these command dont have this feature yet. These are not the only commands that cant be executed from console. 
If you really want to ask for this feature you need to creat a request not a bug report.
A bug would it be if it would not work from console but should, but it never was made to work from console, so please close this bug report or create a feature request like "home, sethome, remove from from console and make a little description why you think this feature should be added.

**Comment by Zrips** [comment] 2020-05-10 13:45
@erisawesome 
Will change behavior of sethome and removehome so we can run those from console.

**Closed by Zrips** 2020-05-10 13:45 UTC
Labels: bug report

**Comment by erisawesome** [comment] 2020-05-10 16:39
That was an insanely fast turnaround! This is why I use CMI!
