### ISSUE TITLE
Holograms jumping down?

### ISSUE THREAD

**Issue by klaidoshka** [Zrips/CMI#5571] opened 2021-05-12 09:40 UTC
**Description of issue:**

Hello,
Since few months ago holograms started to fall down. They fall down after server is started (the first load-up), then, by using `/cmi reload` everything fixes up. Holograms reappear in their real locations, not under 1~2 blocks. I have no clue why is this happening, but I suspect that it is something about CMI itself, because...

- This occurs even without any other plugin, only having CMI loaded.
- This occurs in every server platform that I tried (`spigot/paper/yatopia/airplane/tuinity/purpur`).
- Default (untouched) server platform's configs, like `spigot.yml/paper.yml/...` doesn't change anything, it still occurs.

---
**Video of the issue :**
https://youtu.be/e1QNCyFWvgc

---

**Cmi Version :** **8.8.4.1** (and any other 2-3 months old, can't find the real culprit)

**Server Type :** **Yatopia** (happens with Spigot/Paper/... too) 

**Server Version :** **1.16.5**

**Comment by klaidoshka** [comment] 2021-05-12 09:46
Also, I could just setup an schedule with CMI, which would do `/cmi reload` after server restart.
However, the preferred way for this would be to just have it somehow fixed, if possible 😅

**Comment by Zrips** [comment] 2021-05-13 10:29
Could you give actual example of hologram in that video, with all of its settings. Currently i can't reproduce it, holograms appear in a correct location from beginning

**Comment by klaidoshka** [comment] 2021-05-13 10:34
By using in-game editor I made the hologram have lines like this :
>   "&6&lTesting"
>   "&r"
>   "&2&lTesting"
>   "&r"
>   "&4&lTesting"
And my CMI files are still the same from like... 7 months ago, the folder kept updating itself when I updated CMI.jar, so maybe that could be somewhat the problem too. I will try to install clean CMI and make such hologram a bit later, like after 1.5hrs 👀

**Comment by Zrips** [comment] 2021-05-13 10:44
Tried with your example, still same thing, shows correctly in a correct position. Something is strange here. When you get a chance send me entire hologram section from holograms.yml just in case you have something funky in there.

**Comment by klaidoshka** [comment] 2021-05-13 11:42
> Tried with your example, still same thing, shows correctly in a correct position. Something is strange here. When you get a chance send me entire hologram section from holograms.yml just in case you have something funky in there.

Ummm... okay... I found the culprit for this weird stuff happening.

**What I tested :**
I took out all the plugins and only left CMI.jar alone to create everything, then tested and nothing happened. Holograms were okay. I transfered my old holograms into new file, everything was still okay, but holograms with REALLY multiple lines went under the blocks like it always did, `/cmi reload` wouldn't bring them up again, like before.

That made me think that it actually could be something with my old config... Once again I found the line `Holograms.placeUp: false` and changed it to `Holograms.placeUp: true`. Little did I know... that fixed the problem! Lol. Yeah, holograms are now under the blocks a bit and I will have to change their y: location, but they always stay in the same location, reloading doesn't change anything.

**Anyways :**
I thought that the option for `placeUp: true/false` would just change the way new lines are going, but it is changing the very "center" of the hologram, not the way to where would new lines go (up or down). After starting the server, if `placeUp` is set to `false`, holograms center is below (like with `placeUp: true`), but after doing `/cmi reload`, the center goes back to the top, that's why holograms change their y: location.

I would guess that **it is some kind of a bug** and maybe something can be changed regarding that. But I'm fine now 😄, I just have to increase all my holograms' y: location by 1 or 2 and everything is going to be fixed.

**Comment by Zrips** [comment] 2021-05-13 12:21
That placeUp indicates where we should place stuff from defined center point. So in some situations you might want to populate list up while keeping bottom line at same place independent how many lines you have, while in other situations opposite might be true. But in general its placement should be same independent if you reloaded plugin or not, it should be at same place each time. 
I can't really reproduce this issue at this point. Maybe it was related to some old files, but as long as its fixed at your end we can close this ticket. If you have any additional information relating to this issue, please create new ticket, as closed ones usually are not rechecked.

**Closed by Zrips** 2021-05-13 12:21 UTC
Labels: bug report
