### ISSUE TITLE
not working with SuperGuilds 

### ISSUE THREAD

**Issue by kwab90** [Zrips/CMI#1501] opened 2019-03-04 23:12 UTC
I have alot of plugins I went through all of them and found out CMI was not letting me use a big feature of the plugin SuperGuilds(https://www.spigotmc.org/resources/superguilds-realistic-wars-create-your-guild-and-war-in-battlearena-better-than-factions.6173/) I am unable to use the building feature I'm also trying to contact the SuperGuilds dev. I have no errors

**Cmi Version (using`/cmi version`):** 8.5.1.1

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  1.13.2

**Relevant plugins (Delete if this isn't needed):** SuperGuilds

**Comment by kwab90** [comment] 2019-03-04 23:47
is there a way to disable a command I think it might be holograms because for the SuperGuilds plugin it has to use holographic displays in order to use the building feature so I think its conflicting with your built in hologram system

**Comment by kwab90** [comment] 2019-03-05 01:55
nevermind im dumb

**Comment by LogGits** [comment] 2019-03-05 05:06
Duplicate of #1500

**Closed by LogGits** 2019-03-05 05:06 UTC
