### ISSUE TITLE
Custom Recipes get reset after player log in

### ISSUE THREAD

**Issue by cryoten** [Zrips/CMI#4021] opened 2020-08-19 18:39 UTC
**Description of issue:**

After a server restart, when a player logs in there will be an error in the console about an unrecognized recipe. It repeats twice and doesn't occur on subsequent log ins, just the first after a restart.

Is this something that can be fixed?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:58:35 ERROR]: Tried to load unrecognized recipe: bukkit:d5035283-68ae-4e16-b5cb-fd4900e86568 removed now.
[13:58:35 ERROR]: Tried to load unrecognized recipe: bukkit:d5035283-68ae-4e16-b5cb-fd4900e86568 removed now.
```

**Cmi Version (using`/cmi version`):** 
8.7.6.3

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.16.1, Paper-133

**Comment by broken1arrow** [comment] 2020-08-20 08:21
No, sadly not,

Special if you use items some have metadata, minecraft can handle it. So it get removed.

I use other plugin some do it better (but so long minecraft not add support for metadata you cant go round it to 100%).

**Comment by Zrips** [comment] 2020-08-20 10:42
This could be caused by some custom recipe being present in players advancement records which no longer exists, but in general, this should be fixed from minecraft side and not CMI

**Closed by Zrips** 2020-08-20 10:42 UTC
Labels: bug report

**Comment by Italoplcl** [comment] 2021-06-25 08:36
[01:30:43 ERROR]: Tried to load unrecognized recipe: minecraft:diamond_from_blasting removed now.
[01:30:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-46]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-46]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2185) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1996) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1977) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-46]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.t" is null
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.getWorld(CraftEntity.java:502) ~[patched_1.17.jar:git-Paper-46]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.getLocation(CraftEntity.java:411) ~[patched_1.17.jar:git-Paper-46]
at net.Zrips.CMILib.Locale.Language.replacePlayer(Language.java:375) ~[?:?]
at net.Zrips.CMILib.Locale.Language.updateCmiSnd(Language.java:281) ~[?:?]
at net.Zrips.CMILib.Locale.Language.getMessage(Language.java:88) ~[?:?]
at net.Zrips.CMILib.Messages.CMIMessages.getMsg(CMIMessages.java:201) ~[?:?]
at net.Zrips.CMILib.Locale.LC.getLocale(LC.java:491) ~[?:?]
at com.Zrips.CMI.CMI.getMsg(CMI.java:2198) ~[?:?]
at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.CreateGui(RegChestManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.openInventory(RegChestManager.java:135) ~[?:?]
at com.Zrips.CMI.commands.list.inv.perform(inv.java:44) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-46]
... 21 more
