### ISSUE TITLE
/cmi placeholders Internal error. on page 3 and 4

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#221] opened 2018-04-07 12:22 UTC
just pressing the next page button when you click it to go to page 3 at the bottom it creates an internal error and does not load the next page button. using the command to view the 4th page also causes this, Making me think the error lies there. Page 5 however works just fine.

here is the error.

```
7/04/2018 10:17 PM: [MC]: [22:17:52 INFO]: Mr_Grim_ issued server command: /cmi placeholders -p:4
7/04/2018 10:17 PM: [MC]: [22:17:52 ERROR]: null
7/04/2018 10:17 PM: [MC]: org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.6.4.0
7/04/2018 10:17 PM: [MC]:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-P
aper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.ja
r:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-
1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-13
50]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-135
0]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14
) ~[patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
7/04/2018 10:17 PM: [MC]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-13
50]
7/04/2018 10:17 PM: [MC]:     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
7/04/2018 10:17 PM: [MC]: Caused by: java.lang.NullPointerException
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:371) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:282) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:34) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:310) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:248) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.commands.list.placeholders.perform(placeholders.java:52) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[?:?]
7/04/2018 10:17 PM: [MC]:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1350]
7/04/2018 10:17 PM: [MC]:     ... 15 more
```

**Comment by MCTyler** [comment] 2018-04-07 12:29
Cannot reproduce with
```
[07:26:43 INFO]: This server is running Paper version git-Paper-"c719bcb" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[07:26:43 INFO]: You are running the latest version
> version
[07:27:20 INFO]: --------------------------------------------------
[07:27:20 INFO]: Current plugin version: 7.6.4.0
[07:27:20 INFO]: Newest version: 7.6.4.0
[07:27:20 INFO]: --------------------------------------------------
[07:27:55 INFO]: D8ta issued server command: /cmi placeholders -p:4
```

**Comment by RustyDagger** [comment] 2018-04-07 12:37
I'm a little behind on my paper Spigot version but i don't see how that would cause this. Page 3/5 contain if i'm not wrong placeholders relating to the built in rank up system ( cant tell for sure as i cant see it ) I have that set to false 

```
7/04/2018 10:35 PM: [MC]: [22:35:12 INFO]: This server is running Paper version git-Paper-1350 (MC: 1.12.2) (Implementing API version 1.12.2-R
0.1-SNAPSHOT)
7/04/2018 10:35 PM: [MC]: [22:35:12 INFO]: You are 34 version(s) behind 
```

plugin list.

7/04/2018 10:36 PM: [MC]: [22:36:08 INFO]: Plugins (27): Arconix, ArmorStandEditor, AsyncWorldEdit, BlockGlitchFix, BlocksHub, BuycraftX, Ches
tShop, CMI, CMIEInjector, CoreProtect, CrazyCrates, DeluxeChat, DeluxeJoin, Ersatz, GriefPrevention, GuiRedeemMCMMO, Jobs, LuckPerms, mcMM
O, PlaceholderAPI, ShopGUIPlus, Skript, skript-yaml, Vault, Votifier, WorldEdit, WorldGuard

**Comment by Zrips** [comment] 2018-04-08 11:59
Should be fixed with next build.

**Closed by Zrips** 2018-04-08 11:59 UTC
Labels: bug report, error
