### ISSUE TITLE
An internal error, not all comands are working

### ISSUE THREAD

**Issue by linuxhus** [Zrips/CMI#1058] opened 2018-11-12 15:03 UTC
i have new installed the plugin.
permisssionplugin is uperms = ultarpermissions

Cmi Version (using/cmi version):
i cannot /cmi version then i got // An internal error ......
8.0.21.4
Server Type (Spigot/Paperspigot/etc):
spigot 1.13 java 8
Server Version (using /ver):

Relevant plugins (Delete if this isn't needed):
ultrapermissions

Description of issue or feature request:
When i try to /cmi afk
DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST

ERROR (DELETE IF YOU HAVE NO ERROR):

####################
####################

[01:48:55] [Server thread/INFO]: DosePlay issued server command: /cmi afk

[01:48:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.21.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: me/TechXcrafter/UltraPermissions/UltraPermissions
at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
at com.Zrips.CMI.Locale.Language.replaceUser(Language.java:315) ~[?:?]
at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:182) ~[?:?]
at com.Zrips.CMI.Modules.Afk.AfkManager.setUserToAfk(AfkManager.java:186) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.tunOnAfk(CMIUser.java:1317) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.setAfk(CMIUser.java:1303) ~[?:?]
at com.Zrips.CMI.commands.list.afk.perform(afk.java:52) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

An internal error ......

CONFIG SECTION (DELETE IF NOT RELEVANT):

#####################################
#####################################

**Comment by LogGits** [comment] 2018-11-13 00:50
Duplicate of #1040

**Closed by LogGits** 2018-11-13 00:50 UTC
