### ISSUE TITLE
Incorrect command display /tpa (tab)

### ISSUE THREAD

**Issue by fidzhikovsky** [Zrips/CMI#5185] opened 2021-02-27 10:48 UTC
**Cmi Version (using`/cmi version`):** 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):**  Paper 1.16.5

**Server Version (using `/ver`):**  1.16.5

Incorrect command display /tpa (tab)

![image](https://user-images.githubusercontent.com/67680853/109385092-5fdac380-7902-11eb-9f98-456c1e59889b.png)

**Comment by fidzhikovsky** [comment] 2021-02-27 11:15
The TAB with nickname selection is broken on all teams

**Comment by fidzhikovsky** [comment] 2021-02-27 11:16
![image](https://user-images.githubusercontent.com/67680853/109385637-5b180e80-7906-11eb-96a3-ad68168641f7.png)

**Comment by CloudeLecaw** [comment] 2021-03-01 11:35
Whats wrong here? I allways tpa to my anvil and wait for responce 😂

**Comment by broken1arrow** [comment] 2021-03-01 12:18
I always tpa to air and i still wanting on response.

**Comment by we67iop** [comment] 2021-03-01 14:15
Can't expect the aliaseditor to work without pay, slavery is illegal you know...

**Comment by fidzhikovsky** [comment] 2021-03-01 18:13
DONT WORK /tpa nickname (tab) . 

/tpa nickname+tab

**Comment by Zrips** [comment] 2021-03-02 12:30
@fidzhikovsky 
Try testing without any other plugin or atleast provide more information about this. Are you using default alias or made your own custom?

**Comment by CloudeLecaw** [comment] 2021-03-02 13:13
look like he has this problem for more then just one command.
in his screenshot he showed us /pay

**Comment by Zrips** [comment] 2021-03-02 14:12
Noticed that too, but question would be if its actually caused by CMI or another plugin adding extra tab completes and knowing if its custom alias or default one would help out to narrow down possible causes

**Comment by Zrips** [comment] 2021-03-06 15:52
Should have been resolved with latest CMI build

**Closed by Zrips** 2021-03-06 15:52 UTC
Labels: bug report, unconfirmed
