### ISSUE TITLE
CMI BungeeCord packet issue

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#68] opened 2018-03-02 21:41 UTC
The first few times someone joins they are always kicked on my servers due to packet spamming. After debugging it turned out to be coming from CMI. 

Now I'm not sure if I'm doing something wrong but there isn't really a BungeeCord setting except the BungeeMessages which I already tried turning to false but it doesn't help.

The pastebin shows how the packets look. In this example I was kicked with the message. 

Pastebin: [https://pastebin.com/nZwb1qBD](url)
aXed lost connection: You are sending too many packets! 5205
From which 4744 packets where from CMI.

**Comment by Zrips** [comment] 2018-03-03 13:12
Will do some changes, currently cant reproduce issue but i have general idea what is going on. Will post new version, try it out and give me feedback if that helped or not.

**Comment by iaxedu** [comment] 2018-03-03 17:29
Tested quite a bit and it seems to fixed :) Butttt it seems that this update broke **/cmi schedule name**

[https://pastebin.com/5fCmaNdw](https://pastebin.com/5fCmaNdw)

**Comment by LogGits** [comment] 2018-03-03 18:02
@iaxedu please open another issue request for the schedule command as it is unrelated to this issue. As you mention that the issue is fixed I am closing this issue, however, if the issue persists please don't hesitate to reopen this ticket 🙂

**Closed by LogGits** 2018-03-03 18:02 UTC
