### ISSUE TITLE
[1.16.1] (CMI v8.7.0.0) Could not pass event CMIPlayerUnVanishEvent 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3560] opened 2020-06-25 16:23 UTC
**Description of issue:**

user on discord reported this
```
Server thread/ERROR Could not pass event CMIPlayerUnVanishEvent to CMI v8.7.0.0

org.bukkit.event.EventException: null
```
source: https://ptb.discordapp.com/channels/452792793631555594/526402563847880725/725743221220704386
<img width="782" alt="Screenshot 2020-06-25 at 18 23 18" src="https://user-images.githubusercontent.com/28841349/85758811-f2dab280-b710-11ea-88c1-c4326a207675.png">

I asked for additional information but didn't receive it (yet)

**Comment by mrfloris** [comment] 2020-06-25 16:28
Received additional information from the user;

https://pastebin.com/04eP745Z

![unknown](https://user-images.githubusercontent.com/28841349/85759946-a9d72e00-b711-11ea-85d3-289418aaaa50.png)

**Comment by mrfloris** [comment] 2020-06-25 18:45
<img width="955" alt="Screenshot 2020-06-25 at 20 44 44" src="https://user-images.githubusercontent.com/28841349/85780279-b9ac3d80-b724-11ea-9a57-e281fcbefd40.png">

**Comment by CloudeLecaw** [comment] 2020-06-25 20:33
```
[22:30:47] [Server thread/ERROR]: Could not pass event CMIPlayerUnVanishEvent to CMI v8.7.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:124) ~[?:?]
	at com.Zrips.CMI.Modules.Vanish.VanishListener.onPlayerJoinHideOthers(VanishListener.java:129) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.PlayerList.a(PlayerList.java:199) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.LoginListener.c(LoginListener.java:153) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.LoginListener.tick(LoginListener.java:52) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:128) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1010) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:849) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1603) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:42) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:30) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapListener.CMIPlayerUnVanishEvent(DynMapListener.java:20) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
	... 24 more
```#The Problem is that dynmap is not uptodate for 1.16.1 happens on login

**Comment by Zrips** [comment] 2020-06-26 12:40
Will be fixed, tho its simply issue with dynmap failing to load. There is error log at startup informing that.

**Closed by Zrips** 2020-06-26 12:40 UTC
Labels: bug report
