### ISSUE TITLE
Baltop Issues

### ISSUE THREAD

**Issue by SirGoldman-git** [Zrips/CMI#1022] opened 2018-10-29 03:35 UTC
Baltop has been working on and off after this 1.13 update phase. At times, after about 5-10 hours online baltop will only display one user. For the first time last night my server crashed because of cmi's baltop command.

I'm thinking its a issue loading and recalculating so much data (I have over 1,600 users in the cmi db). Could you possibly add a option in the config to only display a set amount of users on baltop? Baltop already shows you what place you're in from the first page, so I don't see this as being a big deal if you capped how many displayed (Assuming that's the issue).

**Comment by LogGits** [comment] 2018-11-01 07:58
Duplicate of #943

**Closed by LogGits** 2018-11-01 07:58 UTC
Labels: duplicate
