### ISSUE TITLE
[Issue] Bypass AFK and AFK-KICK

### ISSUE THREAD

**Issue by Xardas88** [Zrips/CMI#951] opened 2018-10-08 17:18 UTC
I found a way to bypass the afk / afk-kick.

1. Log-in
2. Launch another client and log-in
3. The first client will be kicked 
4. In the second client, doing no interaction and staying still will never go afk

---
**CONFIG SECTION:**
```
https://pastebin.com/vikzmEDN
```
**Cmi Version:** 
CMI8.0.19.0
**Server Type:** 
Spigot
**Server Version:** 
1.13.1-R0.1-SNAPSHOT
#

**Comment by CloudeLecaw** [comment] 2018-10-09 13:48
Well i think some playable Kids may use this methodes.. and some YouTube Kids. but normal Player do not do Things like this.

**Comment by x1p** [comment] 2018-10-09 14:31
Which is exactly the reason this should be solved. We can't allow things which would only be beneficial for cheaters.

**Comment by Xardas88** [comment] 2018-10-10 11:28
> Which is exactly the reason this should be solved.

Cmi has an internal Playtime Rewards and i found a way to cheat for take it (if you enable" exclude afk" in the config too)

I use hourly rewards with commandblock and use afk-kick. This bug allows players to not be kicked for afk from the server.

if you want I have more examples to explain the reason for solving this bug, but I think these are enough.

**Comment by x1p** [comment] 2018-10-11 14:44
I can confirm I have a few players who say they earn money and not being AFK although they should be AFK according to my defined settings. Of course these players don't know its a bug or won't tell me because that not in their interest.

**Comment by CloudeLecaw** [comment] 2018-10-11 23:07
well i can confirm this behavior in spigot 1.13.1 too

**Comment by Zrips** [comment] 2018-10-16 12:29
Next update will be fixed.
Nice catch.

**Closed by Zrips** 2018-10-16 12:29 UTC
Labels: bug report, unconfirmed
