### ISSUE TITLE
Warps not saving to warps.yml

### ISSUE THREAD

**Issue by mike3132** [Zrips/CMI#7406] opened 2022-11-28 01:06 UTC
### Description of Issue

I have a warp that no matter what I do, whenever I reload cmi or after a few minutes it automatically goes back to the default values and goes to the first page of the warps gui. This is now happening with any new warps that I create. It's not saving to the warps.yml file, There is no errors upon reload or warp creation 

### Version Information

```shell
CMI: 9.2.5.5
CMILib: 1.2.3.7
Server: Paper(39) 1.19-R0.1-SNAPSHOT
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
Warps.yml
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mike3132** [comment] 2022-11-28 01:06
![Screenshot_1](https://user-images.githubusercontent.com/32972166/204171045-90c34d7a-07a5-4bf5-9439-203c8bb5310a.png)
![Screenshot_2](https://user-images.githubusercontent.com/32972166/204171047-ef5be12d-7a72-43a4-9a3b-d46d38afe29e.png)
![Screenshot_3](https://user-images.githubusercontent.com/32972166/204171049-3ddabc71-ea77-4d27-978d-01e24cf978d1.png)

**Comment by Zrips** [comment] 2022-12-01 13:16
Doesn't look to be common issue. This could be caused by issue where plugin would not have right to modify files which would prevent it from updating warps file with new warps on save.

**Comment by mike3132** [comment] 2022-12-01 14:14
Alrighty I seem to have found a work around for it. If I make a warp and set all of the features I want, and then make another warp and save-all and then cmi reload it saves the first warp to the warps file but not the second one.

**Comment by Zrips** [comment] 2022-12-01 14:50
That's some weird behavior you have here. Saving process is the same when initially creating it and when its been done on UI warp editor UI close event. So there should not be any issues with that and looks that its not an issue in most cases. Does warp point gets saved when you perform /cmi setwarp [warpName] but dont close editor UI? Just check warps.yml file if record of it exists already.

**Comment by mike3132** [comment] 2022-12-02 00:36
It seems to just save on the initial creation of the warp as seen in this config. It 
![Screenshot_1](https://user-images.githubusercontent.com/32972166/205188318-012bc79f-b079-4ab1-a93b-ae4ed0dbc8e8.png)
saves the location, and who made it. Also I have tried clicking the close button the gui and pressing esc to close the gui and it dosn't seem to have an effect either way.

**Comment by radiant-ai** [comment] 2023-02-03 01:48
This bug happens to me. I just cannot use GUI to edit my warps and it is very annoying. My warps.yml file only has `Location` and `Creator` saved for a warp.
I workaround this with creating another warp and deleting it. After this all my edits get saved :/

**Comment by MC-MrBirdy** [comment] 2023-03-24 23:05
Seem to also have issues with warps not saving correctly.
In my case new warps are saved, but any edit I make is not.

Normal steps:
1. /cmi setwarp test
2. edit the warp (e.g. item)
3. restart the server
4. warp is back to the default version

Workaround steps:
1. /cmi setwarp test
2. edit the warp (e.g. item)
3. /cmi setwarp removeme
4. /cmi removewarp removeme
5. restart the server
6. warp now has the changed version

Version information:
- paper-1.19.4-470
- CMI-9.5.0.0
- CMILib1.2.5.2

No other plugins are installed while testing the above case(s), and this issue has persisted since 1.19.3.

**Comment by Zrips** [comment] 2023-03-25 09:14
Should be resolved with next update. If issue persists, let me know.

**Closed by Zrips** 2023-03-25 09:14 UTC
Labels: bug report
