### ISSUE TITLE
Error on login in latest CMI 9.0.0.8 with Paper 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5825] opened 2021-07-07 21:20 UTC
```
>.... [23:19:29 WARN]: [CMI] Plugin CMI v9.0.0.8 generated an exception while executing task 42136
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int[])'
at com.Zrips.CMI.NBT.v1_17_R1.updatePlayerViaPackets(v1_17_R1.java:976) ~[?:?]
at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:128) ~[?:?]
at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:105) ~[?:?]
at com.Zrips.CMI.Modules.Skin.SkinListener$2$1.run(SkinListener.java:53) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-79]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-79]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-79]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

![image](https://user-images.githubusercontent.com/12080017/124830301-f6d31e80-df79-11eb-8c0e-a18090f8dc28.png)

Error apears on the live server on login.

It it because this version is for 1.17.1?

**Comment by mrfloris** [comment] 2021-07-08 08:10
Cannot reproduce on my servers. Just checked the /logs/ from the last 24 hours on my cmi servers and see no login issues.

**Comment by mrfloris** [comment] 2021-07-08 08:35
Let me know when you remove the eventcommands.yml onJoin event that deals with skin applying, and try this again if the error goes away? Might help narrow it down.

**Comment by Zrips** [comment] 2021-07-08 08:43
Will issue a basic fix for this, but its strongly recommended to update to 1.17.1 which will not have this issue.

**Closed by Zrips** 2021-07-08 08:43 UTC
Labels: bug report
