### ISSUE TITLE
CustomAlias sub-commands

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#3231] opened 2020-05-01 17:05 UTC
**Description of issue:**
I've created a CustomAlias to block the use of the subcommand /jobs browse
Sometimes it works fine, but most of the time the whole /jobs command is blocked and I don't know why.

---

```
  jobs browse:
    Cmds:
    - msg! [playerName] &c¡Conjuro bloqueado por las artes oscuras!
```

-----------------------
**CMI Version: 8.6.24.0**
**Server Type: Spigot**
**Server Version: 1.15.2-R0.1-SNAPSHOT**
**Vault Version: 1.7.2-b107**

**Comment by Zrips** [comment] 2020-05-02 14:34
Interesting. Is this change in behavior usually happens after server restart or it does during run? If during run, do you perform any customalias action? As tested out if this blocking actual works, and it did. Cant reproduce issue at this point so no idea why its starting to miss behave.

**Comment by C4BR3R4** [comment] 2020-05-02 17:08
I really do not know. I have it blocked for a long time, I have done several tests and I do not know when this happens.

What I do know is that when I create the Alias in the game, it works fine even restarting the CMI.

It has to be on the server restart.

**Comment by Zrips** [comment] 2020-08-12 14:20
Should be resolved with latest builds

**Closed by Zrips** 2020-08-12 14:20 UTC
Labels: bug report
