### ISSUE TITLE
DiscordSRV and  ClickHoverMessages

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#2052] opened 2019-07-13 21:56 UTC
Looks like an old bug that still remains around...

a) Chat messages are not sent to Discord if ClickHoverMessages: is set to true. Even if DiscordSRV is set to true. Disabling ClickHoverMessages: it will start to work again, however, it breaks /mail and /ctext pages and all sorts of functionality if that is disabled.

b) An additional issue which is that when people are linked, if I type of message as OP, the message shows up in-game as if I was in-game, but when everyone else uses discord have a linked account, they show up in a different Discord formatting.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: true
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: true
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'
  # Enables support for DynMap web chat
  DynMapChat: true
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players

```

---

**Cmi Version (using`/cmi version`):** 

[16:55:42 INFO]: --------------------------------------------------
[16:55:42 INFO]: CMI plugin version: 8.6.7.1
[16:55:42 INFO]: Server version: Paper(129) 1.14.3-R0.1-SNAPSHOT
[16:55:42 INFO]: Vault version: 1.6.10(+)
[16:55:42 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 

Paper

**Server Version (using `/ver`):** 

[16:56:11 INFO]: This server is running Paper version git-Paper-129 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[16:56:11 INFO]: Checking version, please wait...
[16:56:12 INFO]: Previous version: git-Paper-124 (MC: 1.14.3)

**Relevant plugins (Delete if this isn't needed):**

DiscordSRV

**Comment by digitalcrowd** [comment] 2019-07-26 00:44
In DiscordSRV, I changed this value to false.

RespectChatPlugins: false

Now, the chat does show up in Discord. However, any plugins that allow you to type input into the chat line without using the forward slash, shows up. Like creating or updating Holograms in CMI, or ChestShop plugins that allow you to type in information on chat line, show up in Discord.

It would be nice if this bug could be fixed. I know it's probably at the end of the list for you, cause many open bug issues related to this.

**Comment by digitalcrowd** [comment] 2019-08-02 16:06
Text that is filtered in chat shows up on Discord.

**Comment by Vankka** [comment] 2019-11-03 12:20
You should never disable `RespectChatPlugins`, it is meant for debugging purposes only.

Duplicate of #391

**Closed** 2020-07-01 15:30 UTC
Labels: bug report
