### ISSUE TITLE
CMI9.2.1.1.jar//com.Zrips.CMI.AllListeners.UserEvents.onPlayerQuit(UserEvents.java:452)

### ISSUE THREAD

**Issue by XinyuGuGu** [Zrips/CMI#7036] opened 2022-07-03 22:57 UTC
### Description of Issue

CMI stuck main thread

### Version Information

```shell
> cmi version
[06:55:47 INFO]: --------------------------------------------------
[06:55:47 INFO]: CMI 插件版本: 9.2.1.1 BungeeCord CMIB  SqLite
[06:55:47 INFO]: CMILib: 1.2.1.0
[06:55:47 INFO]: 服务器版本: Purpur 1.18.2-R0.1-SNAPSHOT
[06:55:47 INFO]: CMI 经济: 禁用 经济: 1.7.3-CMI CMI 聊天: 禁用
[06:55:47 INFO]: 模块 -> 55 已启用 1 已禁用: votifier
[06:55:47 INFO]: --------------------------------------------------
```

### Errors

```shell
-421.6354641397353)
[02:07:57 INFO]: [反作弊] Seven_Nine79 使用 Fabric 进入服务器!
[02:07:59 INFO]: Seven_Nine79 lost connection: Disconnected
[02:08:07 INFO]: UUID of player wildcat is c7fac498-7e09-3efa-b2a4-a87422d77d4a
[02:08:07 INFO]: wildcat[/115.56.194.230:9405] logged in with entity id 2243921 at ([world]7296.8424341356895, 70.0, -43801.70802492603)
[02:08:08 INFO]: XuAnXuAn4 lost connection: Disconnected
[02:08:09 INFO]: j1angnan lost connection: Disconnected
[02:08:10 INFO]: 你治愈了 wildcat (在线).
[02:08:10 INFO]: 已设置飞行模式 禁用 ，被操作玩家 wildcat (在线).
[02:08:16 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:16 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:16 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:16 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:16 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:16 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:17 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:17 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:17 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:17 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:17 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:17 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:23 INFO]: [MysqlPlayerDataBridge] Saving online players data...
[02:08:23 INFO]: [ClueScrolls] Auto saved 14 chest inventories in 21ms
[02:08:23 INFO]: [ExcellentCrates] Auto-save: Saved 14 online users | 0 offline users.
[02:08:23 INFO]: え 你给予了 KongcHecanO 2.00 G
[02:08:23 INFO]: え 你给予了 HellHunter 5.00 G
[02:08:23 INFO]: え 你给予了 uo_lwuy 1.00 G
[02:08:23 INFO]: え 你给予了 xueyueyaodao 1.00 G
[02:08:23 INFO]: [MysqlPlayerDataBridge] Data save complete for 14 players in 131 ms.
[02:08:24 INFO]: No residences found in world: plot
[02:08:35 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:08:44 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:44 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:44 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:44 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:45 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:45 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:45 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:45 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:50 INFO]: Aceroiaorion lost connection: Disconnected
[02:08:52 INFO]: [御灵山海] 熔岩史莱姆 已降临至 史莱姆之森！
[02:08:56 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:56 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:56 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:56 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:56 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:56 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:56 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:56 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:08:57 INFO]: 已给予 kjfdc 1个 优良灵咒核心
[02:08:57 INFO]: [我 -> kjfdc] [优良灵咒核心]x1 兑换成功
[02:09:03 INFO]: HellHunter 回来了
[02:09:13 INFO]: え 你给予了 KongcHecanO 1.50 G
[02:09:13 INFO]: え 你给予了 uo_lwuy 1.00 G
[02:09:13 INFO]: え xueyueyaodao 被给予了 1 灵晶
[02:09:22 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:09:53 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:09:55 INFO]: j1angnan 使用 熔岩短匕 击杀了 熔岩史莱姆！
[02:09:55 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:09:57 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:10:03 INFO]: え 你给予了 KongcHecanO 1.00 G
[02:10:03 INFO]: え uo_lwuy 被给予了 1 灵晶
[02:10:03 INFO]: え xueyueyaodao 被给予了 1 灵晶
[02:10:09 INFO]: wildcat lost connection: Disconnected
[02:10:10 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:10:11 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:10:23 INFO]: [御灵山海] 熔岩史莱姆 已降临至 史莱姆之森！
[02:10:53 INFO]: え 你给予了 KongcHecanO 1.00 G
[02:10:53 INFO]: え 你给予了 uo_lwuy 1.00 G
[02:10:53 INFO]: え 你给予了 xueyueyaodao 1.00 G
[02:11:23 INFO]: [MysqlPlayerDataBridge] Saving online players data...
[02:11:23 INFO]: [MysqlPlayerDataBridge] Data save complete for 12 players in 83 ms.
[02:11:43 INFO]: え 你给予了 KongcHecanO 1.00 G
[02:11:43 INFO]: え 你给予了 uo_lwuy 2.00 G
[02:11:43 INFO]: え 你给予了 xueyueyaodao 1.00 G
[02:11:43 INFO]: え Dawn_Xinyu 被给予了 3 灵晶
[02:11:47 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:11:47 WARN]: [MMOItems] Couldn't read the subtable item CONSUMABLE.ROCK
[02:11:53 INFO]: 只有玩家可以使用该指令.
[02:12:21 INFO]: j1angnan 使用 熔岩短匕 击杀了 熔岩史莱姆！
[02:12:21 INFO]: [+] NaJii
[02:12:22 INFO]: UUID of player NaJii is 0690edc4-cba1-3965-b407-9b4195ad10c8
[02:12:22 INFO]: NaJii[/27.26.242.13:10281] logged in with entity id 2249051 at ([zhucheng]-1.3217010353526037, 17.0, -0.4517374875822938)
[02:12:22 INFO]: [Vulcan] [Vulcan] kjfdc 位置被更新为不存在的方块上! (zhucheng, -29, 15, 27) [15]
[02:12:35 INFO]: 親sour_budou➦ 1
[02:15:22 ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1632 (MC: 1.18.2) ---
[02:16:30 INFO]: 签到 >>> 玩家数据已保存!
[02:17:09 INFO]: NaJii lost connection: Disconnected
[02:17:09 ERROR]: The server has not responded for 180 seconds! Creating thread dump
[02:17:09 ERROR]: ------------------------------
[02:17:09 ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
[02:17:09 INFO]: [反作弊] lIllIlIlIllIl 因未回应服务器数据包被移出服务器! (287837ms)
[02:17:09 INFO]: [反作弊] lIllIlIlIllIl 因未回复KeepAlive数据包而被踢出! (288619ms)
[02:17:09 INFO]: [反作弊] KongcHecanO 因未回应服务器数据包被移出服务器! (287831ms)
[02:17:09 INFO]: [反作弊] KongcHecanO 因未回复KeepAlive数据包而被踢出! (288625ms)
[02:17:09 INFO]: [反作弊] kjfdc 因未回应服务器数据包被移出服务器! (287818ms)
[02:17:09 INFO]: [反作弊] kjfdc 因未回复KeepAlive数据包而被踢出! (288598ms)
[02:17:09 INFO]: [反作弊] SpecialCheni 因未回应服务器数据包被移出服务器! (287860ms)
[02:17:09 INFO]: [反作弊] SpecialCheni 因未回复KeepAlive数据包而被踢出! (288198ms)
[02:17:09 ERROR]: ------------------------------
[02:17:09 ERROR]: Current Thread: Server thread
[02:17:09 INFO]: [反作弊] sour_budou 因未回应服务器数据包被移出服务器! (287825ms)
[02:17:09 INFO]: [反作弊] sour_budou 因未回复KeepAlive数据包而被踢出! (288162ms)
[02:17:09 ERROR]:       PID: 39 | Suspended: false | Native: false | State: RUNNABLE
[02:17:09 ERROR]:       Stack:
[02:17:09 ERROR]:               net.minecraft.network.Connection.processQueue(Connection.java:521)
[02:17:09 ERROR]:               net.minecraft.network.Connection.flushQueue(Connection.java:493)
[02:17:09 ERROR]:               net.minecraft.network.Connection.send(Connection.java:401)
[02:17:09 ERROR]:               net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2123)
[02:17:09 ERROR]:               net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2109)
[02:17:09 ERROR]:               net.minecraft.server.ServerScoreboard.broadcastAll(ServerScoreboard.java:296)
[02:17:09 ERROR]:               net.minecraft.server.ServerScoreboard.onTeamRemoved(ServerScoreboard.java:175)
[02:17:09 ERROR]:               net.minecraft.world.scores.Scoreboard.removePlayerTeam(Scoreboard.java:205)
[02:17:09 ERROR]:               org.bukkit.craftbukkit.v1_18_R2.scoreboard.CraftTeam.unregister(CraftTeam.java:312)
[02:17:09 ERROR]:               [C][基础插件]CMI9.2.1.1.jar//com.Zrips.CMI.AllListeners.UserEvents.onPlayerQuit(UserEvents.java:452)
[02:17:09 ERROR]:               com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1285.execute(Unknown Source)
[02:17:09 ERROR]:               org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[02:17:09 ERROR]:               org.bukkit.plugin.EventExecutor$$Lambda$6288/0x0000000802172be8.execute(Unknown Source)
[02:17:09 ERROR]:               co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[02:17:09 ERROR]:               org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:17:09 ERROR]:               org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[02:17:09 ERROR]:               net.minecraft.server.players.PlayerList.remove(PlayerList.java:620)
[02:17:09 ERROR]:               net.minecraft.server.players.PlayerList.remove(PlayerList.java:603)
[02:17:09 ERROR]:               net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2093)
[02:17:09 ERROR]:               net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2073)
[02:17:09 ERROR]:               net.minecraft.network.Connection.handleDisconnection(Connection.java:764)
[02:17:09 ERROR]:               net.minecraft.network.Connection.tick(Connection.java:583)
[02:17:09 ERROR]:               net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231)
[02:17:09 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1651)
[02:17:09 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522)
[02:17:09 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483)
[02:17:09 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247)
[02:17:09 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[02:17:09 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$4167/0x00000008014ce8f0.run(Unknown Source)
[02:17:09 ERROR]:               java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[02:17:09 ERROR]: ------------------------------
[02:17:09 ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
[02:17:09 ERROR]: ------------------------------
[02:17:10 INFO]: [反作弊] uo_lwuy 因未回应服务器数据包被移出服务器! (287803ms)
[02:17:10 INFO]: [反作弊] uo_lwuy 因未回复KeepAlive数据包而被踢出! (288204ms)
[02:17:10 INFO]: [反作弊] Hilendare 因未回应服务器数据包被移出服务器! (287890ms)
[02:17:10 INFO]: [反作弊] Hilendare 因未回复KeepAlive数据包而被踢出! (288232ms)
[02:17:10 INFO]: [反作弊] kasumi 因未回应服务器数据包被移出服务器! (287868ms)
[02:17:10 INFO]: [反作弊] kasumi 因未回复KeepAlive数据包而被踢出! (288232ms)
[02:17:10 INFO]: [反作弊] xueyueyaodao 因未回应服务器数据包被移出服务器! (287845ms)
[02:17:10 INFO]: [反作弊] xueyueyaodao 因未回复KeepAlive数据包而被踢出! (288216ms)
[02:17:10 INFO]: [反作弊] HellHunter 因未回应服务器数据包被移出服务器! (287842ms)
[02:17:10 INFO]: [反作弊] HellHunter 因未回复KeepAlive数据包而被踢出! (288629ms)
[02:17:10 INFO]: [反作弊] 23121 因未回应服务器数据包被移出服务器! (287862ms)
[02:17:10 INFO]: [反作弊] 23121 因未回复KeepAlive数据包而被踢出! (288199ms)
[02:17:10 WARN]: Can't keep up! Is the server overloaded? Running 287898ms or 5757 ticks behind
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (8/35)
[02:17:10 INFO]: lIllIlIlIllIl lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: [反作弊] 检测到 lIllIlIlIllIl 使用 Timer (类型 D) (8/35)
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (10/35)
[02:17:10 INFO]: KongcHecanO lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (12/35)
[02:17:10 INFO]: kjfdc lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (14/35)
[02:17:10 INFO]: SpecialCheni lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (16/35)
[02:17:10 INFO]: [反作弊] 检测到 sour_budou 使用 Timer (类型 D) (18/35)
[02:17:10 INFO]: sour_budou lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: uo_lwuy lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: Hilendare lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: kasumi lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: UUID of player NaJii is 0690edc4-cba1-3965-b407-9b4195ad10c8
[02:17:10 INFO]: UUID of player sour_budou is 835a7489-1776-3437-890b-cccfff943a70
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: UUID of player NaJii is 0690edc4-cba1-3965-b407-9b4195ad10c8
[02:17:10 INFO]: xueyueyaodao lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: UUID of player Hilendare is 459f2a53-ed94-38d3-8e07-e3a112061d1c
[02:17:10 INFO]: UUID of player HellHunter is ffce59d6-cc43-304d-91f0-61146214da81
[02:17:10 INFO]: UUID of player lIllIlIlIllIl is 97df1924-d9cf-38e8-8d03-f5ed38a95321
[02:17:10 INFO]: HellHunter lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: UUID of player xueyueyaodao is ffcd58ec-a210-3d98-86ab-572c5348a288
[02:17:10 INFO]: UUID of player kasumi is f58c9284-3aa7-3720-957d-4d8508826675
[02:17:10 INFO]: UUID of player sour_budou is 835a7489-1776-3437-890b-cccfff943a70
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: 23121 lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
[02:17:10 INFO]: UUID of player XuAnXuAn4 is fcf7b40c-b871-378e-8843-4862faaedf0c
[02:17:10 INFO]: UUID of player sour_budou is 835a7489-1776-3437-890b-cccfff943a70
[02:17:10 INFO]: UUID of player XuAnXuAn4 is fcf7b40c-b871-378e-8843-4862faaedf0c
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: UUID of player Dawn_Xinyu is c1858d7f-5c0d-3553-88f9-01dee365f69c
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: UUID of player j1angnan is 8bd2c95d-2fa2-39dc-a732-13a0f3277ad7
[02:17:10 INFO]: Dawn_Xinyu lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@e7fcd0a[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@6caf063f]},legacy=false] (/106.112.42.42:10299) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@517fa29e[id=0690edc4-cba1-3965-b407-9b4195ad10c8,name=NaJii,properties={textures=[com.mojang.authlib.properties.Property@184efeea]},legacy=false] (/27.26.242.13:10365) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@2308a042[id=9c4fac1d-18e3-3cf0-9731-0fbca9c39d73,name=SpecialCheni,properties={},legacy=false] (/115.151.185.70:10370) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@569b2fc4[id=0690edc4-cba1-3965-b407-9b4195ad10c8,name=NaJii,properties={textures=[com.mojang.authlib.properties.Property@3416f769]},legacy=false] (/27.26.242.13:10463) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@26fcbf80[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@5e597090]},legacy=false] (/106.112.42.42:10470) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@a3b9293[id=835a7489-1776-3437-890b-cccfff943a70,name=sour_budou,properties={textures=[com.mojang.authlib.properties.Property@8df9c15]},legacy=false] (/175.31.45.221:10494) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@6cd72926[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@5093cbb0]},legacy=false] (/106.112.42.42:10580) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@633dde77[id=9c4fac1d-18e3-3cf0-9731-0fbca9c39d73,name=SpecialCheni,properties={},legacy=false] (/115.151.185.70:10595) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@207e7d2f[id=ffce59d6-cc43-304d-91f0-61146214da81,name=HellHunter,properties={textures=[com.mojang.authlib.properties.Property@3035ccf5]},legacy=false] (/192.168.1.101:10627) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7607ccb9[id=459f2a53-ed94-38d3-8e07-e3a112061d1c,name=Hilendare,properties={textures=[com.mojang.authlib.properties.Property@5fc43831]},legacy=false] (/113.12.144.215:10626) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@23cc4546[id=fc4784e4-ab7d-3526-b4d1-218c0aabc5e8,name=KongcHecanO,properties={},legacy=false] (/123.154.162.22:10625) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@2e0fe92e[id=907f8dcd-ce44-3bf1-af4e-98b740ebbc5c,name=uo_lwuy,properties={},legacy=false] (/101.29.74.249:10628) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7dcb7ec5[id=50216dce-f8f9-36da-92a2-5559fbc6f86e,name=23121,properties={},legacy=false] (/192.168.1.101:10624) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@35e117c1[id=ffcd58ec-a210-3d98-86ab-572c5348a288,name=xueyueyaodao,properties={textures=[com.mojang.authlib.properties.Property@47ff89ee]},legacy=false] (/58.22.57.150:10630) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7446824e[id=f58c9284-3aa7-3720-957d-4d8508826675,name=kasumi,properties={textures=[com.mojang.authlib.properties.Property@3825ef6c]},legacy=false] (/119.122.112.60:10631) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@25515371[id=97df1924-d9cf-38e8-8d03-f5ed38a95321,name=lIllIlIlIllIl,properties={textures=[com.mojang.authlib.properties.Property@6d22b5ae]},legacy=false] (/117.173.26.9:10629) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@34a3c48[id=c1858d7f-5c0d-3553-88f9-01dee365f69c,name=Dawn_Xinyu,properties={textures=[com.mojang.authlib.properties.Property@7591cae2]},legacy=false] (/123.52.28.89:10633) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@3e287cff[id=835a7489-1776-3437-890b-cccfff943a70,name=sour_budou,properties={textures=[com.mojang.authlib.properties.Property@7c5a6cb4]},legacy=false] (/175.31.45.221:10653) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7e3cdd86[id=fcf7b40c-b871-378e-8843-4862faaedf0c,name=XuAnXuAn4,properties={textures=[com.mojang.authlib.properties.Property@5d64e9b9]},legacy=false] (/112.3.143.184:10679) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@5159c3eb[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@40affdfb]},legacy=false] (/106.112.42.42:10734) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@3a30df4[id=9c4fac1d-18e3-3cf0-9731-0fbca9c39d73,name=SpecialCheni,properties={},legacy=false] (/115.151.185.70:10737) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7e1156fb[id=835a7489-1776-3437-890b-cccfff943a70,name=sour_budou,properties={textures=[com.mojang.authlib.properties.Property@ac0e57e]},legacy=false] (/175.31.45.221:10738) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@66597452[id=9c4fac1d-18e3-3cf0-9731-0fbca9c39d73,name=SpecialCheni,properties={},legacy=false] (/115.151.185.70:10794) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@7900a5e9[id=fcf7b40c-b871-378e-8843-4862faaedf0c,name=XuAnXuAn4,properties={textures=[com.mojang.authlib.properties.Property@348ea35e]},legacy=false] (/112.3.143.184:10809) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@6257cb90[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@4dcc57aa]},legacy=false] (/106.112.42.42:10899) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@1685ffaf[id=220b5f64-9bbd-3ffa-bfa3-adb51b2df1fb,name=rtgsg,properties={},legacy=false] (/140.250.248.47:10910) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@3bd3f2c9[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@42876f37]},legacy=false] (/106.112.42.42:10929) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@478037b7[id=9c4fac1d-18e3-3cf0-9731-0fbca9c39d73,name=SpecialCheni,properties={},legacy=false] (/115.151.185.70:10955) lost connection: Disconnected
[02:17:10 INFO]: com.mojang.authlib.GameProfile@1bd77f9c[id=8bd2c95d-2fa2-39dc-a732-13a0f3277ad7,name=j1angnan,properties={textures=[com.mojang.authlib.properties.Property@78dfda58]},legacy=false] (/106.112.42.42:11007) lost connection: Disconnected
[02:17:10 INFO]: j1angnan[/106.112.42.42:11079] logged in with entity id 2249052 at ([plot]-111.17500001192093, 64.0, -518.5602275457578)
[02:17:10 INFO]: [+] j1angnan
[02:17:10 INFO]: [反作弊] j1angnan 使用 Fabric 进入服务器!
[02:17:10 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[02:17:10 INFO]: UUID of player KongcHecanO is fc4784e4-ab7d-3526-b4d1-218c0aabc5e8
[02:17:10 INFO]: UUID of player rtgsg is 220b5f64-9bbd-3ffa-bfa3-adb51b2df1fb
[02:17:10 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[02:17:10 INFO]: UUID of player uo_lwuy is 907f8dcd-ce44-3bf1-af4e-98b740ebbc5c
[02:17:10 INFO]: UUID of player 23121 is 50216dce-f8f9-36da-92a2-5559fbc6f86e
[02:17:10 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[02:17:11 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[02:17:11 INFO]: UUID of player SpecialCheni is 9c4fac1d-18e3-3cf0-9731-0fbca9c39d73
[02:17:13 INFO]: 你治愈了 j1angnan (在线).
[02:17:13 INFO]: 已设置飞行模式 禁用 ，被操作玩家 j1angnan (在线).
[02:17:13 INFO]: [+] 23121
[02:17:15 INFO]: UUID of player 23121 is 50216dce-f8f9-36da-92a2-5559fbc6f86e
[02:17:15 INFO]: 23121[/192.168.1.101:11177] logged in with entity id 2249241 at ([plot]186.193262080839, 63.0, -516.705018012813)
[02:17:18 INFO]: 找不到这个玩家 (heal -> null)
[02:17:18 INFO]: 已设置飞行模式 禁用 ，被操作玩家 23121 (在线).
>
```

### Relevant Plugins

CMI 9.2.1.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment] 2022-07-04 05:24
i think you can close the issue. The issue was your server not responding for 180 secound. may it was overloaded from to many plugins, corrupted hardware or other threads that stacked to much.
Mostly this happens when the hardware of the used server is not good enough to handle the amount of thread or if a plugin using to much threads so the server cant work over them all... then he starts with quene the thread and if these quene gets to big it starts lagging and in worst case the server stops the repsonding...


`The server has not responded for 180 seconds! Creating thread dump.`
every plugin could be listed in the dump after. its depending on what plugin tried to create a thread at this moment in this case it was cmi.
You cant do anything here for the users if the server was not reating.
also at the end u see that this was no bug or crash and you should report it to purpur..well and also not else where ;)
`[02:17:09 ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---`

**Comment by Zrips** [comment] 2022-07-12 14:14
Error is from PlayerQuitEvent which was only triggered on server crash which happened long before this. This isint directly tied to CMI, it only included CMI into report as there was some issues closing server after it hang up.

**Closed by Zrips** 2022-07-12 14:14 UTC
Labels: bug report
