### ISSUE TITLE
PlayTimeRewards Message to Crash

### ISSUE THREAD

**Issue by catter1** [Zrips/CMI#3840] opened 2020-07-27 19:56 UTC
**Description of issue:**
every time PlayTimeRewards sends a public message, they crash with that error (below). It happens (noticeably) when using /heal or a player redeems a PlayTimeRewards. They will NOT crash if they are in supervanish because I have it configured not to send a public message if in sv. I believe /heal crashes the player as well because it sends them a message saying You have been healed!. The weirdest part about it - not only does it crash the player, but crashes all players near the player who is the cause of the message.

---

**ERROR**
```
######################
## catter1 lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) ##
## exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256) ##
######################
```

**CONFIG SECTION:**
```
#######################################
## PlayTimeRewards.yml: [(https://pastebin.com/WkShWk2h)] ##
#######################################
```

---

**Cmi Version:** 
8.7.4.0
**Server Type):** 
Paper
**Server Version:** 
git-Paper-87 MC 1.16.1

**Comment by Zrips** [comment] 2020-07-28 09:36
What is the display name of catter1? Strange question, i know.

**Comment by Zrips** [comment] 2020-07-28 09:41
Extra question: Do you use gradient colors?

**Comment by CloudeLecaw** [comment] 2020-07-28 10:21
Maybe his nickname is very long and he use different hex colors for each letter/symbol so his name is out of the allowed lengh aray for names.

**Comment by Zrips** [comment] 2020-07-28 10:39
@CloudeLecaw 
I was considering that, but i tested it with insanely long nickname with gradient colors, no issues there.

**Comment by catter1** [comment] 2020-07-28 17:46
> What is the display name of catter1? Strange question, i know.

It is long, but it works for every player, regardless of their nick. I guess I should have added this, but I *do* use LuckPerms if that helps. Let me know if I can provide any other information.

**Comment by catter1** [comment] 2020-07-28 17:51
For gradient colors: My luck perms prefix uses them, but I was crashing before I used them. As stated before, it works on all players... I *personally* think it has to do with the message of "[player] got $100 for playing for an hour." This is because if a staff member hops into super vanish, it does not kick them to lobby. *Though now that I think about it, I had disabled the public message...*

**Comment by catter1** [comment] 2020-07-28 17:53
> > What is the display name of catter1? Strange question, i know.

I'll say it anyways if it helps:
&b&l&k|&6&l&k|&b&l&k|&r {#0a0d36}&lSys{#ff0055}&lManager &6&l&k|&b&l&k|&6&l&k|&r &8{#e12eb1}&lCat
Super long, yes, but same for all players

**Comment by Zrips** [comment] 2020-07-30 13:53
Nah, this message is not a long one. It could be combination of couple plugins. And lately plugins like ChatControl started to struggle when it comes to handle new color codes. 
in general if you can reproduce it with some player, then some test server which is clone of your server would need to be setup for testing. We need to determine if this actually originates from CMI or this is issue with multiple plugin combination. That message from rewards is generic one which is processed with specialized command engine. So if you can initiate same specialized command in another place, like attaching to item or creating custom alias, then we will have some other issue. In general, we need to debug this one and determine cause, but this should be done from your end as i cant reproduce this issue and error message doesn't really say much. 
And you could try testing this issue with different clients, with official or cracked ones just to make sure its not related to one of those, as this error points to client failing when it comes to some packet processing, tho question would be whose fault it is.

**Comment by Zrips** [comment] 2020-08-12 13:26
Closing ticket for time being, if you still experience this issue with latest CMI and latest minecraft (1.16.2) version, let me know.

**Closed by Zrips** 2020-08-12 13:26 UTC
Labels: bug report, unconfirmed
