### ISSUE TITLE
Status command

### ISSUE THREAD

**Issue by Hundr** [Zrips/CMI#9241] opened 2024-10-20 09:23 UTC
### Description of Issue

"Status" command not working every time and when it does has large delay before displaying output

### Version Information

```shell
CMI: 9.7.6.11
CMILib: 1.5.1.6
```

### Errors

```shell
no errors generated
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Hundr** [comment] 2024-10-20 09:25
[05:22:15] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:22:22] [Server thread/INFO]: Hundr_ issued server command: /help lag
[05:22:26] [Server thread/INFO]:
[05:22:26] [Server thread/INFO]: --------------------------------------------------
[05:22:26] [Server thread/INFO]:  Platform: amd64 (Linux) Running threads: 57
[05:22:26] [Server thread/INFO]:  TPS: 19.85 (19.60 19.60 19.60 19.60)
[05:22:26] [Server thread/INFO]:  Cpu usage: 42.68% (4 cores)
[05:22:26] [Server thread/INFO]:  Uptime: 2 mins 42 secs
[05:22:26] [Server thread/INFO]:  Memory usage: 29.29% (1199.00/4096 MB)
[05:22:26] [Server thread/INFO]:  Java version: 21.0.4+7-LTS() Build:
[05:22:26] [Server thread/INFO]:  Disk usage: 66.67% (12/18 GB)
[05:22:26] [Server thread/INFO]:  1. HarMine3 3685 Chunks 1141 Entities 4356 tiles 2 players
[05:22:26] [Server thread/INFO]:  2. HarMine3_nether 529 Chunks 127 Entities 12 tiles 0 players
[05:22:26] [Server thread/INFO]:  3. HarMine3_the_end 529 Chunks 84 Entities 25 tiles 0 players
[05:22:26] [Server thread/INFO]: --------------------------------------------------
[05:22:28] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:22:41] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:22:43] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:22:44] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:22:45] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:23:28] [Server thread/INFO]: Hundr_ issued server command: /lag
[05:23:35] [Server thread/INFO]: Hundr_ issued server command: /status
[05:23:41] [Server thread/INFO]: Hundr_ issued server command: /uptime
[05:23:49] [Server thread/INFO]: Hundr_ issued server command: /mem
[05:23:53] [Server thread/INFO]: Hundr_ issued server command: /mem

**Comment by mrfloris** [comment] 2024-10-22 11:45
I've tried this on 100+ user servers and 5+ user servers, and can't reproduce this.

**Comment by Zrips** [comment] 2024-10-24 14:52
@Hundr 
Which server are you running? Output from **/cmi version** would be best one

**Comment by Hundr** [comment] 2024-10-24 17:11
```
[Server thread/INFO]: --------------------------------------------------
[Server thread/INFO]: CMI: 9.7.6.11 SqLite
[Server thread/INFO]: CMILib: 1.5.1.6
[Server thread/INFO]: Server: Spigot(4343) 1.21.1-R0.1-SNAPSHOT+
[Server thread/INFO]: CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Disabled
[Server thread/INFO]: Modules -> 66 enabled 1 disabled: votifier
[Server thread/INFO]: --------------------------------------------------
>pl
[Server thread/INFO]: Plugins (11): CMILib, LuckPerms, voicechat, FastLeafDecay, Vault, Essentials, EssentialsSpawn, VeinMiner, EssentialsChat, CMI, Jobs
```

To add to the original post I cannot seem to reproduce this any longer. There is still a small delay before the command outputs the results but it seems to be working every time now, using either the Status or Lag commands.

**Comment by Zrips** [comment] 2024-10-25 09:44
@Hundr 
Status command is being performed Async, so it will generally have some delay as it performs bunch of calculations relating to entities on entire server on its own pace, so it might take a second or two, tho its usually only takes longer for the first time, repeating calls would do it faster. Closing ticket for now, if issue reappears, let me know

**Closed by Zrips** 2024-10-25 09:44 UTC
Labels: bug report
