### ISSUE TITLE
Custom Permissions for Custom Recipes

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4113] opened 2020-08-30 05:36 UTC
**Description of feature/improvement request:**
Add the ability to create a permission node for custom recipes
---
### Detailed explanation of what it should do, when and in what situation: ###
When you create a custom recipe, the GUI should have a spot where you can enter a custom permission node to be used to be able to craft that recipe.
### Basic explanation as to why this feature is needed and/or useful to have: ###
Overall this would greatly improve the custom recipes so that you could make them unlockable at certain times, areas, quests and really integrate the recipes with other plugins.

**Comment by CloudeLecaw** [comment] 2020-08-31 15:21
duplicate of this
https://github.com/Zrips/CMI/issues/300

**Closed** 2020-12-18 15:05 UTC
Labels: feature request
