### ISSUE TITLE
/jump doesn't work to slabs

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#3669] opened 2020-07-07 05:47 UTC
**Description of issue:**
IF you try to /jump to a slab, it tells you "No block in sight or it's too far (max 100 blocks)" no matter how close you are to the slab.. It works fine to solid blocks

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    # Default distance for jump command. Can be overriden with cmi.command.jump.[amount] permission node
    JumpDefault: 100
```

---

**Cmi Version (using`/cmi version`):** 
[00:46:23 INFO]: --------------------------------------------------
[00:46:23 INFO]: CMI plugin version: 8.7.0.10 MySQL
[00:46:23 INFO]: Server: Paper(370) 1.15.2-R0.1-SNAPSHOT
[00:46:23 INFO]: CMI economy: False Vault: 1.7.2-b107 CMI Chat: False 
[00:46:23 INFO]: Modules -> 43 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[00:46:23 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
[00:46:48 INFO]: This server is running Paper version git-Paper-370 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment] 2020-07-11 14:51
Could not reproduce this issue. Could you provide picture of a location which dint worked for you?

**Comment by Momshroom** [comment] 2020-07-12 15:34
The end, jumping to Purpur slabs and/or stairs:
https://prnt.sc/tgdfln

**Comment by Zrips** [comment] 2020-07-21 16:00
Reproduced, will be fixed with next build

**Closed by Zrips** 2020-07-21 16:00 UTC
Labels: bug report, unconfirmed
